--- Generated by AutoGen
---
---@class MsgCmd_GetBGMDataReply
local MsgCmd_GetBGMDataReply = class("MsgCmd_GetBGMDataReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetBGMDataReply
function MsgCmd_GetBGMDataReply:Execute(reply)
    ---Insert Your Code Here!
    SelfProxyFactory.GetBGMDataProxy():InitBgmData(reply.BGM)
end

return MsgCmd_GetBGMDataReply
