---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2023/2/11 17:56
---@type FlowConst
FlowConst = require("Runtime.Plugins.FlowCanvas.Base.FlowConst")
---@type FlowMgr
FlowMgr = require("Runtime.System.X3Game.Modules.FlowCanvas.FlowMgr")
FlowMgr.Init()