---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaofang.
--- DateTime: 2022/12/30 18:37
---悔牌结束
local CatCardConst = require("Runtime.System.X3Game.Modules.CatCard.Data.CatCardConst")
---@type CatCard.BaseActionData
local BaseActionData = require(CatCardConst.BASE_ACTION_DATA_PATH)
---@class CatCard.RegretEndActionData :CatCard.BaseActionData
local RegretEndActionData = class("RegretEndActionData", BaseActionData)

function RegretEndActionData:ctor()
   
end

return RegretEndActionData
