--- Generated by AutoGen
---
---@class MsgCmd_SCoreAwakenStartReply
local MsgCmd_SCoreAwakenStartReply = class("MsgCmd_SCoreAwakenStartReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.SCoreAwakenStartReply
function MsgCmd_SCoreAwakenStartReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_SCoreAwakenStartReply
