--- Generated by AutoGen
---
---@class MsgCmd_GachaCountRewardReissueUpdateReply
local MsgCmd_GachaCountRewardReissueUpdateReply = class("MsgCmd_GachaCountRewardReissueUpdateReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GachaCountRewardReissueUpdateReply
function MsgCmd_GachaCountRewardReissueUpdateReply:Execute(reply)
    BllMgr.GetGachaBLL():STC_GachaCountRewardReissueUpdateReply(reply)
end

return MsgCmd_GachaCountRewardReissueUpdateReply
