--- Generated by AutoGen
---
---@class MsgCmd_CMSDefaultReply
local MsgCmd_CMSDefaultReply = class("MsgCmd_CMSDefaultReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.CMSDefaultReply
function MsgCmd_CMSDefaultReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_CMSDefaultReply
