---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2021/12/21 19:39
--- 所有ui子类的基类，会同步UIViewCtrl的周期函数

---@class UICtrl:GameObjectCtrl
UICtrl = class("UICtrl", GameObjectCtrl, true)

---界面打开
function UICtrl:OnOpen()
end

---界面关闭
function UICtrl:OnClose()
end

---界面显示
function UICtrl:OnShow()
end

---界面隐藏
function UICtrl:OnHide()
end

---界面focus
function UICtrl:OnFocus(...)
end

---界面blur
function UICtrl:OnBlur(...)
end

---添加回调相关
function UICtrl:OnAddListener()
end

---删除回调相关
function UICtrl:OnRemoveListener()
end

---是否需要往子类同步周期函数
---@return boolean
function UICtrl:IsNeedTransmitChild()
    return true
end

---断线重连
function UICtrl:OnReconnect()
    
end

--region topbar相关
---@protected 创建TopBar
---@param tfParent UnityEngine.Transform 父对象的transform
---@param currencyList  Define.ShowCurrencyType[]   Define.ShowCurrencyType或table 显示的货币列表
---@param backCallBack function 点击返回的回调函数
---@param showBack boolean 是否显示返回按钮
function UICtrl:CreateTopBar(tfParent, currencyList, backCallBack, showBack)
    if self.TopBarInstance == nil then
        self.TopBarInstance = TopBarCtrl.Create(self, tfParent, currencyList, backCallBack, showBack)
        self.TopBarInstance:SetStyle(UIUtil.GetValue(tfParent))
    else
        self.TopBarInstance:LoadData(self, currencyList, backCallBack, showBack)
    end
end

function UICtrl:SetTopBarStyle(styleId)
    if self.TopBarInstance ~= nil then
        self.TopBarInstance:SetStyle(styleId)
    end
end

---隐藏topbar
function UICtrl:HideTopBar()
    self.TopBarInstance:Hide()
end

---显示topbar
function UICtrl:ShowTopBar()
    self.TopBarInstance:Show()
end
--endregion

return UICtrl