--- Generated by AutoGen
---
---@class MsgCmd_GetCoinReply
local MsgCmd_GetCoinReply = class("MsgCmd_GetCoinReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetCoinReply
function MsgCmd_GetCoinReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GetCoinReply
