--- Generated by AutoGen
---
---@class MsgCmd_DailyPhoneStartReply
local MsgCmd_DailyPhoneStartReply = class("MsgCmd_DailyPhoneStartReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.DailyPhoneStartReply
function MsgCmd_DailyPhoneStartReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_DailyPhoneStartReply
