--- Generated by AutoGen
---
---@class MsgCmd_GetItemDataReply
local MsgCmd_GetItemDataReply = class("MsgCmd_GetItemDataReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetItemDataReply
function MsgCmd_GetItemDataReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GetItemDataReply
