--- Generated by AutoGen
---
---@class MsgCmd_AddItemOverLimitReply
local MsgCmd_AddItemOverLimitReply = class("MsgCmd_AddItemOverLimitReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.AddItemOverLimitReply
function MsgCmd_AddItemOverLimitReply:Execute(reply)
    ---Insert Your Code Here!
    BllMgr.GetGemCoreInstanceBLL():OnAddItemOverLimitReply(reply)
    BllMgr.GetItemBLL():OnAddItemOverLimit(reply.Rewards)
end

return MsgCmd_AddItemOverLimitReply
