--- Generated by AutoGen
---
---@class MsgCmd_DailyPhoneFinishReply
local MsgCmd_DailyPhoneFinishReply = class("MsgCmd_DailyPhoneFinishReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param data pbcmessage.DailyPhoneFinishReply
function MsgCmd_DailyPhoneFinishReply:Execute(data)

end

return MsgCmd_DailyPhoneFinishReply
