--- Generated by AutoGen
---
---@class MsgCmd_GetGuildMsgReply
local MsgCmd_GetGuildMsgReply = class("MsgCmd_GetGuildMsgReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetGuildMsgReply
function MsgCmd_GetGuildMsgReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GetGuildMsgReply
