--- Generated by AutoGen
---
---@class MsgCmd_DealGuildApplyReply
local MsgCmd_DealGuildApplyReply = class("MsgCmd_DealGuildApplyReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.DealGuildApplyReply
function MsgCmd_DealGuildApplyReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_DealGuildApplyReply
