--- Generated by AutoGen
---
---@class MsgCmd_GuildGetWishListReply
local MsgCmd_GuildGetWishListReply = class("MsgCmd_GuildGetWishListReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GuildGetWishListReply
function MsgCmd_GuildGetWishListReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GuildGetWishListReply
