---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by muchen.
--- DateTime: 2023/10/26 11:35
---@class KnockMoleProxy:BaseProxy
local KnockMoleProxy = class("KnockMoleProxy", BaseProxy)

function KnockMoleProxy:OnInit()

end

function KnockMoleProxy:OnClear()

end

---当前正在进行的打地鼠
---@return X3Data.KnockMoleLevelData
function KnockMoleProxy:GetCurKnockMoleLevelData(difficultyId)
    local curKnockMoleLevelData = X3DataMgr.Get(X3DataConst.X3Data.KnockMoleLevelData, difficultyId)
    return curKnockMoleLevelData
end

return KnockMoleProxy