--- Generated by AutoGen
---
---@class MsgCmd_GetSpecialDateTreeReply
local MsgCmd_GetSpecialDateTreeReply = class("MsgCmd_GetSpecialDateTreeReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param msg pbcmessage.GetSpecialDateTreeReply
function MsgCmd_GetSpecialDateTreeReply:Execute(msg)
    BllMgr.GetSpecialDateBLL():UpdateSpecialDateTreeInfo(msg)
end

return MsgCmd_GetSpecialDateTreeReply
