--- Generated by AutoGen
---
---@class MsgCmd_TowerSCoreUpdateReply
local MsgCmd_TowerSCoreUpdateReply = class("MsgCmd_TowerSCoreUpdateReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param data pbcmessage.TowerSCoreUpdateReply
function MsgCmd_TowerSCoreUpdateReply:Execute(data)
end

return MsgCmd_TowerSCoreUpdateReply
