--- Generated by AutoGen
---
---@class MsgCmd_FinishDateReply
local MsgCmd_FinishDateReply = class("MsgCmd_FinishDateReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.FinishDateReply
function MsgCmd_FinishDateReply:Execute(reply)
    ---Insert Your Code Here!
    Debug.LogWarning("收到服务器结束回应： MsgCmd_FinishDateReply")
    Debug.LogErrorTable(reply)
    BllMgr.GetDatePlanBLL():UpdateCompleteDateReply(reply.ContentList)
end

return MsgCmd_FinishDateReply
