--- Generated by AutoGen
---
---@class MsgCmd_GameFriendStaminaRecvReply
local MsgCmd_GameFriendStaminaRecvReply = class("MsgCmd_GameFriendStaminaRecvReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GameFriendStaminaRecvReply
function MsgCmd_GameFriendStaminaRecvReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GameFriendStaminaRecvReply
