---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2023/2/6 11:31
---
---@class FlowContext
---@field entity PureLogic.ClientEntity
local FlowContext = class("FlowContext")

function FlowContext:ctor()
    ---@type table[]
    self.tablePool = {}
    ---@type PureLogic.ClientEntity
    self.entity = nil
end

---@param entity PureLogic.ClientEntity
function FlowContext:SetEntity(entity)
    self.entity = entity
end

---@return number
function FlowContext:GetRealtime()
    return 0
end

---@return number
function FlowContext:GetDeltaTime()
    return 0
end

---@param min Int
---@param max Int
---@return Int
function FlowContext:Random(min, max)
    return math.random(min, max)
end

--region 事件注册/派发
---@param eventName string | int
---@vararg
function FlowContext:Dispatch(eventName, ...)
    EventMgr.Dispatch(eventName, ...)
end

---@param eventName string
---@param func function
---@param target table
function FlowContext:AddListener(eventName, func, target)
    EventMgr.AddListener(eventName, func, target)
end

---根据绑定的target反注册事件
---@param target table
function FlowContext:RemoveListenerByTarget(target)
    EventMgr.RemoveListenerByTarget(target)
end
--endregion

--region table 缓存池
---@return table
function FlowContext:GetTable()
    if #self.tablePool > 0 then
        return table.remove(self.tablePool)
    end
    return {}
end

---@param t table
function FlowContext:ReleaseTable(t)
    if t then
        table.clear(t)
        table.insert(self.tablePool, t)
    end
end
---endregion
return FlowContext