---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pc.
--- DateTime: 2020/9/27 20:00
---

local CatCardConst = require("Runtime.System.X3Game.Modules.CatCard.Data.CatCardConst")
local BaseAni = require(CatCardConst.BASE_ANIMATION_PATH)
local ExchagneCardAni = class("ExchagneCardAni",BaseAni)

function ExchagneCardAni:Execute(models,parent_models,speed,callback)
    self:SetIsRunning(true)
    self.end_call = callback
    local end_parent
    self.speed = speed
    self.running_count = 0
    local animation_st = CatCardConst.AnimationState.MOVE | CatCardConst.AnimationState.SCALE | CatCardConst.AnimationState.ROTATION_X | CatCardConst.AnimationState.ROTATION_Y
    local call = handler(self,self.OnModelFinish)
    for k,v in pairs(models) do
        if #v>0 then
            self.running_count = self.running_count + #v
            for index,model in pairs(v) do
                end_parent = parent_models[k][index]
                self.bll:CheckSound(CatCardConst.SoundType.DEFAULT,CatCardConst.Sound.SYSTEM_MIAO_CARDFLY)
                self.bll:CheckAnimation(CatCardConst.AnimationType.MOVE_MODEL,animation_st,model,end_parent,speed,call)
            end
        end
    end
end

---移动结束旋转Z
function ExchagneCardAni:OnModelFinish(model)
    if not model then
        Debug.LogError("[ExchagneCardAni]--failed",model)
        return
    end
    if not self.finish_call then
        self.finish_call = handler(self,self.OnFinish)
    end
    local start_rotation =  GameObjectUtil.GetComponent(model,nil,"Transform").localEulerAngles
    local end_rotation = GameUtil.GetVector(0,0,0)
    self:SetIsRunning(false)
    self.bll:CheckSound(CatCardConst.SoundType.DEFAULT,CatCardConst.Sound.SYSTEM_MIAO_CARDTURN)
    self:Play(CatCardConst.AnimationState.ROTATION,model,self.finish_call,start_rotation,end_rotation,CatCardConst.CARD_ROTATION_DT)
end

function ExchagneCardAni:OnFinish()
    self.running_count = self.running_count-1
    if self.running_count<=0 then
        self:SetIsRunning(false)
        local end_call = self.end_call
        self.end_call = nil
        if end_call then
            end_call()
        end
    end
end

return ExchagneCardAni