--- Generated by AutoGen
---
---@class MsgCmd_GuideFinishReply
local MsgCmd_GuideFinishReply = class("MsgCmd_GuideFinishReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param data pbcmessage.GuideFinishReply
function MsgCmd_GuideFinishReply:Execute(data)
	print("GuideFinishReply")
	Debug.LogTable(data)
end

return MsgCmd_GuideFinishReply
