---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2023/6/5 15:55
---

---@class Framework.GameObjectCtrl:Framework.BaseCtrl
---@field private objLinker PapeGames.X3UI.ObjLinker
---@field private gameObject GameObject
local GameObjectCtrl = class("Framework.GameObjectCtrl", Framework.BaseCtrl, true)

--region 周期函数
function GameObjectCtrl:OnHide()
end

function GameObjectCtrl:OnShow()

end
--endregion

--region 操作函数
function GameObjectCtrl:Hide()
end

function GameObjectCtrl:Show()

end

--销毁
function GameObjectCtrl:Destroy()
    self:InternalDestroy()
    Framework.BaseCtrl.Destroy(self)
end


--endregion

--region 底层调用
---设置owner 用于gameObject绑定lua脚本逻辑
---@param go UnityEngine.GameObject
---@param owner table
function GameObjectCtrl:SetOwner(go, owner)
    self.gameObject = go
    Framework.BaseCtrl.SetOwner(self, owner)
end

---设置linker(统一获取组件)
---@param objLinker PapeGames.X3UI.ObjLinker
function GameObjectCtrl:SetLinker(objLinker)
    self.objLinker = objLinker
end

---@return PapeGames.X3UI.ObjLinker
function GameObjectCtrl:GetLinker()
    return self.objLinker
end

---@param go UObject
---@param ctrlType X3Game.CtrlType
---@param viewType X3Game.ViewType 默认跟进ctrlType映射关系查找
---@return X3Game.Ctrl.UseArgName2
function GameObjectCtrl:GetOrAddCtrl(go, ctrlType, viewType)
    return Framework.GetOrAddCtrl(go, ctrlType, self, viewType)
end

---@param go GameObject
---@param viewType X3Game.ViewType 默认跟进ctrlType映射关系查找
---@return X3Game.View.UseArgName2
function GameObjectCtrl:GetOrAddView(go,viewType)
    return Framework.GetOrAddView(go,viewType,self)
end

---@private
function GameObjectCtrl:InternalDestroy()
    Framework.ClearComponents(self.gameObject)
end

---@private
---@return boolean
function GameObjectCtrl:IsAutoInit()
    return false
end

--endregion

return GameObjectCtrl