---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2023/6/6 21:23
---@class Framework.Parser
---@field CtrlParser Framework.CtrlParser
---@field ViewParser Framework.ViewParser
---@field UComponentParser Framework.UComponentParser
---@field UComponentTypeParser Framework.UComponentTypeParser
---@field Clear fun()

--region 扩展逻辑
Framework.Timer = require(string.concat(Framework.RootPath, "Common.Extern.Timer"))
Framework.Timer.proxy = TimerMgr
Framework.Logger = require(string.concat(Framework.RootPath, "Common.Extern.Logger"))
Framework.Logger.proxy = Debug
Framework.EventDispatcher = require(string.concat(Framework.RootPath, "Common.Extern.EventDispatcher"))
Framework.EventDispatcher.proxy = EventMgr
--endregion

--region 基础类
Framework.BaseCtrl = require(string.concat(Framework.RootPath, "Common.BaseCtrl"))
Framework.BaseParser = require(string.concat(Framework.RootPath, "Common.Parser.BaseParser"))
Framework.GameObjectCtrl = require(string.concat(Framework.RootPath, "Common.GameObjectCtrl"))
--endregion

--region  初始化解析器
Framework.Parser = {}
Framework.Parser.ViewParser = require(string.concat(Framework.RootPath, "Common.Parser.ViewParser")).new()
Framework.Parser.CtrlParser = require(string.concat(Framework.RootPath, "Common.Parser.CtrlParser")).new()
Framework.Parser.UComponentParser = require(string.concat(Framework.RootPath, "Common.Parser.UComponentParser")).new()
Framework.Parser.UComponentTypeParser = require(string.concat(Framework.RootPath, "Common.Parser.UComponentTypeParser"))
Framework.Parser.Clear = function()
    Framework.Parser.ViewParser:Clear()
    Framework.Parser.CtrlParser:Clear()
    Framework.Parser.UComponentParser:Clear()
end
--endregion




