---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2023/6/5 17:30
---@class UComponent.BaseComponent:Framework.Component
local BaseComponent = class("BaseComponent", Framework.Component)

--region 操作函数

---@param idx int 从0开始
---@param compType Framework.UComponentType 组件类型 使用枚举：UComponentType.GameObject
---@return UnityEngine.Object
function BaseComponent:GetChild(idx, compType)
    compType = compType and compType or UComponentType.GameObject
    return self:_InvokeFunc("GetChild", idx, compType)
end

---eg:self:SetPosition(x,y,z) 或者 self:SetPosition(Vector3)
---设置世界坐标
---@vararg number | UnityEngine.Vector3
function BaseComponent:SetPosition(...)
    self:_InvokeFunc("SetPositionXYZ", self:_InternalInvokeFunc("GetVectorXYZ", false, ...))
end

---获取坐标
---@return Vector3
function BaseComponent:GetPosition()
    return self:_InternalInvokeFunc("GetVector", false, self:GetPositionXYZ())
end

---@return number,number,number
function BaseComponent:GetPositionXYZ()
    return self:_InvokeFunc("GetPositionXYZ")
end

---vec3 or x,y,z
---@vararg number | UnityEngine.Vector3
function BaseComponent:SetLocalPosition(...)
    self:_InvokeFunc("SetLocalPositionXYZ", self:_InternalInvokeFunc("GetVectorXYZ", false, ...))
end

---获取坐标
---@return Vector3
function BaseComponent:GetLocalPosition()
    return self:_InternalInvokeFunc("GetVector", false, self:GetLocalPositionXYZ())
end

---获取坐标x,y,z
---@return number,number,number
function BaseComponent:GetLocalPositionXYZ()
    return self:_InvokeFunc("GetLocalPositionXYZ")
end

---设置屏幕坐标
---@vararg number | UnityEngine.Vector3 | UnityEngine.Vector2
function BaseComponent:SetScreenPosition(...)
    local x, y = self:_InternalInvokeFunc("GetVectorXYZ", false, ...)
    self:_InvokeFunc("SetScreenPositionXY", x, y)
end

---获取屏幕坐标
---@return Vector2
function BaseComponent:GetScreenPosition()
    return self:_InternalInvokeFunc("GetVector", false, self:GetScreenPositionXY())
end

---获取屏幕坐标
---@return number,number
function BaseComponent:GetScreenPositionXY()
    return self:_InvokeFunc("GetScreenPositionXY")
end

---设置Local Scale
---@vararg number | UnityEngine.Vector3
function BaseComponent:SetScale(...)
    self:SetLocalScale(...)
end

---获取Local Scale
---@return Vector3
function BaseComponent:GetScale()
    return self:_InternalInvokeFunc("GetVector", false, self:GetLocalScaleXYZ())
end

---@return number,number,number
function BaseComponent:GetScaleXYZ()
    return self:GetLocalScaleXYZ()
end

---@vararg number | UnityEngine.Vector3
function BaseComponent:SetLocalScale(...)
    self:_InvokeFunc("SetLocalScaleXYZ", self:_InternalInvokeFunc("GetVectorXYZ", false, ...))
end

---获取localScale
---@return number,number,number
function BaseComponent:GetLocalScaleXYZ()
    return self:_InvokeFunc("GetLocalScaleXYZ")
end

--vec2 or x,y,z
---@vararg number | UnityEngine.Vector2
function BaseComponent:SetSizeDelta(...)
    local x, y = self:_InternalInvokeFunc("GetVectorXYZ", false, ...)
    self:_InvokeFunc("SetSizeDeltaXY", x, y)
end

---@return  UnityEngine.Vector2
function BaseComponent:GetSizeDelta()
    return self:_InternalInvokeFunc("GetVector", false, self:GetSizeDeltaXY())
end

---@return  UnityEngine.Vector2
function BaseComponent:GetSizeDeltaXY()
    return self:_InvokeFunc("GetSizeDeltaXY")
end

---设置rotation
---@vararg number | Quaternion
function BaseComponent:SetRotation(...)
    self:_InvokeFunc("SetRotationXYZW", self:_InternalInvokeFunc("GetQuaternionXYZW", false, ...))
end

---@return Quaternion
function BaseComponent:GetRotation()
    return self:_InternalInvokeFunc("GetQuaternion", false, self:GetRotationXYZW())
end

---@return number,number,number,number
function BaseComponent:GetRotationXYZW()
    return self:_InvokeFunc("GetRotationXYZW")
end

---设置rotation

---@vararg number | Quaternion
function BaseComponent:SetLocalRotation(...)
    self:_InvokeFunc("SetLocalRotationXYZW", self:_InternalInvokeFunc("GetQuaternionXYZW", false, ...))
end

---@return Quaternion
function BaseComponent:GetLocalRotation()
    return self:_InternalInvokeFunc("GetQuaternion", false, self:GetLocalRotationXYZW())
end

---@return number,number,number,number
function BaseComponent:GetLocalRotationXYZW()
    return self:_InvokeFunc("GetLocalRotationXYZW")
end

---设置欧拉角
--@vararg number | Vector3
function BaseComponent:SetEulerAngles(...)
    self:_InvokeFunc("SetEulerAnglesXYZ", self:_InternalInvokeFunc("GetVectorXYZ", false, ...))
end

---@return Vector3
function BaseComponent:GetEulerAngles()
    return self:_InternalInvokeFunc("GetVector", false, self:GetEulerAnglesXYZ())
end

---@return number,number,number,number
function BaseComponent:GetEulerAnglesXYZ()
    return self:_InvokeFunc("GetEulerAnglesXYZ")
end

---设置欧拉角

---@vararg number | Vector3
function BaseComponent:SetLocalEulerAngles(...)
    self:_InvokeFunc("SetLocalEulerAnglesXYZ", self:_InternalInvokeFunc("GetVectorXYZ", false, ...))
end

---@return Vector3
function BaseComponent:GetLocalEulerAngles()
    return self:_InternalInvokeFunc("GetVector", false, self:GetLocalEulerAnglesXYZ())
end

---@return number,number,number
function BaseComponent:GetLocalEulerAnglesXYZ()
    return self:_InvokeFunc("GetLocalEulerAnglesXYZ")
end

---设置GameObject Layer
---@param layerNameOrId string | number
---@param includeChildren boolean 是否包含子节点
function BaseComponent:SetLayer(layerNameOrId, includeChildren)
    includeChildren = includeChildren or false
    self:_InvokeFunc("SetLayer", layerNameOrId, includeChildren)
end

---获取Layer Id
---@return int
function BaseComponent:GetLayer()
    return self:_InvokeFunc("GetLayer")
end

---获取Layer Name
---@return string
function BaseComponent:GetLayerName()
    return self:_InvokeFunc("GetLayerName")
end

---eg:self:SetEnable(UComponent.Button,true)
---@param compType Framework.UComponent
---@param isEnable boolean
function BaseComponent:SetEnable(compType, isEnable)
    if compType ~= nil then
        if isEnable == nil then
            isEnable = false
        end
        local res = Framework.AbstractType[compType]
        if res then
            for _, v in pairs(res) do
                self:_InvokeFunc("SetEnable", v, isEnable)
            end
        else
            Debug.LogErrorFormat("[SetEnable] failed,compType not find AbstractType please write [%s] to AbstractType", compType)
        end
    end
end

---@param active boolean
---@return boolean
function BaseComponent:SetActive(active)
    if active == nil then
        active = false
    else
        if active ~= false then
            active = true
        end
    end
    return self:_InvokeFunc("SetActive", active)
end

---节点自身是否Active
---@return boolean
function BaseComponent:IsActiveSelf()
    return self:_InvokeFunc("IsActiveSelf")
end

---节点自身是否Active
---@return boolean
function BaseComponent:IsActive()
    return self:IsActiveSelf()
end

---节点在Hierarchy中是否Active
---@return boolean
function BaseComponent:IsActiveInHierarchy()
    return self:_InvokeFunc("IsActiveInHierarchy")
end

---@param parent UObject
function BaseComponent:SetParent(parent)
    self:_InvokeByGameObject("SetParent",parent,false)
end

---@return Transform
function BaseComponent:GetParent()
    return  self:GetComponent(UComponentType.Transform).parent
end

--endregion


return BaseComponent