---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doudou.
--- DateTime: 2022/1/12 14:38
---@class MsgCmd_GMSendReply
local MsgCmd_GMSendReply = class("MsgCmd_GMSendReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))
function MsgCmd_GMSendReply:Execute(msg, request)
    Debug.LogFormat("GMResponse:%s", msg.Response)
    
    -- GM Msg Reply Handler
    if not table.isnilorempty(request) and not table.isnilorempty(request.Params) then
        if request.Params[1] == "condition" then
            if request.Params[2] == "params" then
                -- 彩蛋系统编辑器工具需要捕获这个检查结果
                if EEDebugMgr then EEDebugMgr:HandleGMMsgReply(msg, request) end
            end
        end
    end
    if not table.isnilorempty(request) and not table.isnilorempty(request.Params) then
        if request.Params[1] == "condition" then
            EventMgr.Dispatch("OnServerConditionCheck", msg, request)
        end
    end
end
return MsgCmd_GMSendReply