---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2021/12/24 14:30
--- 所有utils的partial类初始化

require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil")
require("Runtime.System.Framework.GameBase.UISystem.Utils.GameObjectUtil")
require("Runtime.System.Framework.GameBase.UISystem.Utils.RectTransformUtil")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_Button")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_Image")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_Input")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_Joystick")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_ListView")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_MotionHandler")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_TabMenu")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UIUtil_Text")
require("Runtime.System.Framework.GameBase.UISystem.Utils.UniWebViewUtil")