---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2022/3/9 12:37
---
---进入主界面状态，完成初始化
---@type MainHome.MainHomeConst
local MainHomeConst = require("Runtime.System.X3Game.Modules.MainHome.Data.MainHomeConst")
local AIAction = require("Runtime.System.X3Game.Modules.AIDesigner.Task.MainHome.Action.MainHomeBaseAIAction")
---检测主界面男主剧情
---Category:MainHome
---@class MainHomeCheckDialogue:MainHomeBaseAIAction
---@field dialogueId AIVar | int
---@field conversationName AIVar | string
local MainHomeCheckDialogue = class("MainHomeCheckDialogue", AIAction)
function MainHomeCheckDialogue:OnAwake()
    AIAction.OnAwake(self)
    self.checkDialogue = handler(self,self.CheckDialogueChangedRes)
end

function MainHomeCheckDialogue:OnEnter()
    local data = self.bll:GetData()
    local conf = data:GetStateConf()
    local dialogueId = 0
    local conversationName = ""
    if conf then
        dialogueId = conf.StateDialogueID
        conversationName = conf.StateConversation
    end
    EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_AI_PLAY_DIALOGUE, dialogueId, conversationName)
    EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_CHECK_DIALOGUE_CHANGED,self.checkDialogue)
end

function MainHomeCheckDialogue:CheckDialogueChangedRes(res)
    self.bll:SetHandlerRunning(MainHomeConst.HandlerType.DialogueChanged,res)
end

return MainHomeCheckDialogue