--- Generated by AutoGen
---
---@class MsgCmd_GetRoleBaseDataReply
local MsgCmd_GetRoleBaseDataReply = class("MsgCmd_GetRoleBaseDataReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetRoleBaseDataReply
function MsgCmd_GetRoleBaseDataReply:Execute(reply)
    SelfProxyFactory.GetRoleProxy():InitData(reply.Data)
end

return MsgCmd_GetRoleBaseDataReply
