---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by junjun003.
--- DateTime: 2022/9/19 17:10
---

local Base = require("Runtime.System.X3Game.Modules.GamePlayProcedure.ProcedureCtrl.GamePlayState")
---@class BlockTowerChooseState
local BlockTowerChooseState = class("BlockTowerChooseState", Base)

function BlockTowerChooseState:OnEnter()
    self.super.OnEnter(self)

    self.owner.m_LastOperationTime = 0
    if self.owner.changedChooseState == false then
        self.owner:GetGameData().showingAlert = true
        EventMgr.Dispatch("BlockTowerChooseAlert")
        self.owner.changedChooseState = true
    end
    self.owner.gameMode = self.owner:GetGameData().whoseTurn
    self.owner.gameController:SwitchPlayer(self.owner.gameMode)
    self.owner:EnableGameControl()
    self.owner:ClearBetweenState()
    self.owner:CheckEventToPlay(nil, false)
end

---@return string
function BlockTowerChooseState:GotoNextState()

end

return BlockTowerChooseState