---@class MiaoConst
local CatCardConst = {}

CatCardConst.ModeType = {
    None = 0,
    Normal = 1,
    OpenCard = 2,
    Func = 3,
}

---事件配置
CatCardConst.Event = {
    CAT_CARD_ENTER = "CAT_CARD_ENTER",
    CAT_CARD_EXIT = "CAT_CARD_EXIT",
    CAT_CARD_EXIT = "CAT_CARD_EXIT",
    CAT_CHECK_STATE = "CAT_CHECK_STATE",
    CAT_CARD_REFRESH_MODELS = "CAT_CARD_REFRESH_MODELS",
    CAT_CARD_CHECK_SPECIAL_STATE = "CAT_CARD_CHECK_SPECIAL_STATE",
    CAT_CARD_CHECK_ACTION = "CAT_CARD_CHECK_ACTION",
    CAT_CARD_EXECUTE_ACTION = "CAT_CARD_EXECUTE_ACTION",
    CAT_CARD_CHECK_ANIMATION = "CAT_CARD_CHECK_ANIMATION",
    CAT_CARD_CHECK_SOUND = "CAT_CARD_CHECK_SOUND",
    CAT_CARD_CHECK_EFFECT = "CAT_CARD_CHECK_EFFECT",
    CAT_CARD_CHECK_PIPELINE = "CAT_CARD_CHECK_PIPELINE",
    CAT_CARD_CHECK_PIPELINE = "CAT_CARD_CHECK_PIPELINE",
    CAT_CARD_ADD_MODEL_TO_POOL = "CAT_CARD_ADD_MODEL_TO_POOL",
    CAT_CARD_ADD_EFFECT_TO_POOL = "CAT_CARD_ADD_EFFECT_TO_POOL",
    CAT_CARD_SET_MODEL_ACTIVE = "CAT_CARD_SET_MODEL_ACTIVE",
    CAT_CARD_RESET_MODEL = "CAT_CARD_RESET_MODEL",
    CAT_CARD_ON_SELECT_MODEL = "CAT_CARD_ON_SELECT_MODEL",
    CAT_CARD_SET_MODEL_SELECT = "CAT_CARD_SET_MODEL_SELECT",
    CAT_CARD_SET_MODEL_CAN_SELECT = "CAT_CARD_SET_MODEL_CAN_SELECT",
    CAT_CARD_SET_TOUCH_ENABLE = "CAT_CARD_SET_TOUCH_ENABLE",
    CAT_CARD_REFRESH_VIEW = "CAT_CARD_REFRESH_VIEW",
    CAT_CARD_CHECK_RUNNIG = "CAT_CARD_CHECK_RUNNIG",
    CAT_CARD_REFRESH_CENTER_VIEW = "CAT_CARD_REFRESH_CENTER_VIEW",
    CAT_CARD_REFRESH_TIPS = "CAT_CARD_REFRESH_TIPS",
    CAT_CARD_LOCAL_STATE_CHANGE = "CAT_CARD_LOCAL_STATE_CHANGE",
    CAT_CARD_SET_CAT_SELECT = "CAT_CARD_SET_CAT_SELECT",
    CAT_CARD_SET_ALL_SELECT_CATS_IS_PICK = "CAT_CARD_SET_ALL_SELECT_CATS_IS_PICK",
    CAT_CARD_REFRESH_MODEL = "CAT_CARD_REFRESH_MODEL",
    CAT_CARD_SET_MAIN_VIEW_ACTIVE = "CAT_CARD_SET_MAIN_VIEW_ACTIVE",
    CAT_CARD_SET_VIEW_ACTIVE = "CAT_CARD_SET_VIEW_ACTIVE",
    CAT_CARD_CHANGE_ANIMATION_RUNNING_STATE = "CAT_CARD_CHANGE_ANIMATION_RUNNING_STATE",
    CAT_CARD_PLAY_REGRET_UI_ANIMATION = "CAT_CARD_PLAY_REGRET_UI_ANIMATION",
    CAT_CARD_SET_TOUCH_EMPTY_ENABLE = "CAT_CARD_SET_TOUCH_EMPTY_ENABLE",
    CAT_CARD_SET_TOUCH_CAN_EXECUTE_ACTION = "CAT_CARD_SET_TOUCH_CAN_EXECUTE_ACTION",
    CAT_CARD_SET_SLOT_PREVIEW_ACTIVE = "CAT_CARD_SET_SLOT_PREVIEW_ACTIVE",
    CAT_CARD_SET_ROB_NODE_SELECT = "CAT_CARD_SET_ROB_NODE_SELECT",
    CAT_CARD_SET_CARD_MASK_ACTIVE = "CAT_CARD_SET_CARD_MASK_ACTIVE",
    CAT_CARD_SET_WND_RT_ACTIVE = "CAT_CARD_SET_WND_RT_ACTIVE",
    CAT_CARD_ADD_RAY_CAST_CAMERA = "CAT_CARD_ADD_RAY_CAST_CAMERA",
    CAT_CARD_SET_MODEL_LAYER = "CAT_CARD_SET_MODEL_LAYER",
    CAT_CARD_SET_TOUCH_LOCK = "CAT_CARD_SET_TOUCH_LOCK",
    CAT_CARD_SET_WANDERING_TIPS_ACTIVE = "CAT_CARD_SET_WANDERING_TIPS_ACTIVE",
    CAT_CARD_CHECK_UI_EFFECT = "CAT_CARD_CHECK_UI_EFFECT",
    CAT_CARD_SHOW_TIPS = "CAT_CARD_SHOW_TIPS",
    CAT_CARD_ACTION_TYPE_CHANGE = "CAT_CARD_ACTION_TYPE_CHANGE",
    CAT_CARD_CHANGE_ICON = "CAT_CARD_CHANGE_ICON",
    CAT_CARD_SHOW_SCORE = "CAT_CARD_SHOW_SCORE",
    CAT_CARD_CHANGE_DIALOGUE_TIPS = "CAT_CARD_CHANGE_DIALOGUE_TIPS",
    CAT_CARD_SET_WND_ACTIVE = "CAT_CARD_SET_WND_ACTIVE",
    CAT_CARD_SET_FOLLOW_MODEL = "CAT_CARD_SET_FOLLOW_MODEL",
    CAT_CARD_CHECK_CARD_CAN_SELECT = "CAT_CARD_CHECK_CARD_CAN_SELECT",
    CAT_CARD_RECEIVE_SERVER_MSG = "CAT_CARD_RECEIVE_SERVER_MSG",
    CAT_CARD_BREAK = "CAT_CARD_BREAK",
    CAT_CARD_CONTINUE = "CAT_CARD_CONTINUE",
    CAT_CARD_CHOOSE_CONFIRM_EVENT = "CAT_CARD_CHOOSE_CONFIRM_EVENT",
    CAT_CARD_COMMON_CHOOSE_VIEW = "CAT_CARD_COMMON_CHOOSE_VIEW",
    CAT_CARD_ADD_MODEL_TO_TEMP = "CAT_CARD_ADD_MODEL_TO_TEMP",
    CAT_CARD_RELEASE_TEMP_MODEL = "CAT_CARD_RELEASE_TEMP_MODEL",
    CAT_CARD_RELEASE_SHOW_MODEL = "CAT_CARD_RELEASE_SHOW_MODEL",
    CAT_CARD_REMOVE_MODEL = "CAT_CARD_REMOVE_MODEL",
    CAT_CARD_ROTATION_MODEL = "CAT_CARD_ROTATION_MODEL",
    CAT_CARD_SET_FUNC_BTN_USE_ACTIVE = "CAT_CARD_SET_FUNC_BTN_USE_ACTIVE",
    CAT_CARD_REFRESH_TOAST = "CAT_CARD_REFRESH_TOAST",
    CAT_CARD_MODEL_SELECT_EVENT = "CAT_CARD_MODEL_SELECT_EVENT",
    CAT_CARD_SELECT_SLOT_CHANGE = "CAT_CARD_SELECT_SLOT_CHANGE",
    CAT_CARD_TIP_END_EVENT = "CAT_CARD_TIP_END_EVENT",
    CAT_CARD_POPSTATE_CHANGE = "CAT_CARD_POPSTATE_CHANGE",
    CAT_CARD_SET_SELECT_ENABLE = "CAT_CARD_SET_SELECT_ENABLE",
    CAT_CARD_CHECK_SELECT = "CAT_CARD_CHECK_SELECT",
    CAT_CARD_PARSE_PIPELINE = "CAT_CARD_PARSE_PIPELINE",
    CAT_CARD_ADD_MODEL_TO_SHOW = "CAT_CARD_ADD_MODEL_TO_SHOW",
    CAT_CARD_FINISH_FUNC_CARD_EVENT = "CAT_CARD_FINISH_FUNC_CARD_EVENT",
    CAT_CARD_SET_ALL_RUNNING_MODELS_LAYER = "CAT_CARD_SET_ALL_RUNNING_MODELS_LAYER",
    CAT_CARD_MAIN_TIP_INFO_REFRESH = "CAT_CARD_MAIN_TIP_INFO_REFRESH",
    CAT_CARD_DISCARD_BREAK_EVENT = "CAT_CARD_DISCARD_BREAK_EVENT",
    CAT_CARD_DISCARD_END_EVENT = "CAT_CARD_DISCARD_END_EVENT",
    CAT_CARD_CLEAR_TIP_PROGRESS = "CAT_CARD_CLEAR_TIP_PROGRESS",
    CAT_CARD_REFRESH_SCORE = "CAT_CARD_REFRESH_SCORE",
    CAT_CARD_REFRESH_BUFF_INFO = "CAT_CARD_REFRESH_BUFF_INFO",
    CAT_CARD_FINISH_LOCK_STATE = "CAT_CARD_FINISH_LOCK_STATE",
    CAT_CARD_GAME_PAUSE = "CAT_CARD_GAME_PAUSE",
    CAT_CARD_GAME_RESUME = "CAT_CARD_GAME_RESUME",
    CAT_CARD_DISCARD_STEAL_EVENT = "CAT_CARD_DISCARD_STEAL_EVENT",
    CAT_CARD_RESET_BUFF_EVENT = "CAT_CARD_RESET_BUFF_EVENT",
    CAT_CARD_ENDING_SHOWICON = "CAT_CARD_ENDING_SHOWICON",
    CAT_CARD_CHANGE_SCORE_EVENT = "CAT_CARD_CHANGE_SCORE_EVENT",
    CAT_CARD_SET_PLAYCARD_POS = "CAT_CARD_SET_PLAYCARD_POS",
    CAT_CARD_TIP_SELECT_RESULT = "CAT_CARD_TIP_SELECT_RESULT",
    CAT_CARD_SELECT_WANDER_ACTION = "CAT_CARD_SELECT_WANDER_ACTION",
    CAT_CARD_WANDER_RECEIVE_MSG = "CAT_CARD_WANDER_RECEIVE_MSG",
    CAT_CARD_CLEAR_ACTION_LIST = "CAT_CARD_CLEAR_ACTION_LIST",
    EXCHANGE_RECEIVE_MSG_EVENT = "EXCHANGE_RECEIVE_MSG_EVENT",
    REGRET_RECEIVE_MSG_EVENT = "REGRET_RECEIVE_MSG_EVENT",
    REGRET_CAUGHT_SUCCESS = "REGRET_CAUGHT_SUCCESS",
    REGRET_CAUGHT_SELECT_RESULT = "REGRET_CAUGHT_SELECT_RESULT",
    REGRET_STOP_HIM_EVENT = "REGRET_STOP_HIM_EVENT",
    REGRET_PASS_EVENT = "REGRET_PASS_EVENT",
    REGRET_WAITING_PLAYER_SELECT = "REGRET_WAITING_PLAYER_SELECT",
    REGRET_CHANGE_CARD_DATA_EVENT = "REGRET_CHANGE_CARD_DATA_EVENT",
    STEAL_SHOW_PRESTEAL_EVENT = "STEAL_SHOW_PRESTEAL_EVENT",
    STEAL_PRESS_STATE_CHANGE = "STEAL_PRESS_STATE_CHANGE",
    CAT_CARD_STEAL_RECEIVE_MSG = "CAT_CARD_STEAL_RECEIVE_MSG",
    ROB_GET_CARD_MSG_EVENT = "ROB_GET_CARD_MSG_EVENT",
    ROB_SELECT_EVENT = "ROB_SELECT_EVENT",
    CAT_CARD_DIALOGUE_GOTO_NEXT_STATE_EVENT = "CAT_CARD_DIALOGUE_GOTO_NEXT_STATE_EVENT",
    CAT_CARD_DIALOGUE_SET_VARIABLE_EVENT = "CAT_CARD_DIALOGUE_SET_VARIABLE_EVENT",
    ADD_ACTION_PIPELINE_EVENT = "ADD_ACTION_PIPELINE_EVENT",
    WAIT_TIME_OVER_EVENT = "WAIT_TIME_OVER_EVENT",
    WAIT_TIME_BREAK_EVENT = "WAIT_TIME_BREAK_EVENT",
    CAT_CARD_CLOSE_DISCARD_PANEL = "CAT_CARD_CLOSE_DISCARD_PANEL",
    CAT_CARD_SET_WND_TOUCH_ENABLE = "CAT_CARD_SET_WND_TOUCH_ENABLE",
    CAT_CARD_STOP_PIPE_LINE = "CAT_CARD_STOP_PIPE_LINE",
    CAT_CARD_REFRESH_STACK_EVENT = "CAT_CARD_REFRESH_STACK_EVENT",
}

CatCardConst.DialogueVariable = {
    ROLLID = 1, --出拳剧情树的ID
    PRECEDEINSTORY = 3, --出拳剧情树中的剧情先手
    REGRETCONDITIONSTORYID = 6, --悔牌时的条件ID，0--只有放弃， 1--可以换牌
    REGRETSTORYID = 4,  --悔牌时的选择ID
    SURRENDERID = 7 --投降时选择的ID
}

---状态
---@type CatCardConst.State
CatCardConst.State = {
    INIT = 0,
    ROLL = 1,
    INITHAND = 2,
    P1_PRE = 3, --玩家准备阶段
    P1_ACT = 4, --玩家出牌
    P2_PRE = 5, --npc准备阶段
    P2_ACT = 6, --npc出牌
    END = 7,
}

---出牌阶段子状态
---@type CatCardConst.SubState
CatCardConst.SubState = {
    MiaoSubStateInit = 0, -- 准备阶段
    MiaoSubStateFunc = 1, -- 出功能牌
    MiaoSubStateNum = 2, -- 出数字牌
    MiaoSubStateNumPlus = 3, -- 额外出数字牌阶段
}

---出牌阶段
---@type CatCardConst.PopCardState
CatCardConst.PopCardState = {
    None = 0,
    PopFuc = 1,
    PopNum = 2,
    PopNumPlus = 3,
}

CatCardConst.SeatType = {
    PLAYER = 1,
    ENEMY = 2,
}

CatCardConst.RoundRes = {
    NONE = 0,
    WIN = 1,
    LOSS = 2,
    DRAW = 3,
}

---@type CatCardConst.PlayerType
CatCardConst.PlayerType = {
    PLAYER = 0,
    ENEMY = 1,
}


---@type CatCardConst.CardType
CatCardConst.CardType = {
    SLOT = 1,
    CARD = 2
}

---@type CatCardConst.CardSubType
CatCardConst.CardSubType = {
    NORMAL = 1,
    SPECIAL = 2
}

---@type CatCardConst.BuffType
CatCardConst.BuffType = {
    PassCard = 1, --跳过喵
    FrozenCard = 2, --冰冻喵
    ExciteCard = 3, --兴奋喵
}

---@type CatCardConst.PlayerTypeSwitch
CatCardConst.PlayerTypeSwitch = {
    [CatCardConst.SeatType.PLAYER] = CatCardConst.PlayerType.PLAYER,
    [CatCardConst.SeatType.ENEMY] = CatCardConst.PlayerType.ENEMY,
}

---@type CatCardConst.SeatTypeSwitch
CatCardConst.SeatTypeSwitch = {
    [CatCardConst.PlayerType.PLAYER] = CatCardConst.SeatType.PLAYER,
    [CatCardConst.PlayerType.ENEMY] = CatCardConst.SeatType.ENEMY,
}


return CatCardConst