--- Generated by AutoGen
---
---@class MsgCmd_RefreshAndQueryFriendTotalInfoReply
local MsgCmd_RefreshAndQueryFriendTotalInfoReply = class("MsgCmd_RefreshAndQueryFriendTotalInfoReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.RefreshAndQueryFriendTotalInfoReply
function MsgCmd_RefreshAndQueryFriendTotalInfoReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_RefreshAndQueryFriendTotalInfoReply
