---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aoliao.
--- DateTime: 2023/1/6 10:58
---DevelopCardConst
---@class DevelopCardConst
local DevelopCardConst = class("DevelopCardConst")

DevelopCardConst.Event = {
    OnFullScreenCardClick = "DevelopCardConst.Event.OnFullScreenCardClick"
}
---@class DevelopCardConst.FullCardResState
DevelopCardConst.FullCardResState = {
    Complete = 0,
    None = 1,
    Download = 2
}
---@class DevelopCardConst.FullCardResDownloadingState
DevelopCardConst.FullCardResDownloadingState = {
    Downloading = 0,
    Pause = 1,
    Waiting = 2,
    Error = 3,
}
return DevelopCardConst