--- Generated by AutoGen
---
---@class MsgCmd_AskResetReply
local MsgCmd_AskResetReply = class("MsgCmd_AskResetReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.AskResetReply
function MsgCmd_AskResetReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_AskResetReply
