---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by muchen.
--- DateTime: 2022/11/4 11:47
---
local SDKTips = class("SDKTips")
require("Runtime.System.X3Game.Modules.UICommon.MessageBox.MessageBox")
local SDKDefine = require("Runtime.System.X3Game.Modules.SDK.SDKDefine")
--- 分三个阶段
--- 1、8岁以下不能充值
--- 2、8-16岁
--- 3、16-18岁
local function GetAgeRange(age)
    if age >= 8 and age < 16 then
        return 8, 16
    elseif age >= 16 and age < 18 then
        return 16, 18
    end
    return nil
end

---提示tips
function SDKTips.ShowMessageInfo(text)
    UICommonUtil.ShowMessage(text)
end

---打开初始化sdk失败tips
function SDKTips.ShowInitSdkFailTips(cb)
    UICommonUtil.ShowMessageBox(UITextHelper.GetUIText(UITextConst.UI_TEXT_5196), {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_call = function()
            SDKMgr.InitSDK(cb)
        end },
        { btn_type = GameConst.MessageBoxBtnType.CANCEL, btn_call = function()
            SDKMgr.ApplicationQuit()
        end, is_auto_close = false }
    }, AutoCloseMode.None)
end

---游客在游戏中超时
function SDKTips.TouristTimeOverTips()
    local BindAccountCB = function()
        if SDKMgr.IsHaveSDK() then
            SDKMgr.OnBindAccount()
        end
    end
    local levelGame = function()
        GameStateMgr.Switch(GameState.Logout)
    end
    local functions = {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5076), btn_call = BindAccountCB },
        { btn_type = GameConst.MessageBoxBtnType.CANCEL, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5161), btn_call = levelGame }
    }
    UICommonUtil.ShowMessageBox(UITextConst.UI_TEXT_5169, functions, AutoCloseMode.None)
end

---未实名进入游戏时时间耗尽
function SDKTips.TouristTimeOverWhenLoginGameTips()
    local BindAccountCB = function()
        if SDKMgr.IsHaveSDK() then
            SDKMgr.OnBindAccount()
        end
    end
    local levelGame = function()
        GameStateMgr.Switch(GameState.Logout)
    end
    local functions = {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5076), btn_call = BindAccountCB },
        { btn_type = GameConst.MessageBoxBtnType.CANCEL, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5161), btn_call = levelGame }
    }
    UICommonUtil.ShowMessageBox(UITextConst.UI_TEXT_5169, functions, AutoCloseMode.None)
end

---未成年人时间耗尽
function SDKTips.ChildTimeOverTips(time)
    UICommonUtil.ShowMessageBox(UITextHelper.GetUIText(UITextConst.UI_TEXT_5162, time), {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5076), btn_call = function()
            SDKMgr.ApplicationQuit()
        end, is_auto_close = false }
    }, AutoCloseMode.None)
end

---宵禁时间
function SDKTips.BanTime()
    UICommonUtil.ShowMessageBox(UITextConst.UI_TEXT_5160, {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5161), btn_call = function()
            SDKMgr.ApplicationQuit()
        end, is_auto_close = false }
    }, AutoCloseMode.None)
end

---未成年提示
function SDKTips.ShowChildTips()
    UICommonUtil.ShowMessageBox(UITextHelper.GetUIText(UITextConst.UI_TEXT_5159, time), {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5161), btn_call = function()
            SDKMgr.Logout(function()
                SDKMgr.Login()
            end)
        end
        }
    }, AutoCloseMode.None)
end

---打开LimitTips
function SDKTips.ShowLimitTips(limitType, time, isInGame)
    if limitType == SDKDefine.LimitType.Age then
        ---年龄受限
        SDKTips.ShowChildTips()
        return true
    end
    return false
    --if limitType == 1 then
    --    ---在线时长超限
    --    if SDKMgr.IsGuest() then
    --        if isInGame then
    --            SDKTips.TouristTimeOverTips()
    --        else
    --            SDKTips.TouristTimeOverWhenLoginGameTips()
    --        end
    --    else
    --        ---未成年人处理
    --        SDKTips.ChildTimeOverTips(self:_GetHours(time))
    --    end
    --    return true
    --elseif limitType == 2 then
    --    ---宵禁中
    --    SDKTips.BanTime()
    --    return true
    --end
end

---登陆状态失效
function SDKTips.LoginInvalid()
    if GameStateMgr.GetCurStateName() == GameState.Login then
        UICommonUtil.ShowMessage(UITextHelper.GetUIText(UITextConst.UI_TEXT_5113))
        EventMgr.Dispatch("LogoutGame")
    else
        UICommonUtil.ShowMessageBox(UITextHelper.GetUIText(UITextConst.UI_TEXT_5113), {
            { btn_type = GameConst.MessageBoxBtnType.CONFIRM,
              btn_call = function()
                  GameStateMgr.Switch(GameState.Logout,true)
              end,
              btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5732),
            }
        }, AutoCloseMode.None)
    end
end

--region 充值金额上限
---充值金额上限的tips
function SDKTips.ShowBuyMoneyLimitTips(chargeMoney, result)
    --local minAge, maxAge = GetAgeRange(age)
    --if age < 8 then
    --    ---"根据国家相关政策法规规定，未满8周岁的玩家无法在游戏内充值。"
    --    SDKTips.EightRechargeBanTips()
    --elseif chargeMoney >= onceLimitMoney then
    --    ---判断是哪种情况受限，目前只有2种超限，要么是单笔充值超限，要么是月充值超限
    --    ---单笔充值受限，游戏可根据返回的字段来组织提示文字
    --    SDKTips.SingleRechargeBanTips(minAge, maxAge, onceLimitMoney)
    --else
    --    ---月充值超限
    --    local total = tonumber(monthMoney) + tonumber(monthRemainMoney)
    --    SDKTips.MonthRechargeBanTips(minAge, maxAge, total, monthRemainMoney)
    --end
    local region = Locale.GetRegion()
    if region == Locale.Region.Japan then
        local total = tonumber(result.month_money) + tonumber(result.month_remain_money)
        local content = UITextHelper.GetUIText(UITextConst.UI_TEXT_50015, tostring(total), result.month_money, tostring(chargeMoney))
        local functions = {
            { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5164), btn_call = function()
            end },
        }
        UICommonUtil.ShowMessageBox(content, functions)
    end
end

---未满8周岁提示
function SDKTips.EightRechargeBanTips()
    local functions = {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5164), btn_call = function()
        end },
    }
    UICommonUtil.ShowMessageBox(UITextConst.UI_TEXT_5165, functions)
end

---单笔充值受限提示
function SDKTips.SingleRechargeBanTips(minAge, maxAge, onceLimitMoney)
    local functions = {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5164), btn_call = function()
        end },
    }
    local title = UITextHelper.GetUIText(UITextConst.UI_TEXT_5166, minAge, maxAge, onceLimitMoney)
    UICommonUtil.ShowMessageBox(title, functions)
end

---月充值受限提示
function SDKTips.MonthRechargeBanTips(minAge, maxAge, total, monthRemainMoney)
    local functions = {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5164), btn_call = function()
        end },
    }
    local title = UITextHelper.GetUIText(UITextConst.UI_TEXT_5167, minAge, maxAge, total, monthRemainMoney)
    UICommonUtil.ShowMessageBox(title, functions)
end
--endregion

---实名认证失败
---@param callBack function 重试回调
function SDKTips.RealNameFail(callBack)
    UICommonUtil.ShowMessageBox(UITextConst.UI_TEXT_5153, {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM, btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5154), btn_call = callBack }
    }, AutoCloseMode.None)
end

---登录失败提示 google服务连接失败
function SDKTips.ShowLoginTipsByGoogleServerFail()
    UICommonUtil.ShowMessageBox(UITextHelper.GetUIText(UITextConst.UI_TEXT_5195), {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM,
          btn_call = function()

          end,
          btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5732),
        }
    }, AutoCloseMode.None)
end

---购买充值失败提示 google服务连接失败
function SDKTips.ShowBuyTipsByGoogleServerFail()
    UICommonUtil.ShowMessageBox(UITextHelper.GetUIText(UITextConst.UI_TEXT_50030), {
        { btn_type = GameConst.MessageBoxBtnType.CONFIRM,
          btn_call = function()

          end,
          btn_text = UITextHelper.GetUIText(UITextConst.UI_TEXT_5732),
        }
    })
end

return SDKTips
