---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aoliao.
--- DateTime: 2023/1/10 15:46
---DynamicCardDownloadCtrl

---@type  ScatteredDownloadBase
local ScatteredDownloadBase = require("Runtime.System.X3Game.Modules.SubPackages.ScatteredDownloadBase")
---@class DynamicCardDownloadCtrl:ScatteredDownloadBase
local DynamicCardDownloadCtrl = class("DynamicCardDownloadCtrl", ScatteredDownloadBase)
---刷新UI状态
---@param downloadState SubPackage.PackageDownloadState
function DynamicCardDownloadCtrl:RefreshUI(downloadState)
    if not self.dataValid then
        return
    end
    if downloadState == PackageDownloadState.Finished then
        self:SetActive(nil, false)
    else
        self:SetActive(nil, true)
        if downloadState == PackageDownloadState.None then
            self:SetValue(nil, 0)
        elseif downloadState == PackageDownloadState.Downloading then
            self:SetValue(nil, 1)
        elseif downloadState == PackageDownloadState.Pause then
            self:SetValue(nil, 2)
        elseif downloadState == PackageDownloadState.Wait then
            self:SetValue(nil, 3)
        elseif downloadState == PackageDownloadState.Failed then
            self:SetValue(nil, 4)
        end
    end
end
---列表选中态的下载状态逻辑
function DynamicCardDownloadCtrl:Init()
    self.dataValid = false
    self:AddButtonListener(nil, handler(self, self.OnClickSelf))
end

function DynamicCardDownloadCtrl:OnClickSelf()
    if self.downloadState == PackageDownloadState.Finished then
        self:OnClickNormal()
    elseif self.downloadState == PackageDownloadState.None then
        self:OnClickDownload()
    elseif self.downloadState == PackageDownloadState.Downloading then
        self:OnClickPause()
    elseif self.downloadState == PackageDownloadState.Pause then
        self:OnClickDownload()
    elseif self.downloadState == PackageDownloadState.Wait then
        self:OnClickDownload()
    elseif self.downloadState == PackageDownloadState.Failed then
        self:OnClickDownload()
    end
end

---进度更新
function DynamicCardDownloadCtrl:OnDownloading(processValue)
    self.super.OnDownloading(self)
    self:SetText("OCX_txt_DownloadPercent", string.concat(processValue, "%"))
end

function DynamicCardDownloadCtrl:SetDownloadData(subPackageType, subPackageId)
    if nil == subPackageType or nil == subPackageId then
        self.dataValid = false
        self:SetActive(nil, false)
        return
    end
    self.dataValid = true
    ---@type ScatteredDownloadData
    local scatteredDownloadData = {
        type = subPackageType,
        subType = Define.SupPackageSubType.DEFAULT,
        value = subPackageId,
        finishCb = function()
            EventMgr.Dispatch("DynamicCardDownloadFinish")
        end,
    }
    self:InitData(scatteredDownloadData)
end

return DynamicCardDownloadCtrl