---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2021/7/16 14:49
---

---@class AIContext:Class
---@field master any
---@field view any
---@field logLevel AILogLevel
local AIContext = AIUtil.class("AIContext")

---@param master any
function AIContext:ctor(master)
    self.master = master
    self.logLevel = AILogLevel.None
    self.tablePool = {}
end

function AIContext:Destroy()
    self.master = nil
    self.tablePool = nil
end


---@param min Int
---@param max Int
---@return Int
function AIContext:Random(min, max)
    return min
end

---@param value float
---@return float
function AIContext:Ceil(value)
    return value
end

---@param value float
---@return float
function AIContext:Floor(value)
    return value
end

---@return number
function AIContext:GetRealtime()
    return 0
end

---@return number
function AIContext:GetDeltaTime()
    return 0
end

---@param key string
---@return AIVar
function AIContext:GetVariable(key)
    return nil
end

---@param type AIVarType
---@param value any
---@return any
function AIContext:ParseVarValue(type, value)
    return nil
end

---@return table
function AIContext:GetTable()
    if #self.tablePool>0 then
        return table.remove(self.tablePool)
    end
    return {}
end

---@param t table
function AIContext:ReleaseTable(t)
    if t then
        table.clear(t)
        table.insert(self.tablePool,t)
    end
end

return AIContext