---@class cfg.ActiveReward  excel名称:TaskBoard.xlsx
---@field ConditionCount int 奖励活跃要求
---@field ID int ID
---@field Remarks string ##备注
---@field RewardContent int 奖励内容组
---@field RewardCycle int 日常周长类型
