---@class cfg.ActivityGamePlay  excel名称:ActivityCenter.xlsx
---@field ActivityGameType int 玩法类-玩法类型
---@field BuyTimesRefreshType int 玩法类-购买次数重置类型
---@field ConnectStage int[] 玩法类-关联关卡
---@field GameBuyTimesCost cfg.s3int[] 玩法类-购买消耗
---@field GameBuyTimesLimit int 玩法类-购买次数上限
---@field GamePlayID int 玩法ID
---@field MaxTimesLimit int 玩法类-最大存储次数上限
---@field Times int 玩法类-每个重置点恢复次数
---@field TimesRefreshType int 玩法类-挑战次数重置类型
