---@class cfg.ActivityReward  excel名称:ActivityCenter.xlsx
---@field ActivityID int *活动ID
---@field ConditionCheck int[] 条件类型
---@field Rank int *档位
---@field Rewards cfg.s3int[] 奖励道具
---@field ShowRewards cfg.s3int[] 展示道具
