---@class cfg.ActiveRewardGroup  excel名称:TaskBoard.xlsx
---@field Description string ##奖励说明
---@field EndTime int 终止月日
---@field GroupID int 奖励组ID
---@field ID int 唯一Key
---@field Remark string ##备注
---@field RewardItem cfg.s3int[] 奖励内容
---@field StartTime int 开始月日
