---@class cfg.ActorSlotFSMConfig  excel名称:BattleActor.xlsx
---@field ActorID int 角色ID
---@field FSMFilename string 状态机文件名
---@field ID int 流水号
---@field SlotIndex int 槽位索引
---@field SlotType int 槽位类型
---@field TemplateArg undefined luastr 状态机参数
