---@class cfg.ArenaMatch  excel名称:Arena.xlsx
---@field ID int 唯一ID
---@field LeftMatchRangLimit int[] 左侧对手匹配上下限
---@field MatchType int 匹配方式
---@field MiddleMatchRangLimit int[] 中间对手匹配上下限
---@field RankLowerLimit int 排名积分下限
---@field RankUpperLimit int 排名积分上限
---@field RightMatchRangLimit int[] 右侧对手匹配上下限
