---@class cfg.ArenaDummy  excel名称:Arena.xlsx
---@field ID int 唯一ID
---@field ScoreLowerLimit int 积分匹配下限
---@field ScoreSetID int 关联scoreset表格
---@field ScoreUpperLimit int 积分匹配上限
---@field WeaponSetID int 关联weapon表格
