---@class cfg.ArenaEloConfig  excel名称:Arena.xlsx
---@field AWinRate int A玩家获胜期望
---@field BWinRate int B玩家获胜期望
---@field ID int 唯一ID
---@field ValueDifferentLowerLimit int 积分差值下限
---@field ValueDifferentUpperLimit int 积分差值上限
