---@class cfg.ArenaTopRank  excel名称:Arena.xlsx
---@field ID int 唯一ID
---@field PictureControl int 背景显示控制
---@field RankLowerLimit int 名次上限
---@field RankUpperLimit int 名次下限
---@field Reward cfg.s3int[] 奖励
