---@class cfg.AuditScene  excel名称:AuditScene.xlsx
---@field AliScene string[] 阿里云审核scene（预留，暂不用）
---@field Desc1 string ##来源说明
---@field PicSourceID int 图片来源ID
---@field ShumeiScene string[] 数美审核scene
