---@class cfg.BattleShapeConfig  excel名称:BattleShape.xlsx
---@field Angle Fix 扇形角度
---@field Height Fix 高度y轴
---@field ID int 形状体ID
---@field Length Fix 长度x轴或胶囊体长
---@field Note string ##备注
---@field PosOffset FVector3 坐标偏移量
---@field Radius Fix 半径
---@field RotateType int 旋转类型
---@field ShapeType int 形状类型
---@field Width Fix 宽度z轴
