---@class cfg.BattleAnimSound  excel名称:BattleSound.xlsx
---@field ActorName string *Actor名
---@field AnimName string *动作名字
---@field ID int 编号
---@field Note string #说明
---@field PlayType int 1动作播 2播放Timeline 3播放Event
---@field TimelinePath string TimelinePath
