---@class cfg.BattleTestInputData  excel名称:BattleTest.xlsx
---@field GroupDescr string #测试组说明
---@field ID int 唯一ID
---@field Name string #备注名称
---@field ScoreSetID int 关联ScoreSet表
---@field TestGroup int 测试组
---@field WeaponSetID int 关联WeaponSet表
