---@class cfg.BattleLevelAirWall  excel名称:BattleLevel.xlsx
---@field AngleY Fix 旋转
---@field Duration Fix 持续时间
---@field FxID int 特效
---@field ID int 空气墙编号
---@field Name string #备注
---@field Offset FVector3 偏移量
---@field ShapeArgs Fix[] 形状参数1
---@field ShapeType int 形状类型
