---@class cfg.BattleLevelMonsterConfig  excel名称:BattleLevel.xlsx
---@field BackgroundMusic string 怪物背景音
---@field FactionType int 怪物阵营类型
---@field Forward FVector3 怪物出生朝向
---@field ID int ID
---@field LevelID int 关卡ID
---@field MonsterGroup int 怪物分组编号
---@field MonsterID int 怪物角色ID
---@field Position FVector3 怪物出生坐标
---@field PropertyID int 单机属性ID
