---@class cfg.BodyPartData  excel名称:BodyPartData.xlsx
---@field AreaHandleName string 绑点名称
---@field AreaName string ##区域形状
---@field AreaSize cfg.vector3xml 区域大小
---@field AreaType int 区域类型
---@field Des string ##备注
---@field GroupID int *部位判定组
---@field ID int *唯一ID
---@field OffsetPos cfg.vector3xml 位置偏移量
---@field PartName string ##部位名称
---@field PartType int 部位枚举
