---@class cfg.BubbleList  excel名称:CompanySong.xlsx
---@field BubbleContent string 气泡文本
---@field BubbleImg string 气泡样式
---@field ConversationName string 男主反馈Conversation
---@field Des string ##备注
---@field ExclusiveType int 男主互动标识
---@field ID int 唯一ID
---@field InteractDialogueID int 气泡互动ID
---@field SettleTime int 气泡停留时长
