---@class cfg.BuffOperationConfig  excel名称:BattleSkill.xlsx
---@field BuffID int[] 对应BuffID
---@field BuffLevel int[] 对应Buff等级
---@field BuffTime Fix[] 对应Buff时间
---@field ID int ID
---@field MountType int 挂接目标类型
---@field Note string #Buff操作说明
---@field OperationType int Buff操作类型
---@field UseSkillLevel boolean 是否使用技能等级
