---@class cfg.CameraShake  excel名称:BattleCamera.xlsx
---@field Amplitude float 震屏强度
---@field Attack float 淡入时间
---@field CurveAsset string 震屏方式
---@field Decay float 淡出时间
---@field Description string #备注
---@field Duration float 震屏时长
---@field DurationFrame int #震屏帧数
---@field Frequency int 震屏次数
---@field ID int ID
---@field Priority int 优先级
