---@class cfg.CardSuit  excel名称:Card.xlsx
---@field Num int *套装数
---@field PassiveEffect cfg.s2int 套装效果对应被动
---@field SuitID int *套装编号
---@field SuitName int 套装名称&
---@field SuitPlusForce int 套装附加队伍战力
