---@class cfg.CardTemplate  excel名称:Card.xlsx
---@field ID int 流水号
---@field Level int *羁绊卡等级
---@field PropCritVal int 暴击率
---@field PropMaxHP int 血量
---@field PropPhyAtk int 攻击
---@field PropPhyDef int 防御
---@field Template int *属性模板编号
