---@class cfg.CardStar  excel名称:Card.xlsx
---@field AttrAddList cfg.s2int[] 其他属性加成
---@field CritHurtAdd int 基准暴击伤害
---@field ElementRatio int 基准元素适应系数
---@field GoldCost int 升星金币消耗
---@field ID int 唯一ID
---@field ItemCost cfg.s3int[] 升星材料消耗
---@field LevelLimit int 羁绊卡等级上限
---@field Note string ##备注
---@field PlayerLevel int 升至下一突破需要的玩家等级
---@field PropCritVal int 基准暴击率
---@field PropMaxHP int 基准生命值
---@field PropPhyAtk int 基准物理攻击
---@field PropPhyDef int 基准物理防御
---@field StarID int 突破组ID*
---@field StarLevel int 突破阶段*
