---@class cfg.Charge  excel名称:Charge.xlsx
---@field Active int 档位显隐
---@field ConsumeToken int 关联代币道具id
---@field FirstExDiamond int 首充双倍赠送数量
---@field HaveFirstCharge int 是否为首充双倍
---@field ID int 唯一ID
---@field Icon string 图标路径
---@field IfShowBackground int 背景底图是否特殊显示
---@field NormalExDiamond int 普通多次充值赠送数量
---@field OtherSystemID int 其他系统关联ID
---@field Price int 价格
---@field Sort int 排序id
---@field StarDimondNum int 星钻数量
---@field Type int 类型枚举
