---@class cfg.ConditionCheck  excel名称:CommonCondition.xlsx
---@field Description string 枚举说明
---@field Group string 分类
---@field Id int 条件枚举ID
---@field Param0 string 参数1
---@field Param1 string 参数2
---@field Param2 string 参数3
---@field Param3 string 参数4
---@field Param4 string 参数5
---@field Remarks string #备注
---@field TypeDes string ##类型说明
---@field TypeID int ##类型ID
