---@class cfg.CutSceneAsset  excel名称:CutSceneAsset.xlsx
---@field AssetPrefabName string 资产K子节点动画时动画的Prefab记录名（一旦使用后不能更改）
---@field Des string 描述（仅供查看）
---@field FileName string 资产名
---@field Group string 分组（ID选择用）
---@field Id int ID
---@field ModelKey string MainActor：裸模Key（RoleBaseModel）其他：模型资产Key（ModelAsset）
---@field PartKey string[] MainActor：部件Key（PartConfig）其他：空
---@field Type string 资产类型
