---@class cfg.DailyDateEndingWords  excel名称:DailyDateEntry.xlsx
---@field Description int 结局评价描述&
---@field Game string ##辅助列-玩法
---@field Group int 组ID
---@field ID int 唯一ID
---@field ManName string ##辅助列-男主
---@field Result string ##辅助列-结果
