---@class cfg.DailyConfideFeedback  excel名称:DailyPhoneBubble.xlsx
---@field ConversationNameShow string Conversation名
---@field Emotion int 情绪
---@field ID int 唯一ID
---@field MatterSubType int 具体事项
---@field MatterTips string ##事项备忘
---@field MatterType int 事项分类
---@field NodeIDShow int 节点ID
