---@class cfg.DailyDateRule  excel名称:DailyDateEntry.xlsx
---@field Des int ##备注
---@field GameType int 游戏类型
---@field Index int 唯一ID
---@field Order int 显示顺序
---@field PageName int[] 页面prefab的后缀
---@field PrefabName string 页面prefab的母名称（程序根据PageName加后缀）
---@field TypePara int[] 难度类型参数
