---@class cfg.DailyPhonePLAcpBubble  excel名称:DailyPhoneBubble.xlsx
---@field BubbleWord int 气泡文本&
---@field ConversationNameShow string Conversation名
---@field ID int ID
---@field NodeIDShow int 节点ID
---@field Num string ##编号用
---@field PLDialogID int PLDialog
---@field PLStateID int 女主状态组ID
---@field SemanticGroupID int 语义组
---@field Weight int 权重
