---@class cfg.DailyPhoneBonus  excel名称:DailyPhoneBubble.xlsx
---@field BonusTpye int Bonus类别
---@field ConversationNameShow string Conversation名
---@field ID int 唯一ID
---@field NodeIDShow int 节点ID
---@field Note string ##情境备忘
---@field Priority int 优先级
---@field SemanticGroupID int 语义组
---@field StageIndex int[] 陪伴阶段
---@field TargetTips string ##目标文本
