---@class cfg.DataSaveInfo  excel名称:DataSaveType.xlsx
---@field Class string 分类
---@field Desc string 描述
---@field Id int 类型ID
---@field RefreshType int 刷新类型
---@field SaveType int 存储类型
---@field SubID int 子键
