---@class cfg.DateServerEvent  excel名称:DateEventData.xlsx
---@field CommonCondition int 条件
---@field Conversation string 剧情段
---@field DesignDes string #策划备注
---@field EventGroup int 游戏阶段事件组ID
---@field Id int 事件ID
---@field Priority int 优先级
---@field StateDes string #阶段名称
---@field StateType int 阶段
