---@class cfg.DialogueKeyConfig  excel名称:BattleDialogue.xlsx
---@field CountLimit int 触发次数
---@field GroupID int 组ID
---@field Key string 对话Key
---@field KeyCD int Key冷却(单位/毫秒)
---@field KeyMutex string[] Key互斥
---@field Priority int 优先级
