---@class cfg.DialogueInfo  excel名称:DialogueInfo.xlsx
---@field ID int ID
---@field Name string 剧情文件名
---@field Order int 排序
---@field OriginDes int 语音收藏来源&
---@field StartConversation int 初始ConversationID
---@field StartScene string 剧情默认起始场景
---@field Type int 归属类型
