---@class cfg.DialogueReward  excel名称:DialogueReward.xlsx
---@field Asset int 关联剧本ID
---@field AssetName string ##Dialogue文件名称
---@field ConversationTitle string ##Conversation名
---@field Des string ##策划描述
---@field DiaryID int 掉落时间轴事件ID
---@field ID int ID
---@field Reward cfg.s3int[] 激活奖励
---@field StartConversation int 激活需经过ConversationID
---@field StartNodeID int 激活需经过NodeID
