---@class cfg.Drop  excel名称:Drop.xlsx
---@field Description string #掉落描述（仅查看用）
---@field GroupID int 掉落组ID
---@field ID int 掉落ID
---@field Item cfg.s3int[] 道具ID
---@field ItemSource int 关联途径类型
---@field Note string ##奖励说明
---@field Weight int 权值
