---@class cfg.DummiesConfig  excel名称:BattleModel.xlsx
---@field ID int *ID
---@field Key string *挂点Key
---@field Note string #归属角色
---@field Note2 string #用途
---@field PosOffset Vector3 挂点位置偏移
---@field XZAxisPath string 平面挂点路径
---@field YAxisPath string y轴挂点路径
