---@class cfg.EditorCharactorName  excel名称:EditorSetting.xlsx
---@field FinalName string 最终命名
---@field ID int 序号
---@field ModleName string 模型英文名
---@field ModleNo string 模型编号
---@field Note string 说明
---@field Suffix string 后缀
---@field Type int 类型
