---@class cfg.EmojiList  excel名称:CompanySong.xlsx
---@field ConversationName string 男主反馈Conversation
---@field EmojiName int 表情资源名&
---@field ExclusiveType int 男主互动标识
---@field FileName string 文件名
---@field ID int 唯一ID
---@field InteractDialogueID int 表情互动ID
---@field SettleTime int 表情弹幕停留时长
