---@class cfg.EnergyActionConfig  excel名称:EnergySet.xlsx
---@field ActionDescPar int[] 限制条件整型描述参数
---@field EnergyAction int 行为分类
---@field EnergyValue Fix[] 变化值
---@field ID int 序号
---@field Note string 说明
