---@class cfg.FaceSkin  excel名称:Face.xlsx
---@field Color string 整体叠加颜色RGB
---@field Des string ##备注
---@field ID int 唯一ID
---@field Icon string 预览小图标
---@field StyleSourceName string 资产贴图名_脸
---@field StyleSourceNameArm string 资产贴图名_手臂
---@field StyleSourceNameBody string 资产贴图名_全身
