---@class cfg.FaceLip  excel名称:Face.xlsx
---@field ColorID int 颜色ID
---@field ColorIcon string 唇色Icon
---@field DefaultGloss int 默认光泽度（0~1，除100后使用）
---@field Des string ##备注
---@field ID int 唯一ID
---@field ItemCondition int 道具条件
---@field RGBSource string RGB调色时使用贴图资产
---@field ShowType int 显示条件
---@field Source string 推荐唇妆资源贴图
---@field StyleID int 样式ID
---@field StyleIcon string 唇形Icon
