---@class cfg.FaceDecorate  excel名称:Face.xlsx
---@field Des string ##备注
---@field ID int 唯一ID
---@field ItemCondition int 道具条件
---@field PosX int 脸饰位置X（（-0.5~0.5之间）（配置INT，除1000后使用）
---@field PosY int 脸饰位置Y（（-0.5~0.5之间）（配置INT，除1000后使用）
---@field ShowType int 显示条件
---@field Source string 脸饰贴图资源
---@field StyleIcon string 脸饰样式Icon
