---@class cfg.FaceBoneDetail  excel名称:Face.xlsx
---@field BoneID int 对应部位ID（特效显示用）
---@field CameraNode string 相机节点名
---@field Class int 分类名&
---@field Des string ##备注
---@field ID int 唯一ID
---@field LimitMax int 参数最大限制（除100后使用）
---@field LimitMin int 参数最小限制（除100后使用）
---@field Name int 参数名&
---@field ParaName string 参数接口枚举名
---@field SubClass int 小类名&
---@field SubClassIconSelected string 小类图标（选中）
---@field SubClassIconUnSelect string 小类图标（未选中）
