---@class cfg.FaceEye  excel名称:Face.xlsx
---@field ColorID int 颜色ID
---@field ColorIcon string 瞳色Icon
---@field DefaultSize int 默认瞳孔大小（0~1.5，除100后使用）
---@field Des string ##备注
---@field ID int 唯一ID
---@field ItemCondition int 道具条件
---@field RGBSource string RGB调色时使用贴图资产
---@field ShowType int 显示条件
---@field Source string 推荐瞳色资源贴图
---@field StyleID int 样式ID
---@field StyleIcon string 瞳孔样式Icon
