---@class cfg.FaceHair  excel名称:Face.xlsx
---@field CanHighLight int 是否允许挑染
---@field ColorID int 颜色ID
---@field ColorIcon string 发色Icon
---@field DefaultGraDis int 默认渐变距离（0~1，除100后使用）
---@field Des string ##备注
---@field HighlightColorBottom string 挑染发尾颜色RGBA
---@field HighlightColorTop string 挑染顶部颜色RGBA
---@field ID int 唯一ID
---@field IsDefaultColor int 是否为默认颜色
---@field ItemCondition int 道具条件
---@field StyleID int 样式ID
---@field StyleIcon string 发型Icon
---@field StyleSourceID string 头发资产ID
---@field WholeColorBottom string 整体发尾颜色RGBA
---@field WholeColorTop string 整体顶部颜色RGBA
