---@class cfg.FaceClothTryOnList  excel名称:Face.xlsx
---@field Default int 是否默认穿戴
---@field Des string ##备注1
---@field Des2 string ##备注2
---@field ID int 唯一ID
---@field PartIcon string 部件Icon（弃用）
---@field PartSourceID string 配件资产ID（弃用）
---@field ResourceID int 服饰ID或头发ID
---@field Type int 部件类型
