---@class cfg.FashionTalkGroup  excel名称:Fashion.xlsx
---@field ID int ID
---@field Remark string ##对应皮肤/套装ID备注
---@field Remark2 string ##对应男主ID备注
---@field Remark3 string ##反馈编号
---@field Remark4 string ##对应皮肤/套装名备注
---@field TalkGroupID int 对话库组ID
---@field TalkText int 对话内容&
