---@class cfg.FormationCardPos  excel名称:FormationCardPos.xlsx
---@field FormationType int 编队类型*
---@field ID int 唯一ID
---@field OpenCondition int 该编队位开启条件关联SystemLockID
---@field PosType int 限定卡牌类型
---@field SlotID int 编队位ID*
