---@class cfg.Frame  excel名称:Frame.xlsx
---@field Description int 头像框说明&
---@field Get int 头像框获取方式&
---@field ID int 唯一ID
---@field Move int 是否为动态
---@field Name int 头像框名称&
---@field Order int 显示顺序
---@field Resource string 资源
---@field Role int 所属角色
---@field Show int 未获得时是否展示
