---@class cfg.GachaAll  excel名称:Gacha.xlsx
---@field CloseTime undefined time 关闭时间
---@field Cost1 cfg.s3int 单抽基准消耗
---@field Cost10 cfg.s3int 十连基准消耗
---@field CostTicket cfg.s3int 抽卡道具ID
---@field GachaCutScene string 星象仪表演prefab
---@field GachaGroup int 所属卡池组
---@field GachaName string ##卡池名称
---@field GachaPicture string 卡池图
---@field GachaScene string 星象仪背景prefab
---@field GachaTitle string 卡池标题图片
---@field GachaUp int[] 限定一览
---@field HideTime undefined time 卡池隐藏时间
---@field ID int 卡池ID
---@field JumpInterface int 跳转界面
---@field OpenOrClose int 是否开放
---@field OpenTime undefined time 开放时间
---@field Param1 int[] 男主解锁条件
---@field Param2 int 参数2
---@field ProbabilityPicture string 概率公示图
---@field ProbabilityWebsite string 概率公示网址
---@field Reward cfg.s3int[] 抽卡奖励
---@field Rule int[] 规则组
---@field RuleTxt int &规则文本
---@field SRPicture string SR保底图
---@field SSRPicture string SSR保底图
---@field ShowRemain int 是否显示剩余时间
---@field ShowResource cfg.s3int[] 显示资源
---@field ShowTime undefined time 卡池显示时间
