---@class cfg.GachaDrop  excel名称:Gacha.xlsx
---@field GroupID int 掉落组ID
---@field GroupName int ##掉落描述
---@field ID int 掉落ID
---@field ItemID cfg.s3int[] 道具ID
---@field Support1 int ##辅助列1
---@field Support2 int ##辅助列2
---@field Support3 int ##道具名称
---@field Weight int #权重
