---@class cfg.GaruanteeCount  excel名称:Gacha.xlsx
---@field CountType int 保底计数类型
---@field ID int 保底计数ID
---@field Param1 int[] 计数参数1
---@field Param2 cfg.s3int[] 计数参数2
---@field Param3 int[] 计数参数3
---@field Txt string ##计数说明
