---@class cfg.GemCoreSuit  excel名称:GemCore.xlsx
---@field AttrNum cfg.s2int 效果1的属性ID及数值
---@field Effect2 cfg.s2int 效果2
---@field EffectCondition1 int 效果1，件数需求
---@field EffectCondition2 int 效果2，件数需求
---@field Name int 芯核套装名称&
---@field SuitID int 芯核套装ID
---@field SuitIcon string 芯核套装图标
---@field SuitPlusForce2 int 效果2附加战力
