---@class cfg.GemCoreAttrDrop  excel名称:GemCore.xlsx
---@field Attr int 属性ID
---@field AttrGroupID int 属性组ID
---@field AttrID int 属性条目ID
---@field Description string ##属性组描述
---@field GlobalWeight int 随机权值
---@field ID int 唯一ID
---@field InternalWeight int 增加权值
