---@class cfg.GemCoreInstance  excel名称:GemCoreInstance.xlsx
---@field GemOutPut int[] 产出芯核种类
---@field GemShow int[] 产生芯核展示
---@field ID int 唯一ID
---@field LevelList int[] 副本列表
---@field Name int 玩法名称&
---@field SkipExport int 是否开放
---@field TeamType int 关联编队类型
