---@class cfg.GemRare  excel名称:GemCore.xlsx
---@field MaxLevel int 等级上限
---@field Rare int 芯核稀有度
---@field RarityBg string 稀有度背景图
---@field RarityIcon string 稀有度标识
---@field ResolveExp int 芯核分解经验
---@field ResolveExpRate int 芯核分解比例
