---@class cfg.GifImg  excel名称:GifImg.xlsx
---@field Desc1 string ##所属系统
---@field Desc2 string ##说明
---@field FrameNum int 序列帧数量
---@field Prefix string 前缀名
---@field SpriteAtlasName string 图集名称
---@field StringKey string 唯一StringKey
---@field Time float 动图总时长（秒）
