---@class cfg.GM  excel名称:GMCompose.xlsx
---@field Command string 指令字符串
---@field Description string 描述
---@field ID int 唯一ID
---@field Page int 页签
---@field Parameter1 string 参数1
---@field Parameter1Des string 参数1说明
---@field Parameter2 string 参数2
---@field Parameter2Des string 参数2说明
---@field Parameter3 string 参数3
---@field Parameter3Des string 参数3说明
---@field Remark int 类型备注#
---@field SendType int 发送类型
---@field Type int 指令类型
