---@class cfg.GMCompose  excel名称:GMCompose.xlsx
---@field ComposeCommand int[] 组合内容
---@field ID int 命令组合ID
---@field IsShow int 是否在面板显示
---@field Name string 组合命令字符串
---@field Remark string ##备注
---@field Type string ##分类
