---@class cfg.GMList  excel名称:GMCompose.xlsx
---@field Check string ##是否存在相同指令
---@field CommandName string 命令字符串
---@field ID int 命令组合ID
---@field Oldid string ##老的ID
---@field Txt string ##备注
---@field Type string ##类别
