---@class cfg.GraphicsScore  excel名称:GraphicsQuality.xlsx
---@field CPU string CPU2（3）
---@field GPU string GPU（2）
---@field ID int 唯一ID
---@field Memory int 内存（1）
---@field Score int 分数
---@field Type int 类型
