---@class cfg.GraphicsQuality  excel名称:GraphicsQuality.xlsx
---@field ConstString string Key
---@field Group int 组ID
---@field ID int 唯一ID
---@field Name string ##参数名称
---@field NumberToGear int[] 数值转换档位
---@field One int 低
---@field Three int 高
---@field Two int 中
---@field Zero int 关
