---@class cfg.GraphicsGroup  excel名称:GraphicsQuality.xlsx
---@field ConstString string Key
---@field Extreme int 超清
---@field Group int 组ID
---@field High int 高清
---@field Low int 流畅
---@field Middle int 标准
---@field Name int 参数名称&
---@field Order int 顺序
---@field Type int[] 类型
