---@class cfg.GroundMoveFx  excel名称:BattleFx.xlsx
---@field FxID int 特效ID
---@field GroundTextureID int *地面材质贴ID
---@field ID int 编号
---@field Note string #说明
---@field RunState string *移动动作
---@field SoundName string 音效
