---@class cfg.Guide  excel名称:Guide.xlsx
---@field CompleteWay int 完成方式
---@field EventCondition string 事件条件
---@field ExtraCondition int 额外条件
---@field GuideCondition int 引导条件
---@field ID int 唯一ID
---@field IsActive int 是否启用
---@field LevelCondition int 等级条件
---@field Order int 顺序备注
---@field PageUICondition string 页签界面条件
---@field Priority int 优先级
---@field ReMark string 描述备注
---@field SkipComplete int[] 跳过引导
---@field StageCondition int 通关条件
---@field TriggerType int 触发类型
---@field UIComponentCondition string 界面控件条件
---@field UICondition string 界面条件
---@field UnlockCondition int 解锁条件
