---@class cfg.GuideEvent  excel名称:Guide.xlsx
---@field ConstString string Key
---@field Des string #描述
---@field ID int 唯一ID
---@field Param1 string #参数1
---@field Param2 string #参数2
---@field Param3 string #参数3
---@field Param4 string #参数4
---@field ReMark string #归属系统
