---@class cfg.Heartbeat  excel名称:MainUIInteractive.xlsx
---@field Condition int 条件
---@field Desc string ##说明
---@field Dialogue int 剧本ID
---@field EndingConversation string 结束剧情-conversation名
---@field ID int 唯一ID
---@field Male int 所属男主
---@field Mode int 心跳模式
---@field OpeningConversation string 开场白-conversation名
---@field Weight int 抽取权重
