---@class cfg.HeartbeatMode  excel名称:MainUIInteractive.xlsx
---@field Amplitude int 震动强度
---@field Desc string ##说明
---@field HeartbeatImg int[] 跳动形状
---@field HeartbeatInterval cfg.s2int 跳动间隔（需填写：最小间隔+最大间隔）
---@field HeartbeatTime int 跳动总次数
---@field ID int 唯一ID
---@field NextStep int 下一阶段ID
---@field SoundEffect string 单次跳动音效
