---@class cfg.HunterWikiComments  excel名称:WorldInfoHunterWiki.xlsx
---@field Comment int 批注内容&
---@field DesID int 所属描述
---@field DesMark int 描述标记句&
---@field ID int 唯一ID
---@field MarkName int 批注者名称&
---@field MarkType int 批注者类型
