---@class cfg.HurtScarConfig  excel名称:BattleHurt.xlsx
---@field CenterColor float[] 实色颜色
---@field CenterDist float 实色最大宽度
---@field EdgeColor float[] 渐变颜色
---@field EdgeRemain float 边缘渐变最小宽度
---@field ID int 序号
---@field LifeTime float 砍痕生命周期
---@field Tex string 砍痕颜色贴图
---@field UVTiling Vector2 砍痕大小缩放
