---@class cfg.HurtEffect  excel名称:HurtSet.xlsx
---@field CenterColor float[] 实色颜色
---@field CenterDist float 最大宽度
---@field EdgeColor float[] 渐变颜色
---@field EdgeRemain float 最小宽度
---@field ID int 序号
---@field LifeTime float 砍痕生命周期
---@field Tex string 砍痕颜色贴图
---@field UVTiling float[] 砍痕大小缩放
