---@class cfg.InfoOverViewSystem  excel名称:InformationOverView.xlsx
---@field ConstString string 常量
---@field Effective int 是否生效
---@field ID int 功能枚举
---@field Jump int[] 跳转
---@field JumpType int 跳转类型
---@field Name int 收集项名称&
---@field Point int[] 点数
---@field System string ##所属系统（策划查看）
---@field Type int 显示样式
