---@class cfg.InformationPage  excel名称:Information.xlsx
---@field ID int 页签ID
---@field ModuleList int[] 内容模块组
---@field Name int 页签名称&
---@field Order int 排序ID
---@field Remark string #备注名称
---@field Type int 情报类型
