---@class cfg.InfoOverViewStage  excel名称:InformationOverView.xlsx
---@field Effect int 效果
---@field ID int 唯一ID
---@field Role int 角色
---@field Stage int 阶段
---@field Target int 作用对象
---@field TotalPoint int 所需点数
---@field Type int 作用对象类型
