---@class cfg.ItemComposite  excel名称:Item.xlsx
---@field CostItem1 cfg.s3int 合成消耗材料1
---@field CostItem2 cfg.s3int 合成消耗材料2
---@field CostItem3 cfg.s3int 合成消耗材料3
---@field CostItem4 cfg.s3int 合成消耗材料4
---@field Des string ##策划代号
---@field GlueID int ##粘合剂id
---@field GlueNum int ##粘合剂数量
---@field ID int 道具ID
---@field ItemID int ##合成材料id
---@field ItemNum int ##合成材料数量
---@field Name string ##道具名称
---@field Type string ##类型
