---@class cfg.ItemSource  excel名称:Item.xlsx
---@field Desc int 途径描述&
---@field ID int ID
---@field JumpID int 跳转ID
---@field ParaArr cfg.s2int[] 描述参数
---@field ProbabilityDesc int 商店概率刷出途径描述&
---@field Rank int 排序值
---@field Remark string ##备注
---@field SkipShow int 是否显示跳转按钮
