---@class cfg.LoadingContent  excel名称:LoadingContent.xlsx
---@field Description string #分组描述（仅查看）
---@field GroupID int 分组ID
---@field HorizontalPicture string 横屏配图名称
---@field ID int Tips唯一ID
---@field Picture string 组配图名称
---@field Tips int Tips内容&
