---@class cfg.Loot  excel名称:Loot.xlsx
---@field Description string ##关卡描述
---@field FixItemIDYieldNum cfg.s2float[] 不受Range影响道具
---@field ItemIDYieldNum cfg.s2float[] 受Range影响道具
---@field ItemSource int 关联掉落
---@field LootID int 掉落ID
---@field Note string ##备注
---@field Range float 浮动范围
