---@class cfg.LovePointLevel  excel名称:LovePointLevel.xlsx
---@field DailyGetLimit int 每日获得上限
---@field ID int ID
---@field Level int 等级ID
---@field NeedPlayerLevel int 需要角色等级
---@field NextAddLove int 升到下一级需要好感度
---@field PeriodID int 阶段ID
---@field PropAddPercent int 好感度对SCore属性加成（千分比）
---@field PropMaxHPScale int 好感度加成SCore血量千分比
---@field PropPhyAttackScale int 好感度加成SCore物理攻击千分比
---@field PropPhyDefenceScale int 好感度加成SCore物理防御千分比
