---@class cfg.LovePonitGuide  excel名称:LovePointLevel.xlsx
---@field Condition int 出现条件
---@field ID int ID
---@field JumpID string[] 跳转ID
---@field Name int 说明文字&
---@field Parameter1 int 跳转参数1
---@field Parameter2 int 跳转参数2
---@field Parameter3 int 跳转参数3
---@field RoleID int 男主ID
