---@class cfg.LovePointRole  excel名称:LovePointLevel.xlsx
---@field FlowerImage string 装饰花花图案
---@field HomeImage string 家园展示图
---@field ID int ID
---@field PhotoImage string 初始默认头图
---@field SmallWaterMark string 底板小水印
---@field WaterMark string 底板大水印
