---@class cfg.MainLineAchv  excel名称:MainLineAchv.xlsx
---@field AchvCondition1Desc int 成就条件1条件描述&
---@field AchvCondition1ID int 成就条件1条件组ID
---@field AchvCondition1Name int 成就条件1名称&
---@field AchvCondition1Reward cfg.s3int[] 成就条件1达成奖励
---@field AchvCondition2Desc int 成就条件2条件描述&
---@field AchvCondition2ID int 成就条件2条件组ID
---@field AchvCondition2Name int 成就条件2名称&
---@field AchvCondition2Reward cfg.s3int[] 成就条件2达成奖励
---@field AchvCondition3Desc int 成就条件3条件描述&
---@field AchvCondition3ID int 成就条件3条件组ID
---@field AchvCondition3Name int 成就条件3名称&
---@field AchvCondition3Reward cfg.s3int[] 成就条件3达成奖励
---@field Des string #自看关卡名
---@field ID int 关卡ID
