---@class cfg.MainUILight  excel名称:MainUI.xlsx
---@field CharacterLightSolution string 角色光照方案
---@field Desc1 string ##说明
---@field Desc2 string ##说明
---@field GroupID int *组ID
---@field MainUIScene int *主界面场景
---@field Role string ##角色
