---@class cfg.MainUIBGM  excel名称:MainUI.xlsx
---@field ID int 唯一ID
---@field Male int 对应男主
---@field Name int 名称&
---@field Resource string 资源名
---@field ShowCondtion int[] 显示条件
---@field Sort int 排序
