---@class cfg.MainUIScenePlace  excel名称:MainUI.xlsx
---@field ID int 唯一ID
---@field Male int 对应角色
---@field Name int 名称&
---@field RealTimeSceneCondition int[] 实时模式所需场景
---@field RealTimeSwitchGroup int 实时模式对应条件组
---@field Scene int[] 地点包含场景
