---@class cfg.MainUIScene  excel名称:MainUI.xlsx
---@field ID int 唯一ID
---@field Male int 对应角色
---@field Name int 名称&
---@field Place int 所属地点
---@field Resource string 资源名
---@field ShowCondtion int[] 显示条件
---@field TimeType int 时间类型
