---@class cfg.Medal  excel名称:Medal.xlsx
---@field Description int 徽章描述&
---@field Get int 徽章获取方式&
---@field ID int 唯一ID
---@field Name int 徽章名称&
---@field Order int 展示顺序
---@field Resource string 资源
---@field Role int 所属角色
---@field Show int 未获得时是否展示
