---@class cfg.MiaoCardFuncEffect  excel名称:MiaoCardFuncEffect.xlsx
---@field Desc string 效果名称&
---@field EffectType int 效果类型关联EffectType表
---@field ID int 功能牌效果ID
---@field Para0 int 参数0
---@field Para1 int 参数1
---@field Para2 int 参数2
---@field Prompt int 操作受限提示&
---@field Target int 目标类型
