---@class cfg.MiaoCardStack  excel名称:MiaoCard.xlsx
---@field FuncCardCountType cfg.s2int[] 功能牌的总数
---@field Index int 唯一Key
---@field NumCardCountPoint1 int 每种花色的1分牌的总数
---@field NumCardCountPoint2 int 每种花色的2分牌的总数
---@field NumCardCountPoint3 int 每种花色的3分牌的总数
---@field NumCardCountPoint4 int 每种花色的4分牌的总数
---@field NumCardCountPoint5 int 每种花色的5分牌的总数
---@field NumCardCountPoint6 int 每种花色的6分牌的总数
