---@class cfg.MiaoCardInfo  excel名称:MiaoCard.xlsx
---@field CardTypeMatch string[] 匹配底盘时的关联模型
---@field Class int 大类
---@field CupNumConnect cfg.s2int[] 杯子上数字的颜色类型匹配关系
---@field Index int 唯一Key
---@field NormalModel string[] 不同类型格子和牌的关联模型配置
---@field Num int 数字/功能枚举
---@field SubClass int 小类
---@field Type int 花色类型
