---@class cfg.MiaoCardSPAction  excel名称:MiaoCard.xlsx
---@field Des string ##注释
---@field Des2 string ##注释
---@field Des3 string ##注释
---@field Des4 string ##注释
---@field Des5 string ##注释
---@field Des6 string ##注释
---@field Des7 string ##注释
---@field FucPara0 int[] 行为参数0
---@field FucPara1 int[] 行为参数1
---@field FucPara2 int[] 行为参数2
---@field FucPara3 int[] 行为参数3
---@field FucPara4 int[] 行为参数4
---@field FucType int 特殊行为类型
---@field FucTypeDes string ##特殊行为类型
---@field ID int ID
---@field Script1 string 脚本函数名1
---@field Script2 string 脚本函数名2
