---@class cfg.MiaoBuff  excel名称:MiaoCardFuncEffect.xlsx
---@field BuffIcon string 状态图标
---@field CalPos int 结算位置1 使用完功能牌2 使用完数字牌
---@field Desc string 效果名称&
---@field Description int 状态描述&
---@field ID int ID
