---@class cfg.MiaoEffectType  excel名称:MiaoCardFuncEffect.xlsx
---@field ConstString string 类型名
---@field Desc string 描述
---@field ID int 类型ID
---@field Para0 string #参数1含义
---@field Para1 string #参数2含义
---@field Para2 string #参数3含义
---@field Tips string #备注
