---@class cfg.MiaoGachaPackLibrary  excel名称:MiaoGacha.xlsx
---@field ID int 卡包编号
---@field ModuleList int[] 关联卡片组
---@field PackName int 卡包名称&
---@field PackPicture string 卡包封面
---@field Rare int[] 隐藏款
---@field Reward cfg.s3int[] 奖励发放
---@field Sort int 排序
