---@class cfg.MiaoGachaDropALL  excel名称:MiaoGacha.xlsx
---@field CardName string ##名称
---@field DropGroupID int 掉落组
---@field DropID int 唯一ID
---@field DropNum int 掉落次数
---@field ItemID cfg.s3int[] 道具id
