---@class cfg.ModelAsset  excel名称:ModelAsset.xlsx
---@field Des string ##备注
---@field IsValid string 是否是有效数据  是的话 填1 否则留空
---@field PrefabPath string 模型资产路径
---@field StringKey string 唯一StringKey
---@field Type string ##类型
---@field Version string ##版本号
