---@class cfg.Module  excel名称:Module.xlsx
---@field ID int 唯一ID
---@field ModuleName int 模块名称&
---@field Priority int 优先级
---@field Remark int 策划备注#
---@field SubModule int[] 子模块数组
---@field Type int 类型
