---@class cfg.MonsterSummon  excel名称:BattleMonster.xlsx
---@field CritValScale Fix 暴击来源千分比
---@field DeadWithMaster int 是否随母体一起死亡
---@field ElementScale Fix 元素适应系数比例
---@field EnableBeLocked int 角色锁定
---@field HPScale Fix 生命值来源千分比
---@field ID int 召唤怪ID
---@field LifeTime Fix 生存周期
---@field MaxNum int 同场最大数量
---@field MonsterID int 怪物ID
---@field Name string 召唤怪名称
---@field PhyAttackScale Fix 物理攻击来源千分比
---@field PhyDefenceScale Fix 物理防御来源千分比
---@field ShowUI boolean 是否显示UI
---@field Source int 属性来源
