---@class cfg.MsgType  excel名称:PhoneMsg.xlsx
---@field BgDesc int 描述&
---@field ConstString string 类型名
---@field Desc int 描述&
---@field DescTimeColor int 日期颜色&
---@field GetTips int 获取提示&
---@field Id int 类型ID
---@field IsShow int 是否显示
