---@class cfg.MusicFunctionBGMStateConnect  excel名称:MusicFunctionControl.xlsx
---@field Des string ##注释
---@field EventName string Event名称
---@field ID int IndexID
---@field StateGroupName string StateGroup名
---@field StateName string State名
