---@class cfg.MyWeapon  excel名称:MyWeapon.xlsx
---@field DefaultSkinID int 默认武器皮肤
---@field DefaultTag int 默认武器标签
---@field Desc int 武器介绍&
---@field MyWeaponID int 女主武器ID
---@field Rare int 稀有度
---@field Recommend int[] 推荐搭配
---@field WeaponName int 武器名称&
---@field WeaponTag int[] 武器标签
---@field WeaponType int 武器类型ID
