---@class cfg.PathFindingCfg  excel名称:PathFindingCfg.xlsx
---@field AdjacentIndexs int[] 相邻索引
---@field FileName string *战场名称
---@field Gravity Vector3 重心
---@field ID int ID
---@field Index int *索引
---@field Vertex1 Vector3 顶点1
---@field Vertex2 Vector3 顶点2
---@field Vertex3 Vector3 顶点3
