---@class cfg.PerformConfig  excel名称:BattlePerform.xlsx
---@field EndEffectPath string 结束表现
---@field HideEnermy boolean 是否隐藏敌方
---@field ID int 编号
---@field IfHPM boolean 是否使用高模
---@field IfSkip boolean 是否受跳过表演影响
---@field Note string #表演说明
---@field RelativePath string 表演资产
---@field Transition string 转场过渡
---@field WideRelativePath string 横屏表演资产
