---@class cfg.PhoneCall  excel名称:PhoneCall.xlsx
---@field Contact int 对方ID
---@field Conversation int 对话ID
---@field ConversationDetail string 视频电话对应ConversationID
---@field DescForDesigner string ##策划用备注
---@field Dialogue int 视频电话对应DialogueID
---@field ID int 唯一ID
---@field IsShow int 未获得是否展示
---@field Name int 来电名称&
---@field Principal int 是否重要来电
---@field Reward cfg.s3int[] 接听奖励
---@field Type int 电话类型
