---@class cfg.PhoneMyMomentAns  excel名称:PhoneMoment.xlsx
---@field Contact int 联系人ID
---@field ID int 唯一ID
---@field LikeRate string 点赞概率condition=概率=延时Min=延时Max
---@field MomentID int 朋友圈ID
---@field MsgCallRate string 短信电话概率condition=概率=回复type=回复ID=延时Min=延时Maxtype20 ITEM_TYPE_MSG 短信type21 ITEM_TYPE_CALL 电话
---@field ReplyRate string 回复概率condition=概率=回复ID=延时Min=延时Max
