---@class cfg.PhoneContact  excel名称:PhoneContact.xlsx
---@field CallBg string 默认通话背景
---@field Description int 个人描述&
---@field HeadSmallIcon string 小头像
---@field ID int 唯一ID
---@field Mantype int 男主ID
---@field MomentCover string 默认朋友圈封面
---@field MsgBackground string 默认聊天背景
---@field MsgBubble string 默认聊天气泡
---@field Name int 名称&
