---@class cfg.PhoneMaleAutoAvatar  excel名称:PhonePersonality.xlsx
---@field AchievementCondition int 男主头像更换成就条件
---@field Des string ##策划备注
---@field ID int ID
---@field LovePointLevelCondition int 男主头像更换好感度条件
---@field PlayerLevelCondition int 男主头像更换玩家等级条件
---@field Role int 所属男主
---@field TimeCondition undefined time 男主头像更换时间条件
---@field Type cfg.s2int 更换方式
