---@class cfg.PhoneMsgConversationCondition  excel名称:PhoneMsg.xlsx
---@field ConditionGroup int 条件ID
---@field Des string ##对应短信ID
---@field Des1 string ##所属短信
---@field Des2 string ##男主
---@field Des3 string ##条件说明
---@field GroupId int 组ID
---@field Id int 唯一ID
---@field NextID int 跳转节点ID
---@field Weight int 抽取权重
