---@class cfg.PhoneOfficialComment  excel名称:PhoneOfficial.xlsx
---@field ArticleID int *文章ID
---@field CommentType int 评论类型
---@field Content int 留言内容&
---@field ID int *唯一ID
---@field Image string 评论头像
---@field Like int 点赞数
---@field Name int 评论人&
