---@class cfg.PhoneSignature  excel名称:PhonePersonality.xlsx
---@field AchievementCondition int 签名更换成就条件
---@field Des string ##策划备注
---@field ID int ID
---@field LovePointLevelCondition int 签名更换好感度等级条件
---@field PlayerLevelCondition int 签名更换玩家等级条件
---@field Reward int 触发后掉落的奖励
---@field Role int 所属男主
---@field Text int 签名内容&
---@field TimeCondition undefined time 签名更换时间条件
