---@class cfg.PhoneMsgConversation  excel名称:PhoneMsg.xlsx
---@field ConditionChoice cfg.s2int[] 额外选项
---@field ConditionNextID cfg.s2int[] 条件分支
---@field Content int 发送内容&
---@field Cover string 视频封面
---@field DelayTime int 阅读时间
---@field ID int 唯一ID
---@field MsgID int 信息ID
---@field NextID int[] 下个节点ID
---@field RecallTime int 撤回时间
---@field RedBag cfg.s3int[] 红包奖励
---@field Remark int 备注&
---@field Resource string 资源内容
---@field Reward cfg.s3int[] 额外奖励
---@field Teller int 发送人
---@field Time int 输入时间
---@field Type int 内容类型
---@field VoiceTime int 语音时长
