---@class cfg.PhoneMsgBubble  excel名称:PhoneMsgBubble.xlsx
---@field ID int 气泡ID
---@field MaleInterest int[] 男主喜好元素
---@field Name int 气泡名称&
---@field ResourceBG string 气泡底图资源
---@field ResourceDecoration1 string 气泡装饰1资源
---@field ResourceDecoration2 string 气泡装饰2资源
---@field ResourceDecoration3 string 气泡装饰3资源
---@field ResourceDecoration4 string 气泡装饰4资源
---@field Role int 所属男主
---@field TextColor string 气泡文字颜色
