---@class cfg.PhoneAvatarPendant  excel名称:PhoneAvatar.xlsx
---@field AchievementCondition int 成就条件
---@field Contact int[] 佩戴者
---@field Des string ##策划备注
---@field EndTime undefined time 显示结束时间
---@field ID int 挂件ID
---@field Resource string 挂件资源
---@field StartTime undefined time 显示开始时间
