---@class cfg.PhoneMomentCover  excel名称:PhonePersonality.xlsx
---@field AchievementCondition int 朋友圈头图更换成就条件
---@field Des string ##策划备注
---@field ID int ID
---@field LovePointLevelCondition int 朋友圈头图更换好感度等级条件
---@field PlayerLevelCondition int 朋友圈头图更换玩家等级条件
---@field Resource string 资源名称
---@field Role int 所属男主
---@field TimeCondition undefined time 朋友圈头图更换时间条件
