---@class cfg.PhotoRoleHosting  excel名称:Photo.xlsx
---@field Desc string ##说明
---@field Duration cfg.s2int 切换动作持续时间
---@field Frequency cfg.s2int 切换动作次数
---@field ID int 唯一ID
---@field Interval cfg.s2int 切换动作等待时间
---@field Model int 所属模式
---@field Role string 角色ID
