---@class cfg.PhotoTag  excel名称:Photo.xlsx
---@field Des string ##说明
---@field FucType string 功能类型
---@field ID int 唯一ID
---@field Name int 页签名称&
---@field Order int 页签显示顺序
---@field ShowStage int 显示阶段
---@field SubTag int[] 包含二级页签
---@field TagType int 页签类型
