---@class cfg.PhotoSuitStickers  excel名称:PhotoSuit.xlsx
---@field ID int 唯一ID
---@field StickerID int 贴纸ID
---@field StickerPos Vector3 贴纸位置
---@field StickerRot Vector3 贴纸旋转
---@field StickerScale float 贴纸缩放
---@field StickersGroup int 贴纸编组
