---@class cfg.PhotoBrush  excel名称:Photo.xlsx
---@field ID int 唯一ID
---@field Icon string 笔刷icon
---@field ItemID int 激活道具
---@field Model int 所属模式
---@field Resource string[] 笔刷资源（按顺序填写组成笔刷的单张图片名）
---@field Role int 所属角色
