---@class cfg.PhotoSticker  excel名称:Photo.xlsx
---@field ID int 贴纸ID
---@field Icon string 贴纸icon
---@field IsBasePackage int 是否进A包
---@field ItemID int 贴纸激活道具
---@field Model int 所属模式
---@field Name string ##说明
---@field Resource string 资源
---@field Role int 所属角色
---@field Type int 贴纸类型
