---@class cfg.PhotoResponse  excel名称:PhotoResponse.xlsx
---@field Conversation string 反馈剧情Conversation名
---@field Desc string ##策划用备注
---@field DialogID int 反馈剧情ID
---@field ID int 唯一ID
---@field Male int 所属男主
---@field Mode int 所属模式
---@field Probability int 反馈库触发概率
---@field SubType int 反馈子类
---@field Type int 反馈类型
