---@class cfg.PhotoRole  excel名称:Photo.xlsx
---@field CameraFollow string 相机跟随点
---@field CameraLookAt string 相机看点
---@field Des string ##说明
---@field DummyName string 头像截取点名称
---@field GroupID int 部位判定组
---@field ID int 角色ID
