---@class cfg.PlayerTag  excel名称:PlayerTag.xlsx
---@field AssociateTag int[] 关联标签
---@field Desc1 string ##分类说明
---@field Desc2 string ##额外属性说明
---@field ExtraFeature int[] 标签额外属性
---@field ID int 标签ID
---@field Name int 标签名称&
---@field RefreshPara int 刷新时间参数
---@field RefreshType int 刷新时间类型
---@field Type int 标签大类
