---@class cfg.PlayerFavorites  excel名称:PlayerTag.xlsx
---@field ID int 主题ID
---@field Name int 主题名称&
---@field Num int 最大记录数量
---@field Positive int 正向or负向
---@field ReferenceExtraFeature int[] 关联特殊属性
---@field ReferenceType int 关联类型
---@field VariableName string ##变量名（分男主）
