---@class cfg.PreBattleDialogData  excel名称:BattleDialogue.xlsx
---@field DialogID int 战前对话编号
---@field DialogKey string 对话内容
---@field HeroType int 对话发起者
---@field ID int 唯一ID
---@field ManType int 所属男主
---@field ProtectTime int 对话保护时间
---@field ShowTime int 显示时间
---@field Sort int 战前对话顺序
