---@class cfg.Property  excel名称:Attr.xlsx
---@field BgIcon string 属性背景图
---@field CodeName string ##代码中属性名称
---@field Comment string ##备注
---@field ConstString string 属性常量
---@field CorrelationPercentId int 关联千分比属性ID
---@field Description string 属性名称
---@field GSRatio int 战力计算系数（除100后计算）
---@field Id int 属性ID
---@field MinValue Fix 属性最小值
---@field PLBasePropTemplate int 女主基准属性模板
---@field ShowName int 描述&
---@field ShowPercent int 面板显示百分比
---@field StringName string ##属性常量名计算
---@field Type string ##属性类型
