---@class cfg.Questionaire  excel名称:Questionaire.xlsx
---@field JumpToQuest string 跳转链接
---@field Priority int 优先级
---@field QuestionnaireID int 问卷ID
---@field QuestionnaireReward cfg.s3int[] 问卷奖励
---@field TouchOffPoint int[] 触发节点
