---@class cfg.Radio_RY_0005  excel名称:Radio_RY_0005.xlsx
---@field DialogueText int 对话文字&
---@field DialogueTime int 字幕时间（毫秒）
---@field ID int 节点ID
---@field RadioReward int 广播剧奖励ID
---@field RoleID int 说话者ID
---@field VoiceName string 语音
