---@class cfg.Reason  excel名称:Reason.xlsx
---@field ConstString string 唯一Key
---@field Desc string 描述
---@field Done int #是否已埋点
---@field Id int 唯一ID
---@field SubID string ##辅助列id
---@field SystemID1 string #所属系统
---@field SystemKey1 string #系统key
---@field SystemName string #系统
