---@class cfg.RedPoint  excel名称:RedPoint.xlsx
---@field Childs cfg.s2int[] 红点child
---@field ConstString string 红点常量
---@field Des string ##描述
---@field ID int 红点id
---@field OperationType int 复合类型(子节点运算类型)
---@field SysIds int[] 系统解锁id列表
---@field Type int 红点显示类型
