---@class cfg.RoleBaseModel  excel名称:RoleBaseModel.xlsx
---@field DefaultCloth string[] 默认穿戴
---@field Des string ##备注
---@field IsValid string 是否是有效数据  是的话 填1 否则留空
---@field NeedFaceDate int 是否需要捏脸数据
---@field StringKey string 唯一StringKey
