---@class cfg.RoleClothSuit  excel名称:RoleClothSuit.xlsx
---@field AddFuncAsset string 附加功能脚本
---@field AddX3AnimatorAsset string 附加X3Animator脚本
---@field ClothList string[] 服装配饰组合
---@field Des string ##备注
---@field RoleBaseModelID string 角色裸模ID
---@field StringKey string 唯一StringKey
