---@class cfg.RoleReply  excel名称:CompanySong.xlsx
---@field ExclusiveDialogueID int 专属歌曲对白
---@field ExclusiveID int 男主专属歌曲
---@field ExclusiveTrigger int 触发专属对白进度点
---@field Exclusiveconversation string 专属歌曲对白
---@field ID int 唯一ID
---@field IsRecommend int 男主对某首歌是否进行推荐
---@field RecommendDialogueID int 推荐歌曲对白
---@field Recommendconversation string 推荐歌曲对白
---@field RoleID int *男主ID
---@field SongID int *歌曲ID
