---@class cfg.Rule  excel名称:Rule.xlsx
---@field Group int *组ID
---@field ID int *唯一ID
---@field Mark string #备注
---@field Page int 页ID
---@field Picture string 图片
---@field Text int 文本&
---@field Type int 类型
