---@class cfg.ScanningMonsterInfo  excel名称:Watch.xlsx
---@field Discription int 流浪体简介&
---@field ID int 流浪体ID
---@field MonsterType int 流浪体类型&
---@field Name int 流浪体名称&
---@field NuclearLevel string 芯核等级
---@field Num string 流浪体编号
---@field PictureForShow string 怪物静态图
---@field Risk string 危险度
