---@class cfg.SceneInfo  excel名称:SceneInfo.xlsx
---@field BackgroundNodePath string 2D替换面片路径
---@field Des string ##备注
---@field NavMeshPath string 寻路资产路径
---@field SceneName string 场景名
---@field ScenePath string 场景路径
---@field Update string ##更新备注
