---@class cfg.ScoreReco  excel名称:SCore.xlsx
---@field CardContent int 羁绊推荐内容&
---@field CardTitle int 羁绊推荐标题&
---@field GemCoreContent int 芯核推荐内容&
---@field GemCoreTitle int 芯核推荐标题&
---@field ID int 流水ID
---@field OrderNum int 推荐方案序号
---@field RecoCard int[] 推荐羁绊
---@field RecoGemCore int[] 推荐芯核
---@field ScoreID int ScoreID
