---@class cfg.SCoreLevel  excel名称:SCore.xlsx
---@field AttrAddList cfg.s2int[] 其他属性加成
---@field ID int 唯一ID
---@field Level int *等级
---@field LevelID int *等级组ID
---@field NextLvExp int 提升到下一级需要的经验量
---@field PropCritVal int 基准暴击率
---@field PropMaxHP int 基准生命值
---@field PropPhyAtk int 基准物理攻击
---@field PropPhyDef int 基准物理防御
