---@class cfg.Semantics  excel名称:Semantics.xlsx
---@field ForID int ##编号
---@field ID int Index
---@field MatchType int 匹配类别
---@field SemanticGroupID int 语义组
---@field Sentence string PL话语变体
---@field Threshold float ##阈值
---@field Tips1 string ##情境备注
---@field Tips2 string ##目标文本备注
