---@class cfg.ShopAll  excel名称:Shop.xlsx
---@field CloseTime undefined time 商店关闭时间
---@field ConstString string Key
---@field Filt int 是否筛选
---@field GroupID cfg.s2int[] 商店货物组
---@field ID int 商店ID
---@field MoneyID cfg.s3int[] 展示货币
---@field OpenOrClose int 商店是否开放
---@field OpenTime undefined time 商店开放时间
---@field RefreshLimit int 手动刷新次数
---@field RefreshPeriod int 商店刷新类型
---@field RefreshTime string 刷新时间点
---@field SerialNum int 商店排序
---@field ShopBG string 商店banner
---@field ShopCondition int 商店开放额外条件
---@field ShopName int 商店名称&
---@field ShopType int 商店类型
