---@class cfg.ShopMall  excel名称:ShopMall.xlsx
---@field ID int 唯一ID
---@field IsShow int 模块显示
---@field MoneyID cfg.s3int[] 展示货币
---@field Name int 模块名称&
---@field Sort int 排序id
---@field Type int 关联内容
