---@class cfg.SkillBulletConfig  excel名称:BattleSkill.xlsx
---@field AccelerateSpeed Fix 加速度
---@field DamageBoxIDs int[] 技能伤害包围盒编号
---@field FxID int 子弹特效
---@field HitType int 命中类型
---@field HitterID int HitterID
---@field ID int 子弹编号
---@field LifeTime Fix 生命周期
---@field Name string #备注
---@field Offset FVector3 起始位置偏移
---@field Speed Fix 速度
---@field SuspendTime Fix 悬停时间
---@field TemplateArg undefined lua 贝塞尔曲线参数
---@field Type int 子弹类型
