---@class cfg.SkillFashionConfig  excel名称:BattleSkill.xlsx
---@field FashionID int *时装编号
---@field FashionName string ##时装名称
---@field Role string ##归属角色
---@field SkillID int *技能编号
---@field SkillName string ##技能名称
---@field TemplateArg undefined lua 状态机模板参数
---@field Timeline string 技能Timeline
