---@class cfg.SkillTypeConfig  excel名称:BattleSkill.xlsx
---@field BelongTo int 所属描述&
---@field ID int 流水号
---@field InitLevel int 初始等级
---@field LevelMax cfg.s2int[] 技能等级上限
---@field NeedGold int[] 技能升级消耗金币
---@field NeedItem cfg.s3int[] 技能升级消耗道具
---@field PlusForce int[] 附加战力
---@field SkillType int ##技能类型文本&
---@field TYPE string ##技能分类
