---@class cfg.SkillDamageConfig  excel名称:BattleHurt.xlsx
---@field BasicDamage Fix 基础伤害
---@field ConditionParam cfg.s2int ##判定条件（1-BUFFID）
---@field ConditionValue Fix ##判定条件下的值
---@field DamageRatio Fix 伤害系数
---@field DamageType int 伤害类型
---@field DemoTag Fix ##DEMO数值专用
---@field ID int 伤害ID
---@field Name string #备注
---@field ShieldReduce Fix 对怪物护盾伤害
