---@class cfg.SongList  excel名称:CompanySong.xlsx
---@field Author string 作者名称
---@field Des string ##备注
---@field ExclusiveType int 男主专属
---@field ID int 唯一ID
---@field Image string 歌曲图集
---@field PlayTime int 歌曲播放最小时长
---@field SongName string 歌曲名称
---@field StateName string 资源名
