---@class cfg.SoulTrialBuff  excel名称:SoulTrial.xlsx
---@field BuffDesc string[] Buff等级效果
---@field BuffID int BuffID
---@field BuffLevel cfg.s3int[] Buff等级
---@field Desc int Buff描述&
---@field ID int 唯一ID
---@field RoleID int 角色ID
