---@class cfg.SoulTrial  excel名称:SoulTrial.xlsx
---@field Floor int 层数
---@field FloorName int 层数&
---@field ID int 唯一ID
---@field LockStageType string 未解锁关卡模型
---@field MissionID int[] 关卡ID
---@field Reward cfg.s3int[] 每层奖励
---@field RoleID int 角色ID
---@field SpecialReward cfg.s3int[] 特殊奖励
---@field StageType string 关卡模型
