---@class cfg.SpecialDateEntry  excel名称:SpecialDate.xlsx
---@field Bg string 约会大背景
---@field BgDescription int 约会背景信息&
---@field Cost cfg.s3int[] 约会消耗
---@field DateName int 约会主题名称&
---@field DatePlace int 约会地点描述1&
---@field DatePlace2 int 约会地点描述2&
---@field DatePlace3 int 约会地点描述3&
---@field DateType int 约会类型
---@field DefaultEnding int 默认结局
---@field Drama int 关联剧本ID
---@field ID int 唯一ID
---@field Image string 约会小图名
---@field IsOpen int 当前版本是否开放0 不开放1 开放
---@field ManType int 男主ID
---@field OpenCondition int 约会开启条件
---@field RealRewardDrop string 心动指数对应奖励
