---@class cfg.Stamina  excel名称:Stamina.xlsx
---@field ConditionID int 对应ConditionID
---@field FromTime int 体力属于时段
---@field ID int 唯一ID
---@field ResignCost cfg.s3int[] 补签消耗
---@field RewardItem cfg.s3int[] 奖励道具
---@field SpEventID int 对应特殊事件ID
