---@class cfg.StorySeries  excel名称:StorySeries.xlsx
---@field Content int[] 系列内容
---@field ID int 唯一ID
---@field LovePointLevel int 牵绊度等级
---@field Name int 系列名称&
---@field Reward cfg.s3int[] 收集奖励
---@field RoleID int 关联男主
---@field Sort int 排序
---@field StorySummary int 故事简介&
