---@class cfg.StorySeriesType  excel名称:StorySeries.xlsx
---@field ConstString string 类型名
---@field FinishColor string 已完成的颜色
---@field GetColor string 获得未完成的颜色
---@field ID int 类型ID
---@field Image string 图标
---@field Name int 客户端显示类别&
---@field NotGetColor string 未获得的颜色
---@field Tips string #策划备注
