---@class cfg.SubModule  excel名称:Module.xlsx
---@field ID int 唯一ID
---@field KeyArray int[] 参数数组
---@field ModuleID int 归属模块
---@field Remark int 策划备注#
---@field SubType int 功能细分
---@field Type int 功能类型
