---@class cfg.SundryConfig  excel名称:SundryConfig.xlsx
---@field ConstString string Key
---@field ConstType string 枚举数据类型
---@field Des string ##描述（仅策划看）
---@field ID int 唯一Index
---@field SourceSystem string ##所属系统仅策划看）
---@field Value string 内容
