---@class cfg.SystemSettingType  excel名称:SystemSettingType.xlsx
---@field ConstString string 常量
---@field Default int 默认值
---@field Desc string ##功能名称
---@field Id int 系统枚举id
---@field Max int 最大值
---@field Min int 最小值
