---@class cfg.SystemMail  excel名称:SystemMail.xlsx
---@field Id int 系统ID
---@field MailTitle int 邮件标题&
---@field Miss int 邮件称呼&
---@field PDTime int 有效期时长
---@field Reward cfg.s3int[] 奖励
---@field SendCondition int 邮件发送条件枚举
---@field Sign int 邮件署名&
---@field Text int 邮件正文&
