---@class cfg.SystemPushInfo  excel名称:SystemPushInfo.xlsx
---@field ChooseRemove int 从此主题换成默认反馈&
---@field ChooseReply int 换上气泡时的反馈&
---@field ConditionCheck int[] 解锁条件
---@field ItemSouce int 获得途径
---@field Priority int 优先级（数字大的在前）
---@field PushID int 推送池id
---@field PushName int &推送池名字
---@field RoleType int 角色类型
