---@class cfg.Title  excel名称:Title.xlsx
---@field Color string[] 底图字色
---@field Description int 称号获取方式&
---@field ID int 唯一ID
---@field Name int 称号名称&
---@field Order int 显示顺序
---@field Resource string 底图显示
---@field Role int 所属角色
---@field Show int 未获得时是否展示
---@field Type int 称号属性
