---@class cfg.TowerMonster  excel名称:ClimbTower.xlsx
---@field Attack int 怪物攻击力
---@field CritHurtAdd int 怪物暴击伤害
---@field CritVal int 怪物暴击值
---@field Defence int 怪物防御力
---@field Difficulty int ##难度
---@field ID int 唯一ID
---@field MaxHP int 怪物血量
---@field MaxPower int 战力上限
---@field MinPower int 战力下限
