---@class cfg.TowerFloor  excel名称:ClimbTower.xlsx
---@field ClearAward cfg.s2int[] 通层奖励
---@field ID int 唯一ID
---@field LevelAward cfg.s2int[] 重置奖励废弃
---@field LevelList int[] 起始关卡
---@field Name int 名称&
