---@class cfg.TowerAchievementAward  excel名称:ClimbTower.xlsx
---@field Condition int 成就条件
---@field GroupID int 组ID
---@field ID int 唯一ID
---@field Name int 标题&
---@field Order int 排序值
---@field Reward cfg.s2int[] 奖励
---@field RewardForShow cfg.s3int[] 成就奖励显示
