---@class cfg.TowerGlobalChoice  excel名称:ClimbTower.xlsx
---@field EffectTips int 跳出提示&
---@field ID int 唯一ID
---@field Mark int 策划备注#
---@field Parameter1 int 参数1
---@field Parameter2 int 参数2
---@field Parameter3 int 参数3
---@field Type int 类型
