---@class cfg.TowerDifficulty  excel名称:ClimbTower.xlsx
---@field Attack int 怪物攻击力千分比
---@field ClearAward cfg.s2int[] Boss奖励
---@field CritHurtAdd int 怪物暴击伤害千分比
---@field CritVal int 怪物暴击值千分比
---@field Defence int 怪物防御力千分比
---@field Description int 描述&
---@field ID int 唯一ID
---@field MaxHP int 怪物血量千分比
---@field Name int 名称&
