---@class cfg.TowerDrama  excel名称:ClimbTower.xlsx
---@field DifficultyConversation string 难度选择剧情
---@field FirstConversation int 初始进入玩法播放剧情
---@field FloorID int 关联Floor
---@field FloorToConversation cfg.s2int[] 高度与对话关联
---@field ID int 唯一ID
---@field Mark int 策划备注#
---@field PreID int 前置剧情
---@field Priority int 优先级
