---@class cfg.TriggerConfig  excel名称:BattleTrigger.xlsx
---@field CD Fix 冷却时间
---@field Count int 触发次数
---@field Filename string 触发器文件
---@field ID int 触发器编号
---@field Name string 触发器名称
---@field TemplateArg undefined lua 触发参数
