---@class cfg.UFOCatcherTotalDollItem  excel名称:UFOCatcher.xlsx
---@field Des string ##策划用
---@field Doll string ##策划用
---@field DollID int 娃娃ID
---@field GroupID int 组ID
---@field Index int 唯一Key
---@field Man string ##策划用
---@field Quality string ##策划用
