---@class cfg.UFOCatcherTotalDollGroup  excel名称:UFOCatcher.xlsx
---@field Bg string 背景图
---@field DecText int &装饰英文
---@field Des string ##备注
---@field DifficultGroupID int[] 所属DifficultGroup
---@field GroupID int 奖池ID
---@field Title int &标题
