---@class cfg.UIControl  excel名称:MusicFunctionControl.xlsx
---@field CheckBll string 检查挂载脚本函数
---@field Des string ##功能注释
---@field FunctionID int 功能ID
---@field MainUIBGM int 是否继承主界面音乐
---@field SPFunction int 功能界面判定
---@field StringKey string 所属功能的ViewTag
