---@class cfg.Vibration  excel名称:Vibration.xlsx
---@field Amplitude int 震动强度
---@field Des1 string ##模式名称
---@field Des2 string ##震动方式说明
---@field Frequency float 单次震动频率
---@field GroupFrequency float 多次震动间隔
---@field GroupTime int 总震动次数
---@field ID int 震动模式ID
---@field Time int 单次震动次数
