---@class cfg.WatchInterface  excel名称:Watch.xlsx
---@field Date string 日期
---@field ID int 初始界面ID
---@field Temperature int ##温度
---@field Time string ##时间
---@field Weather string ##天气
---@field Week string 星期
