---@class cfg.WorldNpcInfo  excel名称:WorldInfoNPC.xlsx
---@field Age int 年龄&
---@field ID int 唯一ID
---@field Icon string NPC小头像
---@field Image string NPC半身像
---@field Name int NPC名称&
---@field Occupation int 职业&
---@field Sort int 排序
---@field WorkPlace int 就职地点&
