---@class cfg.WorldInfoHistory  excel名称:WorldInfoHistory.xlsx
---@field Date int 日期&
---@field ID int 唯一ID
---@field Name int 词条名称&
---@field Sort int 排序ID
---@field Time int 年份
---@field TimeType int 类型
