--- Generated by AutoGen
---
---@class MsgCmd_SetAsmrPlayModeReply
local MsgCmd_SetAsmrPlayModeReply = class("MsgCmd_SetAsmrPlayModeReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.SetAsmrPlayModeReply
function MsgCmd_SetAsmrPlayModeReply:Execute(reply, sendData)
    BllMgr.GetASMRBLL():UpdatePlayMode(sendData)
end

return MsgCmd_SetAsmrPlayModeReply
