--- 本脚本由 CommandFileGenerator 导出，请勿手动修改!!!

return {
    [Miao.Command.AddMiaoTurnReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.AddMiaoTurnReply',
    [Miao.Command.Debug.AddMiaoTurnReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.AddMiaoTurnReply',
    [Miao.Command.GetMiaoDataReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.GetMiaoDataReply',
    [Miao.Command.Debug.GetMiaoDataReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.GetMiaoDataReply',
    [Miao.Command.GetMiaoRewardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.GetMiaoRewardReply',
    [Miao.Command.Debug.GetMiaoRewardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.GetMiaoRewardReply',
    [Miao.Command.GiveUpMiaoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.GiveUpMiaoReply',
    [Miao.Command.Debug.GiveUpMiaoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.GiveUpMiaoReply',
    [Miao.Command.InitMiaoHandReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.InitMiaoHandReply',
    [Miao.Command.Debug.InitMiaoHandReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.InitMiaoHandReply',
    [Miao.Command.MiaoPlayFuncCardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoPlayFuncCardReply',
    [Miao.Command.Debug.MiaoPlayFuncCardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoPlayFuncCardReply',
    [Miao.Command.MiaoSPExchangeHandReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPExchangeHandReply',
    [Miao.Command.Debug.MiaoSPExchangeHandReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPExchangeHandReply',
    [Miao.Command.MiaoSPExchangeHandUndoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPExchangeHandUndoReply',
    [Miao.Command.Debug.MiaoSPExchangeHandUndoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPExchangeHandUndoReply',
    [Miao.Command.MiaoSPReplaceReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPReplaceReply',
    [Miao.Command.Debug.MiaoSPReplaceReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPReplaceReply',
    [Miao.Command.MiaoSPRobGetCardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPRobGetCardReply',
    [Miao.Command.Debug.MiaoSPRobGetCardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPRobGetCardReply',
    [Miao.Command.MiaoSPRobReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPRobReply',
    [Miao.Command.Debug.MiaoSPRobReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPRobReply',
    [Miao.Command.MiaoSPStealReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPStealReply',
    [Miao.Command.Debug.MiaoSPStealReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPStealReply',
    [Miao.Command.MiaoSPUndoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.MiaoSPUndoReply',
    [Miao.Command.Debug.MiaoSPUndoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.MiaoSPUndoReply',
    [Miao.Command.PlayMiaoCardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.PlayMiaoCardReply',
    [Miao.Command.Debug.PlayMiaoCardReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.PlayMiaoCardReply',
    [Miao.Command.ReduceMiaoCountReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.ReduceMiaoCountReply',
    [Miao.Command.Debug.ReduceMiaoCountReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.ReduceMiaoCountReply',
    [Miao.Command.RollMiaoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.RollMiaoReply',
    [Miao.Command.Debug.RollMiaoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.RollMiaoReply',
    [Miao.Command.StartAITestReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.StartAITestReply',
    [Miao.Command.Debug.StartAITestReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.StartAITestReply',
    [Miao.Command.UpdateMiaoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.UpdateMiaoReply',
    [Miao.Command.Debug.UpdateMiaoReply] = 'Runtime.System.X3Game.Modules.GamePlayLogic.GamePlay.Miao.Command.Debug.UpdateMiaoReply',
}