---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liyan.
--- DateTime: 2023/12/26 17:28
---

local UIPaintingConst = {}

UIPaintingConst.DrawType =
{
    COLOR   = 1 ,       -- 纯色线
    TEXTURE = 1 << 1,   -- 贴图笔触
    VFX     = 1 << 2,   -- VFX
}

return UIPaintingConst