--- Generated by AutoGen
---
---@type MainHome.MainHomeConst
local MainHomeConst = require("Runtime.System.X3Game.Modules.MainHome.Data.MainHomeConst")
---@class MsgCmd_GetAccompanyDataReply
local MsgCmd_GetAccompanyDataReply = class("MsgCmd_GetAccompanyDataReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetAccompanyDataReply
function MsgCmd_GetAccompanyDataReply:Execute(reply)
    ---Insert Your Code Here!
    Debug.LogFormat("MsgCmd_GetAccompanyDataReply")
    for roleId, accompanyData in pairs(reply.Data.RoleMap) do
        SelfProxyFactory.GetAccompanyProxy():AddOrUpdateRoleData(roleId ,
                {
                    RoleID = roleId ,
                    Type = accompanyData.Type ,
                    StartTime = accompanyData.StartTime,
                    ExpectDuration = accompanyData.ExpectDuration,
                    AccumulateTime = accompanyData.AccumulateTime,
                    OfflineDuration = accompanyData.OfflineDuration,
                })
    end
    EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_ACCOMPANY_GET_DATA_BACK , reply)
end

return MsgCmd_GetAccompanyDataReply
