--- Generated by AutoGen
---
---@class MsgCmd_BindPhoneOrEmailReply
local MsgCmd_BindPhoneOrEmailReply = class("MsgCmd_BindPhoneOrEmailReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.BindPhoneOrEmailReply
function MsgCmd_BindPhoneOrEmailReply:Execute(reply)
    ---Insert Your Code Here!
    local rewards = reply.Rewards or {}
    UICommonUtil.ShowRewardPopTips(rewards, 2, false)
end

return MsgCmd_BindPhoneOrEmailReply
