---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2020/12/31 12:31
---

local AIAction = require("Runtime.Plugins.AIDesigner.Base.AITask").AIAction

---两值相乘，并返回至storeResult
---@class SystemAI.FloatMultiplication:AIAction
---@field floatValue AIVar|Float
---@field multiplyValue AIVar|Float
---@field storeResult AIVar|Float
local FloatMultiplication = AIUtil.class("FloatMultiplication", AIAction)

function FloatMultiplication:OnUpdate()
    self.storeResult:SetValue(self.floatValue:GetValue() * self.multiplyValue:GetValue())
    return AITaskState.Success
end

return FloatMultiplication