---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2020/11/27 17:26
---

local AIAction = require("Runtime.Plugins.AIDesigner.Base.AITask").AIAction

---返回成功
---@class SystemAI.ReturnSuccess:AIAction
local ReturnSuccess = AIUtil.class("ReturnFailure", AIAction)

function ReturnSuccess:OnUpdate()
    return AITaskState.Success
end

return ReturnSuccess