---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengzi.
--- DateTime: 2023/6/21 16:18
---

---@class DCStateDefine
local DCStateDefine = {}


DCStateDefine.States = {
    StaticCard = "StaticCardState",
    Loading = "LoadingState",
    Playing = "PlayingState",
}


DCStateDefine.PlayStatus = {
    Playing = 1,
    Pause = 2,
    Stop = 3,
}

return DCStateDefine