---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2020/11/26 16:49
---

local AIComposite = require("Runtime.Plugins.AIDesigner.Base.AITask").AIComposite

---顺序执行子节点，当遇到子节点返回成功时，则中断后续子节点执行；
---全部节点返回失败，该节点就返回失败
---IconName:SelectorIcon.png
---@class AI.Selector:AIComposite
local Selector = AIUtil.class("Selector", AIComposite)

function Selector:OnUpdate()
    for _, child in ipairs(self.children) do
        if not child.disabled then
            if child.state == AITaskState.Running or child.state == AITaskState.BlockingUp then
                return AITaskState.BlockingUp
            elseif child.state == AITaskState.Success then
                return AITaskState.Success
            end
        end
    end
    return AITaskState.Failure
end

function Selector:CanRunChild(index)
    for i = 1, index - 1 do
        local child = self.children[i]
        if not child.disabled and (child.state == AITaskState.Success or child.state == AITaskState.Running or child.state == AITaskState.BlockingUp) then
            return false
        end
    end
    return true
end

return Selector
