---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiantao.
--- DateTime: 2023/4/6 11:29
---
---@class EnterProStageAction
local EnterProStageAction = class("EnterProStageAction", require("Runtime.System.X3Game.Modules.EnterGame.Action.BaseEnterGameAction"))
function EnterProStageAction:CheckCondition()
    ---检测是否是序章
    if BllMgr.GetChapterAndStageBLL():IsPrologueChapter() then
        return true
    end
    return false
end

function EnterProStageAction:EnterAction()
    if self.callBack then
        self.callBack()
    end
    self:CheckPlayVideo()
end

function EnterProStageAction:CheckNeedLoading()
    local videoName = LuaCfgMgr.Get("SundryConfig", X3_CFG_CONST.CGVIDEONAME)
    local firstStageId = LuaCfgMgr.Get("SundryConfig", X3_CFG_CONST.PROLOGUESTART)
    return (not BllMgr.GetChapterAndStageBLL():StageIsUnLockById(firstStageId)) and (not  string.isnilorempty(videoName))
end

function EnterProStageAction:CheckPlayVideo()
    ---防止中途修改GM
    if not BllMgr.GetChapterAndStageBLL():IsAutoNextStage() then
        GameStateMgr.Switch(GameState.MainHome)
        return
    end
    --视频加密需求 暂时屏蔽pv 功能
    local firstStageId = LuaCfgMgr.Get("SundryConfig", X3_CFG_CONST.PROLOGUESTART)
    if not BllMgr.GetChapterAndStageBLL():StageIsUnLockById(firstStageId) then
        local videoName = LuaCfgMgr.Get("SundryConfig", X3_CFG_CONST.CGVIDEONAME)
        if not string.isnilorempty(videoName) then
            UICommonUtil.BlackScreenIn(function()
                UICommonUtil.SetLoadingEnable(GameConst.LoadingType.Common, false)
            end)
            local stageCfg = LuaCfgMgr.Get("CommonStageEntry", firstStageId)
            if stageCfg.DramaFront ~= 0 then
                PreloadBatchMgr.PreloadAsync(PreloadBatchType.Dialogue, stageCfg.DramaFront,
                        function()
                            UIMgr.Open(UIConf.CommonVideoShowWnd, videoName, function()
                                BllMgr.GetChapterAndStageBLL():StartProStage(false)
                            end, GameConst.VideoSourceType.URL,false, nil, true)
                            UICommonUtil.CloseScreen()
                        end)
            end
        else
            BllMgr.GetChapterAndStageBLL():StartProStage()
            UICommonUtil.SetLoadingEnable(GameConst.LoadingType.Common, false)
        end
    else
        BllMgr.GetChapterAndStageBLL():StartProStage()
        UICommonUtil.SetLoadingEnable(GameConst.LoadingType.Common, false)
    end
end

return  EnterProStageAction