--- Generated by AutoGen
---
---@class MsgCmd_SCoreEquipReply
local MsgCmd_SCoreEquipReply = class("MsgCmd_SCoreEquipReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param Data pbcmessage.SCoreEquipReply
function MsgCmd_SCoreEquipReply:Execute(Data)
	EventMgr.Dispatch(ScoreConst.Event.SCORE_EQUIP_REPLY)
end

return MsgCmd_SCoreEquipReply
