--- Generated by AutoGen
---
---@class MsgCmd_GetSCoreInfoReply
local MsgCmd_GetSCoreInfoReply = class("MsgCmd_GetSCoreInfoReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetSCoreInfoReply
function MsgCmd_GetSCoreInfoReply:Execute(reply)
    ---Insert Your Code Here!
    SelfProxyFactory.GetScoreProxy():OnGetSCoreInfoReply(reply)
end

return MsgCmd_GetSCoreInfoReply
