---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2022/6/1 23:48
--- 显示猫相关表现
local CatCardConst = require("Runtime.System.X3Game.Modules.CatCard.Data.CatCardConst")
---@type CatCard.BaseActionData
local BaseActionData = require(CatCardConst.BASE_ACTION_DATA_PATH)
---@class CatCard.CatShowActionData:CatCard.BaseActionData
local CatShowActionData = class("CatShowActionData",BaseActionData)

function CatShowActionData:ctor()
    BaseActionData.ctor(self)
    ---@type int
    self.slotIdx = 0
end

--region Set
---@param idx int
function CatShowActionData:SetSlotIdx(idx)
    self.slotIdx = idx
end
--endregion

--region Get
---@return int
function CatShowActionData:GetSlotIdx()
    return self.slotIdx
end
--endregion

---@param slotIdx int
function CatShowActionData:Set(slotIdx)
    self:SetSlotIdx(slotIdx)
end

return CatShowActionData