--- Generated by AutoGen
---
---@class MsgCmd_GMPayDeliverReply
local MsgCmd_GMPayDeliverReply = class("MsgCmd_GMPayDeliverReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GMPayDeliverReply
function MsgCmd_GMPayDeliverReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GMPayDeliverReply
