---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2022/4/26 14:16
--- 主界面本地状态刷新
---@type MainHome.MainHomeConst
local MainHomeConst = require("Runtime.System.X3Game.Modules.MainHome.Data.MainHomeConst")
---@type MainHomeBaseCtrl
local BaseCtrl = require(MainHomeConst.BASE_CTRL)
---@class MainHomeLocalStateCtrl:MainHomeBaseCtrl
local MainHomeLocalStateCtrl = class("MainHomeLocalStateCtrl", BaseCtrl)

function MainHomeLocalStateCtrl:ctor()
    BaseCtrl.ctor(self)
    self.stateId = 0
    self.realStateId = 0
end

---刷新表现
function MainHomeLocalStateCtrl:RefreshShow()
    EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_SET_PPV_FEATURE_ENABLE,self.bll:IsHandlerRunning(MainHomeConst.HandlerType.ActorFront))
    EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_REFRESH_CHARACTER_LIGHT)
end

---刷新数据变更
function MainHomeLocalStateCtrl:RefreshData()
    self.bll:SetHandlerRunning(MainHomeConst.HandlerType.DialogueChanged,false)
    self.bll:SetHandlerRunning(MainHomeConst.HandlerType.ActorChanged,false)
    EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_CHECK_ACTOR_POS_TYPE)
end

function MainHomeLocalStateCtrl:OnEventLocalStateChanged(st)
    if type(st) == "table" then
        st = tonumber(st.params and st.params[1] or 0)
    end
    if not st or st==0 then
        return
    end
    self.stateId = st
    local data = self.bll:GetData()
    self.realStateId = data:GetStateId()
    data:RefreshState(self.stateId,true)
    self:RefreshData()
    self:RefreshShow()
    data:RefreshState(self.realStateId)
end

function MainHomeLocalStateCtrl:OnEventServerStateChanged()
    self.stateId = 0
    self.realStateId = 0
end


function MainHomeLocalStateCtrl:Enter()
    BaseCtrl.Enter(self)
    self:RegisterEvent()
end

function MainHomeLocalStateCtrl:Exit()
    BaseCtrl.Exit(self)
    self.stateId = 0
    self:UnRegisterEvent()
end


---还原假状态
function MainHomeLocalStateCtrl:OnEventRestoreLocalState()
    if self.stateId>0 and self.realStateId>0 then
        if self.bll:IsDebugMode() then
            Debug.LogFormat("[MainHome] 恢复假状态fakeState=[%s]-->realState=[%s]",self.stateId,self.realStateId)
        end
        self.realStateId = self.bll:GetData():GetServerStateId()
        EventMgr.Dispatch(MainHomeConst.Event.MAIN_HOME_CHANGE_ACTOR_STATE,self.realStateId)
        self.stateId = 0
        self.realStateId = 0
    end
end

function MainHomeLocalStateCtrl:RegisterEvent()
    EventMgr.AddListener(MainHomeConst.Event.MAIN_HOME_CHANGE_ACTOR_STATE,self.OnEventLocalStateChanged,self)
    EventMgr.AddListener(MainHomeConst.Event.MAIN_HOME_AI_STATE_CHANGED,self.OnEventServerStateChanged,self)
    EventMgr.AddListener(MainHomeConst.Event.MAIN_HOME_RESTORE_LOCAL_STATE,self.OnEventRestoreLocalState,self)
end
return MainHomeLocalStateCtrl