---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanbo.
--- DateTime: 2021/12/28 14:37
---
---@class MsgCmd_CircleChessStartActionReply
local MsgCmd_CircleChessStartActionReply = class("MsgCmd_CircleChessStartActionReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param msg any
function MsgCmd_CircleChessStartActionReply:Execute(msg, ...)
    SelfProxyFactory.GetCircleChessProxy():CircleChessStartActionReply(msg)
    EventMgr.Dispatch(CircleChessDefine.Event.SERVER_CC_START_ACTION_REPLY, msg)
end

return MsgCmd_CircleChessStartActionReply