---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanbo.
--- DateTime: 2021/12/28 14:37
---
---@class MsgCmd_CircleChessRollMoveReply
local MsgCmd_CircleChessRollMoveReply = class("MsgCmd_CircleChessRollMoveReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param msg any
function MsgCmd_CircleChessRollMoveReply:Execute(msg, ...)
    SelfProxyFactory.GetCircleChessProxy():CircleChessRollMoveReply(msg)
    EventMgr.Dispatch(CircleChessDefine.Event.SERVER_CC_ROLL_MOVE_REPLY, msg)
end

return MsgCmd_CircleChessRollMoveReply