---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doudou.
--- DateTime: 2023/7/10 17:01
---@class JumpLoopChecker
local JumpLoopChecker = class("SpecialUILoopChecker")

function JumpLoopChecker:ctor()
    self._ViewRecordMap = nil
end

function JumpLoopChecker:Init()
    ---@type table<string, string[]>
    self._ViewRecordMap = {}
    EventMgr.AddListener(Const.Event.GLOBAL_UIVIEW_ON_OPEN, self._OnWndOpen, self)
    EventMgr.AddListener(Const.Event.GLOBAL_UIVIEW_ON_CLOSE, self._OnWndClose, self)
end

function JumpLoopChecker:TryStartRecord(viewTag)
    if UIMgr.IsOpened(viewTag) then
        if self._ViewRecordMap[viewTag] == nil then
            self._ViewRecordMap[viewTag] = {}
        end
    end
end

function JumpLoopChecker:StopRecord(viewTag)
    self._ViewRecordMap[viewTag] = nil
end

function JumpLoopChecker:CloseRecordWnd(viewTag)
    local record = self._ViewRecordMap[viewTag]
    self._ViewRecordMap[viewTag] = nil
    if record then
        for i = #record, 1, -1 do
            UIMgr.Close(record[i], false)
        end
    end
end

function JumpLoopChecker:_OnWndOpen(data)
    local viewTag = data.ViewTag
    for tag, record in pairs(self._ViewRecordMap) do
        if tag == viewTag then
            self._ViewRecordMap[tag] = nil
            Debug.LogWarningFormat("%s is Open Twice", viewTag)
        else
            table.insert(record, viewTag)
        end
    end
end

function JumpLoopChecker:_OnWndClose(data)
    local viewTag = data.ViewTag
    for tag, record in pairs(self._ViewRecordMap) do
        if tag == viewTag then
            self._ViewRecordMap[tag] = nil
        else
            local removeIdx
            for i = #record, 1, -1 do
                if record[i] == viewTag then
                    removeIdx = i
                    break
                end
            end
            if removeIdx then
                table.remove(record, removeIdx)
            end

            if #record == 0 then
                self._ViewRecordMap[viewTag] = nil
            end
        end
    end
end

function JumpLoopChecker:Clear()
    EventMgr.RemoveListenerByTarget(self)
    self._ViewRecordMap = nil
end

return JumpLoopChecker