--- Generated by AutoGen
---
---@class MsgCmd_GetSomeShopDataReply
local MsgCmd_GetSomeShopDataReply = class("MsgCmd_GetSomeShopDataReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetSomeShopDataReply
function MsgCmd_GetSomeShopDataReply:Execute(reply)
    ---Insert Your Code Here!
    SelfProxyFactory.GetShopProxy():OnGetSomeShopDataCallBack(reply)
end

return MsgCmd_GetSomeShopDataReply
