---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fusu.
--- DateTime: 2023/4/6 14:07
---

local AccompanyConst = require("Runtime.System.X3Game.Modules.Accompany.Data.AccompanyConst")
local AccompanyBaseAction = require("Runtime.System.X3Game.Modules.Accompany.Action.AccompanyBaseAction")

---@class AccompanyPlayDialogAction : AccompanyBaseAction
local AccompanyPlayDialogAction = class("AccompanyPlayDialogAction" , AccompanyBaseAction)

function AccompanyPlayDialogAction:Init(actionParam)
    ---剧情配置名
    ---@type string
    self._dataKey = actionParam[1]
    ---剧情配置名
    ---@type string
    self._dialogueIdType = actionParam[2]
    ---剧情pipeLineKey
    ---@type string
    self._pipeLineKey = actionParam[3]
end

function AccompanyPlayDialogAction:OnConditionPass()
    self._conversationName = self.accMgr.accBll:GetConfigDataByKey(self._dataKey)
    self._dialogueId =  self.accMgr.accBll:GetDialogueId(self._dialogueIdType)
    
    ---剧情不存在直接完成
    if string.isnilorempty(self._conversationName) then
        self:OnFinish()
        return
    end
    
    ---@type AccompanyDialogueCtrl
    local dialogueCtrl = self.accMgr:GetCtrl(AccompanyConst.CtrlType.DialogueCtrl)
    dialogueCtrl:StartDialogueByName(self._conversationName, self._dialogueIdType , self._pipeLineKey, function()
        self:OnFinish()
    end)
end

function AccompanyPlayDialogAction:OnFinish()
    AccompanyPlayDialogAction.super.OnFinish(self)
    EventMgr.Dispatch(AccompanyConst.Event.ON_ACCOMPANY_DIALOGUE_FINISH, self._conversationName)
end

function AccompanyPlayDialogAction:OnDestroy()
    AccompanyPlayDialogAction.super.OnDestroy(self)
    ---@type AccompanyDialogueCtrl
    local dialogueCtrl = self.accMgr:GetCtrl(AccompanyConst.CtrlType.DialogueCtrl)
    dialogueCtrl:StopDialogueByPipelineKey(self._pipeLineKey)
end

return AccompanyPlayDialogAction