---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by deling.
--- DateTime: 2023/9/14 17:35
---

---@type PureLogic.IComponent
local IComponent = require("PureLogic.Common.Component.IComponent")
---@class PureLogic.PhotoComp:PureLogic.IComponent
---@field entity PureLogic.ClientEntity
local PhotoComp = class("PhotoComp", IComponent)

---初始化
function PhotoComp:OnInit()
end

---注销
function PhotoComp:OnDispose()
end

---暂停
function PhotoComp:OnPause()
end

---继续
function PhotoComp:OnResume()
end

return PhotoComp