--- Generated by AutoGen
---
---@class MsgCmd_ClearFrameNewReply
local MsgCmd_ClearFrameNewReply = class("MsgCmd_ClearFrameNewReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.ClearFrameNewReply
---@param request pbcmessage.ClearFrameNewRequest
function MsgCmd_ClearFrameNewReply:Execute(reply, request)
    ---Insert Your Code Here!
    SelfProxyFactory.GetPlayerInfoProxy():FrameClearRed(request.FrameList)
end

return MsgCmd_ClearFrameNewReply
