--- Generated by AutoGen
---
---@class MsgCmd_SetFrameIDReply
local MsgCmd_SetFrameIDReply = class("MsgCmd_SetFrameIDReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.SetFrameIDReply
---@param request pbcmessage.SetFrameIDRequest
function MsgCmd_SetFrameIDReply:Execute(reply, request)
    ---Insert Your Code Here!
    SelfProxyFactory.GetPlayerInfoProxy():FrameChange(request.FrameID)
end

return MsgCmd_SetFrameIDReply
