--- Generated by AutoGen
---
---@class MsgCmd_GiveUpBlockTowerReply
local MsgCmd_GiveUpBlockTowerReply = class("MsgCmd_GiveUpBlockTowerReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GiveUpBlockTowerReply
function MsgCmd_GiveUpBlockTowerReply:Execute(reply)

end

return MsgCmd_GiveUpBlockTowerReply
