--- Generated by AutoGen
---
---@class MsgCmd_CardMergeReply
local MsgCmd_CardMergeReply = class("MsgCmd_CardMergeReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param data pbcmessage.CardMergeReply
function MsgCmd_CardMergeReply:Execute(data,request)
	BllMgr.GetCardBLL():STC_CardComposeCallBack(request.Id)
end

return MsgCmd_CardMergeReply
