--- Generated by AutoGen
---
---@class MsgCmd_CardGetRewardReply
local MsgCmd_CardGetRewardReply = class("MsgCmd_CardGetRewardReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.CardGetRewardReply
function MsgCmd_CardGetRewardReply:Execute(reply)
    UICommonUtil.ShowRewardPopTips(reply.RewardList, 2)
end

return MsgCmd_CardGetRewardReply
