---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kan.
--- DateTime: 2022/2/10 10:47
--- 备忘录管理者

local Caretaker = class("Caretaker")

function Caretaker:ctor()
    self.curIndex = 0     --记录当前显示位置
    self.mementoList = {} --存储备忘录信息
end

---将备忘信息增加到备忘录中
function Caretaker:Add(memento)
    if self.curIndex ~= #self.mementoList then
        self:RemoveMemento()
    end

    table.insert(self.mementoList,memento)
    self.curIndex = #self.mementoList
end

function Caretaker:RemoveMemento()
    for i = #self.mementoList,self.curIndex + 1,-1 do --从后往前移除
        table.remove(self.mementoList,i)
    end
end

---设置当前位置标记
function Caretaker:SetIndex(index)
    self.curIndex = index
end

function Caretaker:Reset()
    self.curIndex = 0
    self.mementoList = {}
end

---获取当前标记
function Caretaker:GetIndex()
    return self.curIndex
end

---获取备忘录总数
function Caretaker:GetMementoCount()
    return #self.mementoList
end

---获取当前备忘信息
function Caretaker:GetMemento()
    return self.mementoList[self.curIndex]
end

function Caretaker:GetMementoByIndex(index)
    return self.mementoList[index]
end

return Caretaker

