--- Generated by AutoGen
---
---@class MsgCmd_CustomDataDeleteReply
local MsgCmd_CustomDataDeleteReply = class("MsgCmd_CustomDataDeleteReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.CustomDataDeleteReply
function MsgCmd_CustomDataDeleteReply:Execute(reply)
    ---Insert Your Code Here!
    BllMgr.GetPlayerServerPrefs():DataDeleteReply(reply)
end

return MsgCmd_CustomDataDeleteReply
