---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanbo.
--- DateTime: 2021/8/13 16:38
---
---@class TeamConst
local TeamConst = {}

TeamConst.TeamType = {
    ---设置阵型
    Setting = 0,
    ---主线阵型
    MainLineBattle = 1,
    ---迷惘之塔
    TowerBattle = 2,
    ---作战补给
    CombatSupplies = 3,
    ---羁绊提升
    FettersUpgrade = 4,
    ---羁绊突破
    FettersBreakout = 5,
    ---誓约特训
    PledgeSpecialTraining = 6,
    ---心灵试炼
    SoulTrial = 7,
    ---武器试炼
    WeaponTrial = 10,
    ---芯核副本
    GemCore = 11,
    ---Doll
    Doll = 12,
    ---SCoreTry
    SCoreTry = 13,
    ---HunterContest 猎人锦标赛
    HunterContest = 14,
}

TeamConst.Event = {
    TEAM_WND_REFRESH_SCORE = "TEAM_WND_REFRESH_SCORE",
    TEAM_WND_BOTTOM_ACTIVE = "TEAM_WND_BOTTOM_ACTIVE",
    TEAM_WND_LIMIT_MESSAGE = "TEAM_WND_LIMIT_MESSAGE",
    TEAM_WND_ON_SELECT_CELL = "TEAM_WND_ON_SELECT_CELL",
    TEAM_WND_WEAPON_CHANGE = "TEAM_WND_WEAPON_CHANGE",
    TEAM_WND_SCORE_CHANGE = "TEAM_WND_SCORE_CHANGE",
    TEAM_WND_PL_SUIT_CHANGE = "TEAM_WND_PL_SUIT_CHANGE",
    TEAM_WND_CHARACTER_LOADED_MY = "TEAM_WND_CHARACTER_LOADED_MY",
    TEAM_WND_CHARACTER_LOADED_OTHER = "TEAM_WND_CHARACTER_LOADED_OTHER",
    TEAM_WND_WEAPON_SURE = "TEAM_WND_WEAPON_SURE",
    TEAM_WND_SAVE_SCORE_ID_SUIT_ID = "TEAM_WND_SAVE_SCORE_ID_SUIT_ID",
    TEAM_WND_SAVE_SKIN = "TEAM_WND_SAVE_SKIN",
    TEAM_WND_SELECT_PL_FASHION_ID = "TEAM_WND_SELECT_PL_FASHION_ID",
    TEAM_WND_CHANGE_SCORE_ID_SUIT_ID = "TEAM_WND_CHANGE_SCORE_ID_SUIT_ID",
    ------
    TEAM_WND_SETFORMATION_NETREPLY = "TEAM_WND_SETFORMATION_NETREPLY",--同步设置玩法编队服务器数据
    TEAM_WND_SETPREFABFORMATION_NETREPLY = "TEAM_WND_SETPREFABFORMATION_NETREPLY",--同步设置预设编队服务器数据
    
    TEAM_WND_CHOOSESCORE_UPDATESTATE = "TEAM_WND_CHOOSESCORE_UPDATESTATE", --刷新显示score更改后的状态
    TEAM_WND_CHOOSEWEAPON_UPDATESTATE = "TEAM_WND_CHOOSEWEAPON_UPDATESTATE",--刷新显示weapon更改后的状态
    TEAM_WND_CHOOSEPLSUITID_UPDATESTATE = "TEAM_WND_CHOOSEPLSUITID_UPDATESTATE",--刷新显示PlSuitId更改后的状态
    
    TEAM_WND_CHOOSESCORE_CHANGEMODEL = "TEAM_WND_CHOOSESCORE_CHANGEMODEL", --刷新显示score更改后的状态
    TEAM_WND_CHOOSEWEAPON_CHANGEMODEL = "TEAM_WND_CHOOSEWEAPON_CHANGEMODEL",--刷新显示weapon更改后的状态
    TEAM_WND_CHOOSEPLSUITID_CHANGEMODEL = "TEAM_WND_CHOOSEPLSUITID_CHANGEMODEL",--刷新显示PlSuitId更改后的状态
    TEAM_WND_AUTOCHOOSE_CHANGEMODEL = "TEAM_WND_AUTOCHOOSE_CHANGEMODEL",--刷新显示所有都更改后的状态
    
    TEAM_WND_SET_CHANGECARDS = "TEAM_WND_SET_CHANGECARDS",--编队上阵思念卡设置后数据更改
    
    TEAM_WND_CARDSCHANGED = "TEAM_WND_CHANGECARDS",--编队思念卡数据更改
}

TeamConst.FormationType = 
{
    --玩法编队
    Formation = 1,
    --预设编队
    PreFabFormation = 2,
}

TeamConst.CardSlotNum = 6 --思念卡槽数量


TeamConst.ChooseType = 
{
    SCORE = 1,
    WEAPON = 2,
    FASHION = 3
}

---编队设置状态
TeamConst.FormationSetState = 
{
    SUCCESS = 1, --设置成功
    SUCCESS_CARDNOFULL = 2, --思念卡槽数量未满
    CARDSETERROR = 3,--思念卡牌设置错误
    SCORESETERROR = 4,--Score设置错误
    WEAPONSETERROR = 5,--武器设置错误
    PLSUITSETERROR = 6,--战斗装设置错误
}

---score使用状态类型
TeamConst.ScoreUseState = 
{
    CANUSE = 1, --可以使用
    NOUSE_STAGELIMIT = 2,--关卡限制不能使用
    NOUSE_ROLELIMIT = 3, -- 角色限制不能使用
    NOHAS = 4 --没有拥有
}


---score使用状态类型
TeamConst.WeaponUseState =
{
    CANUSE = 1, --可以使用
    NOUSE_STAGELIMIT = 2,--关卡限制大类不能使用
    NOUSE_STATELIMINTITEM = 3, -- 关卡限制不能使用单个武器
    NOUSE_ROLEEXCLUSIVE = 4 --角色专属
}

---score界面自动匹配类型
TeamConst.AudoChangeType = {
    None = 0,
    All = 1,
    Fashion = 2,
    Weapon = 3,
}

---动态加载cts外部组件路径---表里已改为全路径，代码中不应出现常量路径加载
TeamConst.X3ANIMATORPART_ASSET_PATH = "Assets/Build/Art/Drama/Performance/UIShow/DynamicPartAssets/%s.asset"

---选择的预设编队index
TeamConst.SelectPreFabFormationKey = "SELECTPREFABFORMATIONKEY"

---玩法编队设置的预设编队id
TeamConst.FormationChoosePreFabKey = "FORMATIONCHOOSEPREFABKEY"

return TeamConst