---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pc.
--- DateTime: 2020/8/28 19:40
---

---@type CatCardConst
local CatCardConst = require("Runtime.System.X3Game.Modules.CatCard.Data.CatCardConst")
local BaseState = require(CatCardConst.BASE_STATE_PATH)
local InitHandState = class("InitHandState",BaseState)

function InitHandState:Execute(is_special)
    ---@type CatCardBLL
    self.bll = self.bll
    --进入正式出牌阶段
    self:SetIsRunning(true)
    if is_special then
        self:ShowRealCards()
        ---@type CatCard.ChangeDialogueStateActionData
        local actionData = self.bll:GetActionData(CatCardConst.ActionType.ChangeDialogueState, CatCardConst.PlayerType.PLAYER, function ()
            self:DialogEnd()
        end)
        actionData:SetState(CatCardConst.DialogueState.InitHand)
        actionData:SetDialogueCtrlState(CatCardConst.DialogueCtrlState.Start)
        actionData:Begin()
    else
        self:SetNewCard()
        EventMgr.Dispatch(CatCardConst.Event.CAT_CARD_REFRESH_MODELS,CatCardConst.CardType.SLOT)
        self:CheckInitHandAction(function ()
            EventMgr.Dispatch(CatCardConst.Event.CAT_CARD_REFRESH_MODELS,CatCardConst.CardType.CARD)
            self:RotateCards(function ()
                self:OnInitHandEnd()
            end)
        end)
    end
end

function InitHandState:SetNewCard()
    for k,v in pairs(CatCardConst.PlayerType) do
        local data_list = self.bll:GetDataList(CatCardConst.CardType.CARD,v)
        local rotation_z = v == CatCardConst.PlayerType.PLAYER and CatCardConst.PLAYER_CARD_ROTATION_Z or 0
        for _,data in pairs(data_list) do
            data:SetIsNew(true)
            data:SetRotationZ(rotation_z)
        end
        PoolUtil.ReleaseTable(data_list)
    end
    
end

function InitHandState:OnInitHandEnd(...)
    self.bll:CheckAction(CatCardConst.SpecialType.INIT_HAND,true,nil,CatCardConst.MAX_INIT_CARD_COUNT,CatCardConst.PlayerType.ENEMY)
    self.bll:CheckAction(CatCardConst.SpecialType.INIT_HAND,true,nil,CatCardConst.MAX_INIT_CARD_COUNT,CatCardConst.PlayerType.PLAYER)
    EventMgr.Dispatch(CatCardConst.Event.CAT_CARD_CHECK_SPECIAL_STATE,...)
end

function InitHandState:RotateCards(callback)
    self.bll:CheckAction(CatCardConst.SpecialType.INIT_HAND,false,callback,CatCardConst.MAX_INIT_CARD_COUNT,CatCardConst.PlayerType.PLAYER,true)
end

function InitHandState:CheckInitHandAction(callback)
    local index = 2
    local is_finish = false
    local func = function()
        index = index -1
        if not is_finish and index<=0 then
            is_finish = true
            if callback then callback() end
        end
    end
    self.bll:CheckAction(CatCardConst.SpecialType.INIT_HAND,false,func,1,CatCardConst.PlayerType.ENEMY,false,true)
    self.bll:CheckAction(CatCardConst.SpecialType.INIT_HAND,false,func,1,CatCardConst.PlayerType.PLAYER,false,false)
end

function InitHandState:DialogEnd()
    self:SetIsRunning(true)
    self:SetStartView(true,function ()
        self:SetIsRunning(false)
        self:AddMiaoTurn()
    end)
end

function InitHandState:SetStartView(is_active,callback)
    EventMgr.Dispatch(CatCardConst.Event.CAT_CARD_SET_VIEW_ACTIVE,CatCardConst.ViewType.START,is_active,true,callback)
end

return InitHandState