--- Generated by AutoGen
---
---@class MsgCmd_MessageCollectStickerReply
local MsgCmd_MessageCollectStickerReply = class("MsgCmd_MessageCollectStickerReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.MessageCollectStickerReply
---@param request pbcmessage.MessageCollectStickerRequest
function MsgCmd_MessageCollectStickerReply:Execute(reply, request)
    ---Insert Your Code Here!
    BllMgr.GetPhoneMsgBLL():AddCustomEmoji(request.StickerID, false, true)
end

return MsgCmd_MessageCollectStickerReply
