---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaofang.
--- DateTime: 2023/1/7 11:37
local CatCardConst = require("Runtime.System.X3Game.Modules.CatCard.Data.CatCardConst")
---@type CatCard.BaseActionData
local BaseActionData = require(CatCardConst.BASE_ACTION_DATA_PATH)
---@class CatCard.StealEndActionData:CatCard.BaseActionData
local StealEndActionData = class("StealEndActionData",BaseActionData)

function StealEndActionData:ctor()

end

return StealEndActionData