--- Generated by AutoGen
---
---@class MsgCmd_GameGetPlayerRankReply
local MsgCmd_GameGetPlayerRankReply = class("MsgCmd_GameGetPlayerRankReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GameGetPlayerRankReply
function MsgCmd_GameGetPlayerRankReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GameGetPlayerRankReply
