--- Generated by AutoGen
---
---@class MsgCmd_SoulTrialGetBuffsReply
local MsgCmd_SoulTrialGetBuffsReply = class("MsgCmd_SoulTrialGetBuffsReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param data pbcmessage.SoulTrialGetBuffsReply
function MsgCmd_SoulTrialGetBuffsReply:Execute(data)
    SelfProxyFactory.GetSoulTrialProxy():SoulTrialGetBuffsReply(data.RoleBuffs)
    EventMgr.Dispatch(SoulTrialConst.Event.SERVER_ST_GET_BUFFS_REPLY, data)
end

return MsgCmd_SoulTrialGetBuffsReply
