--- Generated by AutoGen
---
---@class MsgCmd_GetHunterContestDataReply
local MsgCmd_GetHunterContestDataReply = class("MsgCmd_GetHunterContestDataReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.GetHunterContestDataReply
function MsgCmd_GetHunterContestDataReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_GetHunterContestDataReply
