---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiaozhu.
--- DateTime: 2022/3/8 12:26
---
---@type MainHome.MainHomeConst
local MainHomeConst = {}
---按照id（小-->大）初始化
MainHomeConst.CtrlType = {

    --点击交互相关
    TOUCH = 1,
    --点击数据
    TOUCHDATA = 2,
    --装饰,礼盒
    ORNAMENT = 3,
    --板娘玩家
    ACTOR = 4,
    --剧情
    DIALOGUE = 5,
    --UI相关
    VIEW = 6,
    --镜头相关
    CAMERA = 7,
    --网络
    NETWORK = 8,
    --交互类型
    INTERACT = 9,
    --AI
    AI = 10,
    --状态刷新
    STATE_CHECK = 11,
    --本地状态特殊处理
    LOCAL_STATE = 12,
}

---正在处理的操作类型
---@class HandlerType
MainHomeConst.HandlerType = {
    None = 0,
    ViewNormal = 1,                     ---view正常状态
    ViewChanging = 2,                   ---view正在变化
    ViewChangeFinish = 3,               ---view变化完成
    StateChanged = 4,                   ---state发生改变
    StateChangeWaitRefresh = 5,         ---state发生改变等待刷新
    IsCanRefresh = 6,                   ---是否可以刷新
    PlayDialogue = 7,                   ---播放剧情
    StopDialogue = 8,                   ---停止剧情
    PauseDialogue = 9,                  ---暂停剧情
    ResumeDialogue = 10,                ---恢复剧情
    DialogueIdle = 11,                  ---剧情播放正常状态
    DialogueChanged = 12,               ---剧情发生改变
    ActorChanged = 13,                  ---板娘发生改变
    ActorOut = 14,                      ---板娘在屏幕外
    ActorMiddle = 15,                   ---板娘在屏幕中间
    ActorFront = 16,                    ---板娘在屏幕前
    ActorShow = 17,                     ---板娘显示
    ActorIgnoreState = 18,              ---不理人状态
    ActorNormalState = 19,              ---正常状态
    SceneObjActive = 20,                ---场景显示
    WndFocus = 21,                      ---WndFocus
    ViewFocus = 22,                     ---ViewFocus
    TouchEnable = 23,                   ---屏幕点击
    GestureEnable = 24,                 ---手势
    HideMainUI = 25,                    ---隐藏主界面
    CameraEnabled = 26,                 ---相机显隐
    Transition = 27,                    ---过渡
    PosChanged = 28,                    ---坐标发生改变
    FeatureEnabled = 29,                ---特写
    ActionDialoguePlaying = 30,         ---Action剧情正在播放
    WndTouchEnable = 31,                ---界面点击
    ViewMoving = 32,                    ---主界面View发生改变
    StartTransition = 33,               ---开始过渡
    TransitionFinish = 34,              ---过渡完成
    CheckUI = 35,                       ---检查UI
    ActorLoading = 36,                  ---板娘正在加载
    ViewShow = 37,                      ---主界面view_show
    ClearAction = 38,                   ---清理Action
    RefreshOK = 39,                     ---刷新完成
    EnterOk = 40,                       ---进入完成
    LoadingClosed = 41,                 ---关闭loading
    LoadingShow = 42,                   ---loading显示
    IsCanPlayDialogue = 43,             ---是否可以播放剧情
    ActorLoading = 44,                  ---板娘正在加载
    ActorLoadFinish = 45,               ----板娘加载完成
    ActorRegisterFinish = 46,           ---板娘注册完成
    IsClearActioning = 47,              ---正在清理Action
    ActionShowRunning = 48,             ---Action正在运行
    ClearActionImmediately = 49,        ---立即清理Action
    SceneChanging = 50,                 ---场景变化ing
    DialoguePlaying = 51,               ---剧情正在播放
    RefreshFinish = 52,                 ---刷新完成
    CheckDialogue = 53,                 ---检查剧情
    FocusChanged = 54,                  ---焦点发生变化
    SceneObjActiveChanged = 55,         ---场景显隐发生变化
    ClearActionBeforeCheckAction = 56,  ---检查Action前清理Action
    WaitingErrandMgr = 57,              ---等待事务系统
    IsCanCheckAction = 58,              ---是否可以检查Action
    PostProcessEnabled = 59,            ---后处理
    SceneChanged = 60,                  ---场景变化
    ModeChanged = 61,                   ---模型变化
    CheckTransition = 62,               ---检查过渡
    TopBarActive = 63,                  ---TopBar显隐
    BtnActive = 64,                     ---按钮显隐
    CheckBtn = 65,                      ---检查按钮
    WndShow = 66,                       ---界面显示
    DoubleTouchMoving = 67,             ---双击移动ing
    ViewMoveCanClearAction = 68,        ---？？
    WaitTransition = 69,                ---等待过渡
    TimelineEnterOk = 70,               ---Timeline完成
    InitOK = 71,                        ---初始化完成
    Transitioning = 72,                 ---过渡中
    EnterView = 73,                     ---进去view
    MainHomeLocalStateChanged = 74,     ---本地状态发生改变
    MainUIOK = 75,                      ---主界面UI完成
    DialogueTransition = 76,            ---剧情过渡
    DraggingCamera = 77                  ---正在拖拽相机
}

---@class MainHomeConst.State
MainHomeConst.State =
{
    --主界面当前状态
    MainHome = 1,
    --连麦状态
    DailyConfide = 2,
}

---@class MainHomeConst.ViewType
MainHomeConst.ViewType = {
    Date = 1, --约会 
    MainHome = 2, --主界面
    Action = 3, --行动
    Interact = 4, --交互界面
}

MainHomeConst.BtnType = {
    Normal = 1,
    List = 2,
}

MainHomeConst.OrnamentType = {
    GIFT = 1, --礼盒
    LOVETOKEN = 2, --信物
    COMMON_CONDITION = 3, --条件检测
}

MainHomeConst.PosType = {
    --前排
    FRONT = 1,
    --中排
    MIDDLE = 2,
    --外出
    OUT = 3

}

---双指操作类型判断
---@class MainHomeConst.DoubleTouchType
MainHomeConst.DoubleTouchType = {
    None = 0,
    Near = 1,
    Far = 2,
}

MainHomeConst.ActorState = {
    NONE = 0,
    IDLE = 1,
    IGNORE = 2,
}

MainHomeConst.NetworkType = {
    EVENT_FINISH = 1,                           ---完成事件UIEvent
    GET_BOX_REWARD = 2,                         ---宝箱奖励
    GET_BOX_LOVE_TOKEN = 3,                     ---
    SET_EVENT = 4,                              ---设置事件ID
    MAIN_UI_REFRESH = 5,                        ---主界面状态刷新
    ADD_ROLE_INTERACTIVE_NUM = 6,               ---点击交互上报(不包含部位)
    ADD_SPECIAL_NUM = 7,                        ---
    SET_INTERACTIVE_ENABLE = 8,                 ---设置交互模式
    ADD_ROLE_INTERACT_NUM = 9,                  ---添加特殊互动次数
    CHECK_INTERACTIVE_ENABLE = 10,              ---检查交互模式是否和当前看板娘状态兼容
    ADD_ROLE_INTERACTIVE_BODY_TYPE_NUM = 11,    ---点击交互上报(包含部位)
}

---action类型
---@class MainHomeConst.ActionType
MainHomeConst.ActionType = {
    Online = "Online",
    Click = "Click",
    Idle = "Idle",
    BackMainUI = "BackMainUI",
    ClickBodyPartUnLimit = "ClickBodyPartUnLimit",
    ClickBodyPartLimit = "ClickBodyPartLimit",
    LongPress = "LongPress",
    Drag = "Drag",
    TwoFingersOperation = "TwoFingersOperation",
    Blow = "Blow",
    ShakePhone = "ShakePhone",
    CamaraFollowGyro = "CamaraFollowGyro",
    LookAtFinger = "LookAtFinger",
    Snap = "Snap",
    SnapDialogue = "SnapDialogue",
    Heartbeat = "Heartbeat",
    DailyRecipe = "DailyRecipe",
    FaceValidationIdentity = "FaceValidationIdentity",
    ScoreSpecialAction = "ScoreSpecialAction",
    ShowInteractiveUI = "ShowInteractiveUI",
    HideInteractiveUI = "HideInteractiveUI",
    EnterInteractiveState = "EnterInteractiveState",
    ExitInteractiveState = "ExitInteractiveState",
    SpecialEventHideUI = "SpecialEventHideUI",
    SpecialEventNormal = "SpecialEventNormal",
    StateRefresh = "StateRefresh",
    ChangeMainUIScene = "ChangeMainUIScene",
    TwoFingersUIShow = "TwoFingersUIShow",
    TwoFingersNearDialogue = "TwoFingersNearDialogue",
    TwoFingersFarDialogue = "TwoFingersFarDialogue",
    MidPosEnterDialogue = "MidPosEnterDialogue",
    MidPosEnter = "MidPosEnter",
    DailyConfide = "DailyConfide",
    PlayerBirthday = "PlayerBirthday" ,
    Accompany = "Accompany",
    DialogueTransition = "DialogueTransition",
    TouchCountsEffect = "TouchCountsEffect",
    ChangeCamera = "ChangeCamera",
    DragingCamera = "DragingCamera",
    TurnRoundFacingCamera = "TurnRoundFacingCamera",
    SideCamera = "SideCamera",
    SideCameraDialogue = "SideCameraDialogue",
    ChangeCameraResume = "ChangeCameraResume"
}

---@class MainHomeConst.ModeType
MainHomeConst.ModeType = {
    None = 0,
    --正常模式
    NORMAL = 1,
    --交互模式
    INTERACT = 2,
}

MainHomeConst.ChangeStatus = {
    Hand = 0,
    Auto = 1
}

MainHomeConst.TransitionType = {
    ScreenWhite = 0,            ---白屏过渡
    PlayAnimation = 1           ---播放动画过渡
}

---action关系计算
---@class MainHomeConst.ActionSwitchType
MainHomeConst.ActionSwitchType = {
    Parallel = 1,
    Break = 2,
    Wait = 3,
    Mutex = 4,
}

---处理类型
---@class MainHomeConst.ActionHandlerType
MainHomeConst.ActionHandlerType = {
    Running = 1,
    Waiting = 2,
}

---执行逻辑
---@class MainHomeConst.ActionExecute
MainHomeConst.ActionExecute = {
    None = 0,
    Run = 1,
    Pending = 2,
    Discard = 3,
    Break = 4,
}

---点击返回按钮的退出裂隙
MainHomeConst.ExitType = {
    None = 0,
    ExitSelf = 1,
    ExitInteract = 2,
}

---是否隐藏主界面
MainHomeConst.HideMainUIType = {
    Show = 0,
    Hide = 1
}

---是否可以编辑照片
MainHomeConst.HidePhotoEditType = {
    Enable = 0,
    Disable = 1
}

MainHomeConst.ActionHandlerConf = {
    [MainHomeConst.ActionSwitchType.Parallel] = {
        [MainHomeConst.ActionHandlerType.Running] = MainHomeConst.ActionExecute.Run,
        [MainHomeConst.ActionHandlerType.Waiting] = MainHomeConst.ActionExecute.Pending,
    },
    [MainHomeConst.ActionSwitchType.Break] = {
        [MainHomeConst.ActionHandlerType.Running] = MainHomeConst.ActionExecute.Break,
        [MainHomeConst.ActionHandlerType.Waiting] = MainHomeConst.ActionExecute.Break,
    },
    [MainHomeConst.ActionSwitchType.Wait] = {
        [MainHomeConst.ActionHandlerType.Running] = MainHomeConst.ActionExecute.Pending,
        [MainHomeConst.ActionHandlerType.Waiting] = MainHomeConst.ActionExecute.Pending,
    },
    [MainHomeConst.ActionSwitchType.Mutex] = {
        [MainHomeConst.ActionHandlerType.Running] = MainHomeConst.ActionExecute.Discard,
        [MainHomeConst.ActionHandlerType.Waiting] = MainHomeConst.ActionExecute.Discard,
    },
}

MainHomeConst.TouchState = {
    NONE = 0,
    DRAGING = 1,
    GESTURE = 2,
    MOVING = 3,
    BREAK = 4,
}

---@class ActionClearType
MainHomeConst.ActionClearType = {
    None = 0,
    ALL = -1,
    Focus = 1,
    ExitInteract = 2,
    ViewMoving = 3,
    Action = 4,
    DoubleTouch = 5,
    SceneActiveChanged = 6,
    ---策划预留
    State = 1101,
    Exit = 1102,
    ExitBySelf = 1103,
    
}

---@class MainHomeConst.GyroState
MainHomeConst.GyroState = {
    None = 0,
    Enable = 1,
    Disable = 2,
    ForceRefresh = 3,
    Pause = 4,
    Resume = 5,
}

MainHomeConst.ActionExitType = {
    Auto = 0,
    ExitBySelf = 1,
}

MainHomeConst.ActionStopType = {
    [MainHomeConst.ActionClearType.ViewMoving] = true,
    [MainHomeConst.ActionClearType.Focus] = true,
    [MainHomeConst.ActionClearType.Action] = true,
    [MainHomeConst.ActionClearType.ExitInteract] = true,
    [MainHomeConst.ActionClearType.DoubleTouch] = true,
    [MainHomeConst.ActionClearType.SceneActiveChanged] = true,
}

MainHomeConst.ActionBlushClearType = {
    None = 0,
    Clear = 1,
}

---@class MainHomeConst.ActionFocusBreakType
MainHomeConst.ActionFocusBreakType =
{
    Break=0,
    Pause = 1,
    Finish = 2,
    Ignore = 3,
}

MainHomeConst.Event = {
    ---内部逻辑事件---
    MAIN_HOME_SET_VIEW_ACTIVE = "MAIN_HOME_SET_VIEW_ACTIVE",
    MAIN_HOME_SET_VIEW_FOCUS = "MAIN_HOME_SET_VIEW_FOCUS",
    MAIN_HOME_SET_VIEW_CLOSE = "MAIN_HOME_SET_VIEW_CLOSE",
    MAIN_HOME_SET_VIEW_MOVING = "MAIN_HOME_SET_VIEW_MOVING",
    MAIN_HOME_REFRESH_BTN = "MAIN_HOME_REFRESH_BTN",
    MAIN_HOME_CHECK_RUNNING = "MAIN_HOME_CHECK_RUNNING",
    MAIN_HOME_SET_VIRTUAL_CAMERA_ENABLE = "MAIN_HOME_SET_VIRTUAL_CAMERA_ENABLE",
    MAIN_HOME_CHANGE_VIEW = "MAIN_HOME_CHANGE_VIEW",
    MAIN_HOME_ON_DESTROY = "MAIN_HOME_ON_DESTROY",
    MAIN_HOME_SET_TOUCH_ENABLE = "MAIN_HOME_SET_TOUCH_ENABLE",
    MAIN_HOME_SET_TOUCH_TYPE_ENABLE = "MAIN_HOME_SET_TOUCH_TYPE_ENABLE",
    MAIN_HOME_CHANGE_VIEW_TYPE = "MAIN_HOME_CHANGE_VIEW_TYPE",
    MAIN_HOME_REFRESH_ORNAMENTS = "MAIN_HOME_REFRESH_ORNAMENTS",
    MAIN_HOME_ON_CLICK_OBJ = "MAIN_HOME_ON_CLICK_OBJ",
    MAIN_HOME_ON_LONG_PRESS_OBJ = "MAIN_HOME_ON_LONG_PRESS_OBJ",
    MAIN_HOME_ADD_CHECK_OBJS = "MAIN_HOME_ADD_CHECK_OBJS",
    MAIN_HOME_SET_ROOT_ACTIVE = "MAIN_HOME_SET_ROOT_ACTIVE",
    MAIN_HOME_SET_ACTOR_ACTIVE = "MAIN_HOME_SET_ACTOR_ACTIVE",
    MAIN_HOME_ACTOR_LOAD_SUCCESS = "MAIN_HOME_ACTOR_LOAD_SUCCESS",
    MAIN_HOME_INIT_DRAG_CAMERA = "MAIN_HOME_INIT_DRAG_CAMERA",
    MAIN_HOME_TURN_ROUND_CAMERA = "MAIN_HOME_TURN_ROUND_CAMERA",
    MAIN_HOME_TURN_ROUND_START = "MAIN_HOME_TURN_ROUND_START",
    MAIN_HOME_ON_CLICK_ACTOR = "MAIN_HOME_ON_CLICK_ACTOR",
    MAIN_HOME_ON_LONG_PRESS_CLICK_ACTOR = "MAIN_HOME_ON_LONG_PRESS_CLICK_ACTOR",
    MAIN_HOME_ON_TOUCH_UP_ACTOR = "MAIN_HOME_ON_TOUCH_UP_ACTOR",
    MAIN_HOME_ON_TOUCH_DOWN_ACTOR = "MAIN_HOME_ON_TOUCH_DOWN_ACTOR",
    MAIN_HOME_ON_LOOK_AT_ACTOR = "MAIN_HOME_ON_LOOK_AT_ACTOR",
    MAIN_HOME_SEND_REQUEST = "MAIN_HOME_SEND_REQUEST",
    MAIN_HOME_RECEIVE_MSG = "MAIN_HOME_RECEIVE_MSG",
    MAIN_HOME_REFRESH_ORDER = "MAIN_HOME_REFRESH_ORDER",
    MAIN_HOME_REFRESH_STATE_VIEW_TIPS = "MAIN_HOME_REFRESH_STATE_VIEW_TIPS",
    MAIN_HOME_REFRESH_ACTOR = "MAIN_HOME_REFRESH_ACTOR",
    MAIN_HOME_CHECK_ACTOR = "MAIN_HOME_CHECK_ACTOR",
    MAIN_HOME_PLAY_TRANSITION = "MAIN_HOME_PLAY_TRANSITION",
    MAIN_HOME_PLAY_TRANSITION_BY_ANIMATION = "MAIN_HOME_PLAY_TRANSITION_BY_ANIMATION",
    MAIN_HOME_RESET_MAIN_CAMERA = "MAIN_HOME_RESET_MAIN_CAMERA",
    MAIN_HOME_SET_PPV_FEATURE_ENABLE = "MAIN_HOME_SET_PPV_FEATURE_ENABLE",
    MAIN_HOME_VIEW_FOCUS_CHANGED = "MAIN_HOME_VIEW_FOCUS_CHANGED",
    MAIN_HOME_SET_GESTURE_ENABLE = "MAIN_HOME_SET_GESTURE_ENABLE",
    MAIN_HOME_SET_WND_TOUCH_ENABLE = "MAIN_HOME_SET_WND_TOUCH_ENABLE",
    MAIN_HOME_STATE_CHANGE_REFRESH = "MAIN_HOME_STATE_CHANGE_REFRESH",
    MAIN_HOME_DIALOG_END_SP_EVENT = "MAIN_HOME_DIALOG_END_SP_EVENT",
    MAIN_HOME_ON_CLICK_ACTOR_PATCH = "MAIN_HOME_ON_CLICK_ACTOR_PATCH",
    MAIN_HOME_CLOSE_DIALOGUE = "MAIN_HOME_CLOSE_DIALOGUE",
    MAIN_HOME_MOVE_VIEW = "MAIN_HOME_MOVE_VIEW",
    MAIN_HOME_MOVE_VIEW_BACK = "MAIN_HOME_MOVE_VIEW_BACK",
    MAIN_HOME_MOVE_TIMELINE = "MAIN_HOME_MOVE_TIMELINE",
    MAIN_HOME_SET_TIMELINE_PROGRESS = "MAIN_HOME_SET_TIMELINE_PROGRESS",
    MAIN_HOME_FAST_FORWARD_TIMELINE = "MAIN_HOME_FAST_FORWARD_TIMELINE",
    MAIN_HOME_GET_VIEW_TYPE_BY_STEP = "MAIN_HOME_GET_VIEW_TYPE_BY_STEP",
    MAIN_HOME_SET_POST_PROCESS_ACTIVE = "MAIN_HOME_SET_POST_PROCESS_ACTIVE",
    MAIN_HOME_RESET_ACTOR_POS = "MAIN_HOME_RESET_ACTOR_POS",
    MAIN_HOME_CHECK_VIEW = "MAIN_HOME_CHECK_VIEW",
    MAIN_HOME_CHECK_IS_CAN_CHANGE_VIEW = "MAIN_HOME_CHECK_IS_CAN_CHANGE_VIEW",
    MAIN_HOME_FORCE_UPDATE = "MAIN_HOME_FORCE_UPDATE",
    MAIN_HOME_DIALOG_CLEAR_BY_EXIT = "MAIN_HOME_DIALOG_CLEAR_BY_EXIT",
    MAIN_HOME_CHECK_VIEW_UNLOCK = "MAIN_HOME_CHECK_VIEW_UNLOCK",
    MAIN_HOME_CHECK_OTHER_SYSTEM = "MAIN_HOME_CHECK_OTHER_SYSTEM",
    MAIN_HOME_CHECK_EVENT = "MAIN_HOME_CHECK_EVENT",
    MAIN_HOME_CHECK_EVENT_END = "MAIN_HOME_CHECK_EVENT_END",
    MAIN_HOME_ON_MODE_CHANGE = "MAIN_HOME_ON_MODE_CHANGE",
    MAIN_HOME_ENTER = "MAIN_HOME_ENTER",
    MAIN_HOME_EXIT = "MAIN_HOME_EXIT",
    MAIN_HOME_BEING_INTERACT = "MAIN_HOME_BEING_INTERACT",
    MAIN_HOME_END_INTERACT = "MAIN_HOME_END_INTERACT",
    MAIN_HOME_CHECK_ACTION = "MAIN_HOME_CHECK_ACTION",
    MAIN_HOME_CHECK_ACTION_CAN_TRIGGER = "MAIN_HOME_CHECK_ACTION_CAN_TRIGGER",
    MAIN_HOME_DIALOGUE_END = "MAIN_HOME_DIALOGUE_END",
    MAIN_HOME_SET_ACTION_SHOW_RUNNING = "MAIN_HOME_SET_ACTION_SHOW_RUNNING",
    MAIN_HOME_START_ACTION_BY_TYPE = "MAIN_HOME_START_ACTION_BY_TYPE",
    MAIN_HOME_STOP_ACTION_BY_TYPE = "MAIN_HOME_STOP_ACTION_BY_TYPE",
    MAIN_HOME_SET_ACTION_PARAM = "MAIN_HOME_SET_ACTION_PARAM",
    MAIN_HOME_SET_TOP_BAR_ENABLE = "MAIN_HOME_SET_TOP_BAR_ENABLE",
    MAIN_HOME_CLICK_TOP_BAR = "MAIN_HOME_CLICK_TOP_BAR",
    MAIN_HOME_CHECK_DIALOGUE_CHANGED = "MAIN_HOME_CHECK_DIALOGUE_CHANGED",
    MAIN_HOME_CLEAR_ACTION = "MAIN_HOME_CLEAR_ACTION",
    MAIN_HOME_HANDLE_TYPE_CHANGED = "MAIN_HOME_HANDLE_TYPE_CHANGED",
    MAIN_HOME_ACTION_ENTER = "MAIN_HOME_ACTION_ENTER",
    MAIN_HOME_ACTION_EXIT = "MAIN_HOME_ACTION_EXIT",
    MAIN_HOME_SET_WND_ACTIVE = "MAIN_HOME_SET_WND_ACTIVE",
    MAIN_HOME_CARESS_ACTOR = "MAIN_HOME_CARESS_ACTOR",
    MAIN_HOME_DIALOGUE_TRIGGER_ACTION_BY_TYPE = "MAIN_HOME_DIALOGUE_TRIGGER_ACTION_BY_TYPE",
    MAIN_HOME_SNAP_SUCCESS = "MAIN_HOME_SNAP_SUCCESS",
    MAIN_HOME_SNAP_RESELECT = "MAIN_HOME_SNAP_RESELECT",
    MAIN_HOME_STOP_ACTOR_ANI = "MAIN_HOME_STOP_ACTOR_ANI",
    MAIN_HOME_SCENE_CHANGE_REFRESH = "MAIN_HOME_SCENE_CHANGE_REFRESH",
    MAIN_HOME_STATE_REFRESH_REPLAY = "MAIN_HOME_STATE_REFRESH_REPLAY",
    MAIN_HOME_SHAKE_PHONE = "MAIN_HOME_SHAKE_PHONE",
    MAIN_HOME_SET_FOLLOW_CAMERA_STATE = "MAIN_HOME_SET_FOLLOW_CAMERA_STATE",
    MAIN_HOME_DOUBLE_TOUCH_TYPE_CHANGED = "MAIN_HOME_DOUBLE_TOUCH_TYPE_CHANGED",
    MAIN_HOME_SET_MULTI_TOUCH_ENABLE = "MAIN_HOME_SET_MULTI_TOUCH_ENABLE",
    MAIN_HOME_SET_BLOW_ENABLE = "MAIN_HOME_SET_BLOW_ENABLE",
    MAIN_HOME_SET_DIALOGUE_ACTOR = "MAIN_HOME_SET_DIALOGUE_ACTOR",
    MAIN_HOME_RELEASE_ACTOR = "MAIN_HOME_RELEASE_ACTOR",
    MAIN_HOME_SET_INTERACT_VIEW_ACTIVE = "MAIN_HOME_SET_INTERACT_VIEW_ACTIVE",
    MAIN_HOME_START_ACTION = "MAIN_HOME_START_ACTION",
    MAIN_HOME_POST_PROGRESS_ENABLE_CHANGED = "MAIN_HOME_POST_PROGRESS_ENABLE_CHANGED",
    MAIN_HOME_CAMERA_MODE_CHANGED = "MAIN_HOME_CAMERA_MODE_CHANGED",
    MAIN_HOME_DOUBLE_TOUCH_END = "MAIN_HOME_DOUBLE_TOUCH_END",
    MAIN_HOME_CHANGE_DIALOGUE_SEED = "MAIN_HOME_CHANGE_DIALOGUE_SEED",
    MAIN_HOME_CLEAR_DIALOGUE_NODE_LIST = "MAIN_HOME_CLEAR_DIALOGUE_NODE_LIST",
    MAIN_HOME_CHANGE_ACTOR_STATE = "MAIN_HOME_CHANGE_ACTOR_STATE",
    MAIN_HOME_CHECK_ACTOR_POS_TYPE = "MAIN_HOME_CHECK_ACTOR_POS_TYPE",
    MAIN_HOME_REFRESH_CHARACTER_LIGHT = "MAIN_HOME_REFRESH_CHARACTER_LIGHT",
    MAIN_HOME_SERVER_MAIN_UI_UPDATE_REPLY = "MAIN_HOME_SERVER_MAIN_UI_UPDATE_REPLY",
    MAIN_HOME_BREAK_CHANGE_VIEW = "MAIN_HOME_BREAK_CHANGE_VIEW",
    MAIN_HOME_CHECK_VIEW_BLUR = "MAIN_HOME_CHECK_VIEW_BLUR",
    MAIN_HOME_INTERACT_CHANGE_CHECK_VIEW = "MAIN_HOME_INTERACT_CHANGE_CHECK_VIEW",
    MAIN_HOME_INIT_OK = "MAIN_HOME_INIT_OK",
    MAIN_HOME_DAILY_CONFIDE_ENABLE = "DailyConfideEnable",
    MAIN_HOME_LOCAL_STATE_SUCCESS = "MAIN_HOME_LOCAL_STATE_SUCCESS",
    MAIN_HOME_REGISTER_ACTOR = "MAIN_HOME_REGISTER_ACTOR",
    MAIN_HOME_RESTORE_LOCAL_STATE = "MAIN_HOME_RESTORE_LOCAL_STATE",
    MAIN_HOME_PAUSE_CHANGED = "MAIN_HOME_PAUSE_CHANGED",
    ---timeline相关
    MAIN_HOME_TIMELINE_HIDE_BLUR = "HideBlur",
    MAIN_HOME_TIMELINE_SHOW_BLUR = "ShowBlur",
    MAIN_HOME_TIMELINE_SHOW_VIEW = "ShowView",
    MAIN_HOME_TIMELINE_HIDE_VIEW = "HideView",
    MAIN_HOME_TIMELINE_ENTER_GAME = "MainHomeEnter",
    MAIN_HOME_TIMELINE_PLAY = "MainHomeTimelinePlay",


    ---AI指令相关--
    MAIN_HOME_AI_CHANGE_VIEW = "MAIN_HOME_AI_CHANGE_VIEW",
    MAIN_HOME_AI_SET_VIEW_ACTIVE = "MAIN_HOME_AI_SET_VIEW_ACTIVE",
    MAIN_HOME_AI_SET_VIEW_FOCUS = "MAIN_HOME_AI_SET_VIEW_FOCUS",
    MAIN_HOME_AI_SET_WND_FOCUS = "MAIN_HOME_AI_SET_WND_FOCUS",
    MAIN_HOME_AI_PLAY_DRAMA = "MAIN_HOME_AI_PLAY_DRAMA",
    MAIN_HOME_AI_SEND_REQUEST = "MAIN_HOME_AI_SEND_REQUEST",
    MAIN_HOME_AI_ACTOR_STATE_CHANGED = "MAIN_HOME_AI_ACTOR_STATE_CHANGED",
    MAIN_HOME_AI_STATE_CHANGED = "MAIN_HOME_AI_STATE_CHANGED",
    MAIN_HOME_AI_CHECK_STATE = "MAIN_HOME_AI_CHECK_STATE",
    MAIN_HOME_AI_SET_IS_RUNNING = "MAIN_HOME_AI_SET_IS_RUNNING",
    MAIN_HOME_AI_SET_VIEW_MOVING = "MAIN_HOME_AI_SET_VIEW_MOVING",
    MAIN_HOME_AI_TRIGGER_INTERACT = "MAIN_HOME_AI_TRIGGER_INTERACT",
    MAIN_HOME_AI_CHECK_ACTION = "MAIN_HOME_AI_CHECK_ACTION",
    MAIN_HOME_AI_PLAY_DIALOGUE = "MAIN_HOME_AI_PLAY_DIALOGUE",
    MAIN_HOME_AI_PLAY_ACTION_DIALOGUE = "MAIN_HOME_AI_PLAY_ACTION_DIALOGUE",
    MAIN_HOME_AI_SET_ACTION_RUNNING = "MAIN_HOME_AI_SET_ACTION_RUNNING",
    MAIN_HOME_AI_SET_ACTION_TREE_RUNNING = "MAIN_HOME_AI_SET_ACTION_TREE_RUNNING",
    MAIN_HOME_AI_START_ACTION = "MAIN_HOME_AI_START_ACTION",
    MAIN_HOME_AI_STOP_ACTION = "MAIN_HOME_AI_STOP_ACTION",
    MAIN_HOME_AI_SET_WAITING_SHOW = "MAIN_HOME_AI_SET_WAITING_SHOW",
    MAIN_HOME_AI_LOCAL_STATE_CHANGED = "MAIN_HOME_AI_LOCAL_STATE_CHANGED",
    
    ---强制完成Action
    MAIN_HOME_FORCE_FINISH_ACTION = "MAIN_HOME_FORCE_FINISH_ACTION",

    ---切换场景相关---
    MAIN_HOME_CHANGE_SCENE_START = "MAIN_HOME_CHANGE_SCENE_START",
    MAIN_HOME_CHANGE_SCENE_FINISH = "MAIN_HOME_CHANGE_SCENE_FINISH",
    MAIN_HOME_CHANGE_SCENE_ACTION = "MAIN_HOME_CHANGE_SCENE_ACTION",
    MAIN_HOME_BEGIN_LOAD_SCENE = "MAIN_HOME_BEGIN_LOAD_SCENE",
    MAIN_HOME_LOADED_SCENE = "MAIN_HOME_LOADED_SCENE",
    MAIN_HOME_POST_PROGRESS_FORCE_DISABLE = "MAIN_HOME_POST_PROGRESS_FORCE_DISABLE",

    ---心跳感应相关---
    MAIN_HOME_HEARTBEAT_CD = "MAIN_HOME_HEARTBEAT_CD",
    ---主界面交互CD事件----
    MAIN_HOME_INTERACT_CD = "MAIN_HOME_INTERACT_CD",

    MAIN_HOME_HEARTBEART_END = "MAIN_HOME_HEARTBEART_END",

    MAIN_HOME_SNAP_END = "MAIN_HOME_SNAP_END",

    MAIN_HOME_LOADING_FINISH = "MAIN_HOME_LOADING_FINISH",
    MAIN_HOME_LOADING_MOVEOUT_FINISH = "MAIN_HOME_LOADING_MOVEOUT_FINISH",
    
    MAIN_HOME_REFRESH_CHANGE_BUTTON = "MAIN_HOME_REFRESH_CHANGE_BUTTON",
    
    ---时装相关
    MainUI_Action_ChangeFashion = "MainUI_Action_ChangeFashion",

    ---倾诉相关
    MAIN_HOME_DAILY_CONFIDE_TRIGGER = "MAIN_HOME_DAILY_CONFIDE_TRIGGER",

    ---陪伴
    MAIN_HOME_ACCOMPANY_TRIGGER = "MAIN_HOME_ACCOMPANY_TRIGGER",
    MAIN_HOME_ACCOMPANY_RECONNECT = "MAIN_HOME_ACCOMPANY_RECONNECT",
    
    MAIN_HOME_CHANGE_LOCK_STATE = "MAIN_HOME_CHANGE_LOCK_STATE",

    ---主界面Enter并且LoadActorFinish
    MAIN_HOME_ENTER_AND_ACTOR_LOADED = "MAIN_HOME_ENTER_AND_ACTOR_LOADED",
}

return MainHomeConst