---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by junjun003.
--- DateTime: 2022/1/14 14:36
---

---@class DialogueMoveAction:DialogueBaseAction
local DialogueMoveAction = class("DialogueMoveAction", require("Runtime.System.X3Game.Modules.Dialogue.Action.DialogueBaseAction"), nil, true)

---ActionInit
---@param cfg
function DialogueMoveAction:OnInit(cfg)
    self.super.OnInit(self, cfg)
    ---@type DynamicTarget 行为目标
    self.target = cfg.target
    ---@type Vector3
    self.targetPosition = cfg.targetPosition
    ---@type Quaternion
    self.targetRotation = cfg.targetRotation
    ---@type boolean
    self.moveImmediately = cfg.moveImmediately
    ---@type GameObject
    self.targetGO = nil
    ---@type X3Animator
    self.targetAnim = nil
    ---@type Vector3
    self.startPosition = nil
    ---@type Quaternion
    self.startRotation = nil
end

---ActionEnter
function DialogueMoveAction:OnEnter()
    self.targetGO = self.system:GetDynamicTarget(self.target)
    if self.targetGO then
        if self.moveImmediately then
            self.startPosition = self.targetPosition
            self.startRotation = self.targetRotation
        else
            self.startPosition = GameObjectUtil.GetPosition(self.targetGO)
            self.startRotation = GameObjectUtil.GetRotation(self.targetGO)
        end

        if self.target.targetType == DialogueEnum.DynamicTargetType.Actor or
                self.target.targetType == DialogueEnum.DynamicTargetType.ActorTag then
            self.targetAnim = GameObjectUtil.EnsureCSComponent(self.targetGO, typeof(CS.X3Game.X3Animator))
        end
    end
end

---Process函数
---@param progress float
---@return DialogueEnum.UpdateActionState
function DialogueMoveAction:OnProcess(progress)
    if self.targetGO then
        self:SetPosition(Vector3.Lerp(self.startPosition, self.targetPosition, progress))
        self:SetRotation(Quaternion.Lerp(self.startRotation, self.targetRotation, progress))
    end
    return self.super.OnProcess(self, progress)
end

---设置位置
---@param position Vector3
function DialogueMoveAction:SetPosition(position)
    if self.targetAnim then
        self.targetAnim:SetPosition(position.x, position.y, position.z)
    elseif self.targetGO then
        GameObjectUtil.SetPosition(self.targetGO, position)
    end
end

---设置旋转
---@param rotation Quaternion
function DialogueMoveAction:SetRotation(rotation)
    if self.targetAnim then
        self.targetAnim:SetRotation(rotation.x, rotation.y, rotation.z, rotation.w)
    elseif self.targetGO then
        GameObjectUtil.SetRotation(self.targetGO, rotation)
    end
end

return DialogueMoveAction