---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by junjun003.
--- DateTime: 2023/9/26 19:31
---

---@class DialogueResetAnimStateAction：DialogueBaseAction
local DialogueResetAnimStateAction = class("DialogueResetAnimStateAction", require("Runtime.System.X3Game.Modules.Dialogue.Action.DialogueBaseAction"), nil, true)

---ActionInit
function DialogueResetAnimStateAction:OnInit(cfg)
    self.super.OnInit(self, cfg)
    ---@type DynamicTarget 执行目标
    self.target = cfg.target
end

---ActionEnter
function DialogueResetAnimStateAction:OnEnter()
    local actor = self.system:GetDynamicTarget(self.target)
    self.x3Animator = GameObjectUtil.EnsureCSComponent(actor, typeof(CS.X3Game.X3Animator))
    if GameObjectUtil.IsNull(self.x3Animator) == false then
        local defaultStateName = self.x3Animator.DefaultStateName
        self.x3Animator:ResetCtsStates()
        self.x3Animator:SetDefaultState(defaultStateName)
    else
        Debug.Log("没有找到X3Animator")
    end
end

return DialogueResetAnimStateAction