ConditionTypeClient = {
    [0] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1] = { Bll = "ConditionCheckBLL", Proto = {"BaseExpUpdateReply", "GetBaseDataReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [2] = { Bll = "ConditionCheckBLL", Proto = {"UpdateRoleLoveDataReply", "RoleUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [3] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [4] = { Bll = "ConditionCheckBLL", Proto = {"ItemUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [5] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [6] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [7] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [8] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [801] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [802] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [901] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [902] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [903] = { Bll = "MainHomeBLL", Proto = {"CustomRecordUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [904] = { Bll = "MainHomeBLL", Proto = {"CustomRecordUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [920] = { Bll = "FashionBLL", Proto = {"FashionDressUpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [921] = { Bll = "FashionBLL", Proto = {"FashionDressUpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [950] = { Bll = "CompanyBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [951] = { Bll = "CompanyBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [952] = { Bll = "CompanyBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [953] = { Bll = "CompanyBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1001] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1002] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1003] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1004] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1005] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1010] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1011] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1013] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|4", }},
    [1017] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1018] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1019] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1020] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1021] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1022] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1023] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1024] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1025] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1026] = { Bll = "UFOCatcherBLL", Proto = {"CatchDollReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1027] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1028] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1029] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|4", "GameplayCommonData|5", }},
    [1030] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1201] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1202] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1203] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1204] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1205] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1206] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1207] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1208] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1209] = { Bll = "UFOCatcherBLL", Proto = {"ReduceCountReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1401] = { Bll = "DailyDateBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|6", }},
    [1402] = { Bll = "BlockTowerBLL", Proto = {"GetBlockTowerDataReply", "MoveBlockTowerBlockReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1403] = { Bll = "BlockTowerBLL", Proto = {"GetBlockTowerDataReply", "MoveBlockTowerBlockReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1404] = { Bll = "BlockTowerBLL", Proto = {"GetBlockTowerDataReply", "MoveBlockTowerBlockReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1405] = { Bll = "BlockTowerBLL", Proto = {"GetBlockTowerDataReply", "MoveBlockTowerBlockReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1406] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1407] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1408] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1409] = { Bll = "BlockTowerBLL", Proto = {"ReduceBlockTowerCountReply", "MoveBlockTowerBlockReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1410] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1411] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1412] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1413] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1500] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1501] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1502] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1503] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1504] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1505] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1506] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1507] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1508] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1509] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1510] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1511] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1512] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1513] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1514] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1515] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1516] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1517] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1518] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1519] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [1520] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [4003] = { Bll = "SpecialDateBLL", Proto = {"GetSpecialDateTreeReply", "CheckSpecialDateDialogueReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [4004] = { Bll = "SpecialDateBLL", Proto = {"EnterSpecialDateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [4005] = { Bll = "SpecialDateBLL", Proto = {"GetSpecialDateRewardReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [5001] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [5002] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [5003] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [6000] = { Bll = "ChapterAndStageBLL", Proto = {"StageUpdateReply", "BuyStageTimesReply", "FinStageReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [6001] = { Bll = "ChapterAndStageBLL", Proto = {"StageUpdateReply", "BuyStageTimesReply", "FinStageReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [6002] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [6003] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [8001] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [8002] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [8003] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [8004] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9001] = { Bll = "PlayerBLL", Proto = {"BaseExpUpdateReply", "GetBaseDataReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9002] = { Bll = "TaskBLL", Proto = {"QuestUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9003] = { Bll = "ChapterAndStageBLL", Proto = {"BuyStageTimesReply", "StageUpdateReply", "FinStageReply", "DungeonEndReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9004] = { Bll = "CardBLL", Proto = {"CardUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9005] = { Bll = "CardBLL", Proto = {"CardUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9006] = { Bll = "CardBLL", Proto = {"CardUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9007] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9008] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9009] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9010] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9011] = { Bll = "CollectionRoomBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9013] = { Bll = "UnLockBLL", Proto = {"SetUnlockReply, ", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9014] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9015] = { Bll = "SoulTrialBLL", Proto = {"SoulTrialUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9016] = { Bll = "FashionBLL", Proto = {"FashionDressUpReply", "FashionSelfDressReply", "GirlFashionChangeReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9017] = { Bll = "FashionBLL", Proto = {"FashionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9019] = { Bll = "FashionBLL", Proto = {"FashionDressUpReply", "FashionSelfDressReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9020] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9021] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9022] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9023] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9024] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9025] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9026] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9028] = { Bll = "MainHomeBLL", Proto = {"RecordUpdateReply", "RecordGroupUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9029] = { Bll = "NoviceGuideBLL", Proto = {"GuideUpdateReply", "SetGuideReply", "GuideFinishReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9030] = { Bll = "NoviceGuideBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9033] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9034] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [9500] = { Bll = "GachaBLL", Proto = {"GachaOne", "GachaTen", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [101000] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"DoubleTouchType|2", }},
    [101001] = { Bll = "MainInteractBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"MainHomeData|2", }},
    [101002] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"ActionRecord|2", }},
    [101003] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"MainHomeData|3", }},
    [101004] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"MainHomeData|4", }},
    [101005] = { Bll = "MainInteractBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [101006] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"MainHomeData|5", }},
    [101007] = { Bll = "BGMBLL", Proto = {"BGMUnlockSongUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [101008] = { Bll = "BGMBLL", Proto = {"BGMUnlockSongUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [101009] = { Bll = "DailyConfideBll", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"DailyConfideData|6", }},
    [101010] = { Bll = "DailyConfideBll", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"DailyConfideData|6", }},
    [101011] = { Bll = "FashionBLL", Proto = {"FinStageReply", "DungeonEndReply", "FashionDressUpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [101012] = { Bll = "MainHomeBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [102000] = { Bll = "UFOCatcherBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103001] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103003] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103004] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103005] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103006] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103007] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103008] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103009] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|4", }},
    [103010] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|4", "GameplayCommonData|5", }},
    [103011] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103012] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103013] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103014] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103015] = { Bll = "CatCardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [103016] = { Bll = "CatCardBLL", Proto = {"GetMiaoRewardReply", } , CustomRecord = {}, UserRecord = {10017, }, X3Datas = {}},
    [103017] = { Bll = "CatCardBLL", Proto = {"GetMiaoRewardReply", } , CustomRecord = {}, UserRecord = {10019, }, X3Datas = {}},
    [105000] = { Bll = "SpecialDateBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [106000] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [106001] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [106002] = { Bll = "PhoneMsgBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [107000] = { Bll = "LovePointBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [107001] = { Bll = "LovePointBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointRole|2", }},
    [107002] = { Bll = "LovePointBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [108000] = { Bll = "FashionBLL", Proto = {"FashionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [108001] = { Bll = "FashionBLL", Proto = {"FashionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [108002] = { Bll = "FashionBLL", Proto = {"FashionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [110000] = { Bll = "AccompanyBLL", Proto = {"StopAccompanyReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [111000] = { Bll = "CollectionRoomBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [111001] = { Bll = "CollectionRoomBLL", Proto = {"CollectionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [112000] = { Bll = "BlockTowerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [112001] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|4", }},
    [112002] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GameplayCommonData|4", "GameplayCommonData|5", }},
    [112003] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [112004] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [112005] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [112006] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [112007] = { Bll = "GameplayBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [113000] = { Bll = "PhotoSystemBLL", Proto = {"PhotoComponentUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [114000] = { Bll = "RadioNewBLL", Proto = {"ReportBroadcastingPlayReply", "QuitBroadcastingPlayReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [115001] = { Bll = "ReturnActivityBll", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [115002] = { Bll = "ReturnActivityBll", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [116000] = { Bll = "DailyDateBLL", Proto = {} , CustomRecord = {2, }, UserRecord = {}, X3Datas = {}},
    [202000] = { Bll = "MonthCardBLLReplace", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"MonthCardData|2", }},
    [202001] = { Bll = "MonthCardBLLReplace", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"MonthCardData|4", }},
    [202003] = { Bll = "BattlePassBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [202004] = { Bll = "BattlePassBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [203000] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [204000] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [206000] = { Bll = "GachaBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [206001] = { Bll = "GachaBLL", Proto = {"GachaOneReply", "GachaTenReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [206002] = { Bll = "GachaBLL", Proto = {"GachaOneReply", "GachaTenReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [206003] = { Bll = "GachaBLL", Proto = {"GachaClose", "GachaOpen", "GachaOne", "GachaTen", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [208000] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209000] = { Bll = "FriendBLL", Proto = {"FriendApplyAcceptReply", "FriendDelReply", "FriendInfoUpdateReply", "GetFriendDataReply", "GetFriendSimpleDataReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209001] = { Bll = "PlayerFavoriteBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209002] = { Bll = "PlayerFavoriteBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209003] = { Bll = "PlayerFavoriteBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209004] = { Bll = "PlayerFavoriteBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209005] = { Bll = "MiaoGachaBLL", Proto = {"MiaoGachaUpdateReply", "MiaoGachaReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209006] = { Bll = "MiaoGachaBLL", Proto = {"MiaoGachaUpdateReply", "MiaoGachaReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209007] = { Bll = "PlayerBLL", Proto = {"BaseExpUpdateReply", "GetBaseDataReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209008] = { Bll = "GalleryNewBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"GalleryRecord|2", }},
    [209009] = { Bll = "OthersBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209010] = { Bll = "PlayerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"Coin|2", }},
    [209011] = { Bll = "DailyDateBLL", Proto = {"CollectionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209012] = { Bll = "DailyDateBLL", Proto = {"CollectionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209013] = { Bll = "DailyDateBLL", Proto = {"CollectionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209014] = { Bll = "DailyDateBLL", Proto = {} , CustomRecord = {}, UserRecord = {10018, }, X3Datas = {}},
    [209015] = { Bll = "PlayerFavoriteBLL", Proto = {"PlayerChooseUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"PlayerChoose", }},
    [209016] = { Bll = "PlayerFavoriteBLL", Proto = {"AcceptRecommendReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"PlayerRecommend", }},
    [209017] = { Bll = "DailyDateBLL", Proto = {"CollectionUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209018] = { Bll = "DailyRoutineBLL", Proto = {"SyncRoleStateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [209019] = { Bll = "PlayerFavoriteBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"PlayerChoose", }},
    [209020] = { Bll = "PlayerFavoriteBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"PlayerChoose", }},
    [209021] = { Bll = "LoginBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [210000] = { Bll = "ConditionCheckBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [210001] = { Bll = "SystemSettingBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [211000] = { Bll = "PlayerBLL", Proto = {"TitleUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [211001] = { Bll = "PlayerBLL", Proto = {"SetNicknameReply", "SetBaseInfoReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [212000] = { Bll = "EasterEggBLL", Proto = {"EasterEggEffectReply", "EasterEggTriggerReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [301000] = { Bll = "DungeonRecordBLL", Proto = {"DungeonRecordUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [301001] = { Bll = "DungeonRecordBLL", Proto = {"DungeonRecordUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [301002] = { Bll = "DungeonRecordBLL", Proto = {"DungeonRecordUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [301003] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [301004] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [301005] = { Bll = "ChapterAndStageBLL", Proto = {"DungeonEndReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [303000] = { Bll = "SoulTrialBLL", Proto = {"SoulTrialUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [303001] = { Bll = "SoulTrialBLL", Proto = {"SoulTrialUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [306000] = { Bll = "GemCoreBLL", Proto = {"GemCoreUpdateReply", "GemCoreLevelUpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306001] = { Bll = "ScoreBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306002] = { Bll = "ScoreBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306003] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306004] = { Bll = "CardBLL", Proto = {"CardUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306005] = { Bll = "CardBLL", Proto = {"CardUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306006] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", "SCoreAddExpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306007] = { Bll = "CardBLL", Proto = {"CardUpdateReply", "CardAddExpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306008] = { Bll = "ScoreBLL", Proto = {"SCoreUpdateReply", "SCoreUpgradeStarReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306009] = { Bll = "CardBLL", Proto = {"CardUpdateReply", "CardStarUpReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306010] = { Bll = "CardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"CardData", }},
    [306011] = { Bll = "CardBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"CardQuestData", "CardSuitQuestData", }},
    [306012] = { Bll = "CardBLL", Proto = {"CardProgressReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306013] = { Bll = "CardBLL", Proto = {"CardAwakenReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306014] = { Bll = "CardBLL", Proto = {"CardAwakenReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306015] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306016] = { Bll = "ChapterAndStageBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [306017] = { Bll = "CardBLL", Proto = {"CardUpdateReply", "CardProgressReply", "ItemUpdateReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [401000] = { Bll = "", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [401001] = { Bll = "ActivityCenterBLL", Proto = {"ActivityTotalLoginClaimReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"Activity|2", }},
    [401002] = { Bll = "ActivityCenterBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"ActivityDialogue|4", }},
    [401003] = { Bll = "ActivityCenterBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"ActivityDialogue|4", }},
    [401100] = { Bll = "PlayerBirthdayBLL", Proto = {"UpdateBirthdayDataReply", "GetBirthdayDataReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [401101] = { Bll = "PlayerBirthdayBLL", Proto = {"UpdateBirthdayDataReply", "GetBirthdayDataReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {"LovePointTimeRecord|2", }},
    [401105] = { Bll = "ActivityDIYModelBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"ActivityDiyModel", }},
    [401200] = { Bll = "PlayerBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [401201] = { Bll = "ActivityCenterBLL", Proto = {"ActivityTotalLoginClaimReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
    [401202] = { Bll = "ActivityGrowUpBLL", Proto = {} , CustomRecord = {}, UserRecord = {}, X3Datas = {"ActivityGrowUpData|2", }},
    [401301] = { Bll = "ActivityScoreBLL", Proto = {"ActivityCMSConfigGetReply", } , CustomRecord = {}, UserRecord = {}, X3Datas = {}},
}
return ConditionTypeClient