--- Generated by AutoGen
---
---@class MsgCmd_DungeonUpdateReply
local MsgCmd_DungeonUpdateReply = class("MsgCmd_DungeonUpdateReply", require("Runtime.System.Framework.GameBase.Misc.SimpleCommand"))

---Command执行
---@param reply pbcmessage.DungeonUpdateReply
function MsgCmd_DungeonUpdateReply:Execute(reply)
    ---Insert Your Code Here!
end

return MsgCmd_DungeonUpdateReply
